# -*- coding: utf-8 -*-
"""Chapter_16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZedC9SH1AuN4oD0tI_b2SrGXwl_edUAi
"""

# -*- coding: utf-8 -*-
"""
chapter_16_validation_reporting.py
=====================================
Hands-On Electroretinography in the Age of AI
Chapter 16 – Model Validation and TRIPOD-AI Reporting

Implements the complete validation and reporting pipeline:

  AUDIT INTEGRITY (§16.2)
    verify_sap_hash              – SHA-256 check of pre-registered SAP document

  INTERNAL VALIDATION (§16.3)
    run_stratified_cv            – Five-fold stratified patient-level group CV

  EXTERNAL VALIDATION (§16.4)
    verify_centre_stratification – Zero-overlap check between train and ext. centres

  PER-CLASS PERFORMANCE (§16.5)
    delong_auc_ci                – AUC + 95% CI via DeLong (1988) method
    compute_per_class_auc        – One-vs-rest AUC for all classes
    compute_calibration_metrics  – Calibration curves + Brier Score per class

  BATCH HARMONISATION (§16.6)
    apply_combat_harmonisation   – ComBat device/site batch-effect removal

  INTEGRATED REPORTING (§16.7)
    build_validation_report      – Machine-readable Model Card JSON structure

Locked thresholds (pre-registered SAP):
  Stage 1 minimum sensitivity  : 0.90
  Stage 2 minimum sensitivity  : 0.75 per class
  External AUC deployment gate : 0.88 (Albasu et al. 2024 reference)
  Brier Score warning threshold: 0.25
  Calibration n_bins           : 10
  ComBat RMSE maximum          : 15% of source mean

Repository : https://github.com/AI-Fairness-com/ERG-Analysis-API
Author     : Hamid
Licence    : See repo root LICENSE
"""

# ── Dependencies ───────────────────────────────────────────────────────────────
# Run once in your Colab session:
#   !pip install scikit-learn scipy pandas matplotlib neuroCombat -q
# neuroCombat is optional (apply_combat_harmonisation degrades gracefully).

import os
import json
import hashlib
import datetime
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

from scipy import stats
from sklearn.model_selection   import StratifiedGroupKFold
from sklearn.calibration       import calibration_curve
from sklearn.metrics           import brier_score_loss
from sklearn.preprocessing     import label_binarize

# ── Locked project constants ───────────────────────────────────────────────────
N_FOLDS               = 5
RANDOM_SEED           = 42
STAGE1_MIN_SENS       = 0.90
STAGE2_MIN_SENS       = 0.75
BRIER_WARN            = 0.25
DELONG_ALPHA          = 0.05
CALIBRATION_N_BINS    = 10
ALBASU_REF_AUC        = 0.888   # Albasu et al. (2024) ViT Small macro-AUC

ALL_CLASSES = [
    'Normal',
    'Diabetic Retinopathy (early)',
    'Glaucoma (early)',
    'Retinitis Pigmentosa / Rod Dystrophy',
    'Age-Related Macular Degeneration',
    'Cone Dystrophy',
    'Complete CSNB',
]


# ══════════════════════════════════════════════════════════════════════════════
# 1. SAP pre-registration hash verification
# ══════════════════════════════════════════════════════════════════════════════

def verify_sap_hash(sap_path:        str  = 'docs/SAP_v1.0.pdf',
                    registered_hash: str  = None) -> dict:
    """Compute SHA-256 hash of the SAP document and compare to registered hash.

    Must be called at the start of every validation script to confirm that the
    Statistical Analysis Plan has not been modified after pre-registration.
    Any discrepancy must be declared as a deviation from the pre-registered plan
    before analysis proceeds.

    Parameters
    ----------
    sap_path : str
        Path to the SAP PDF file.
    registered_hash : str or None
        Expected SHA-256 hex digest from the OSF registration record.
        If None, the computed hash is printed for manual recording — no
        comparison is made and no exception is raised.

    Returns
    -------
    dict with keys: sap_path, computed_hash, registered_hash,
                    hash_match (bool or None), verified_at

    Raises
    ------
    ValueError if registered_hash is provided and does not match.
    """
    with open(sap_path, 'rb') as f:
        computed = hashlib.sha256(f.read()).hexdigest()

    match = (computed == registered_hash) if registered_hash else None
    result = {
        'sap_path'       : sap_path,
        'computed_hash'  : computed,
        'registered_hash': registered_hash,
        'hash_match'     : match,
        'verified_at'    : datetime.datetime.now().isoformat(),
    }

    if match is False:
        raise ValueError(
            'SAP document hash does not match the pre-registered hash. '
            'Do not proceed with analysis until the discrepancy is resolved. '
            'Any analysis performed with a modified SAP must be declared as '
            'a deviation from the pre-registered plan.')

    print(f"SAP hash verified: {'MATCH' if match else 'UNREGISTERED (record hash now)'}  "
          f"[{computed[:16]}...]")
    return result


# ══════════════════════════════════════════════════════════════════════════════
# 2. Five-fold stratified patient-level cross-validation
# ══════════════════════════════════════════════════════════════════════════════

def run_stratified_cv(df:           pd.DataFrame,
                      feature_cols: list,
                      label_col:    str = 'label',
                      patient_col:  str = 'patient_id',
                      n_splits:     int = N_FOLDS,
                      random_state: int = RANDOM_SEED) -> dict:
    """Five-fold stratified group cross-validation (patient-level splitting).

    Splitting is performed at the patient level (StratifiedGroupKFold):
    all recordings from one patient are assigned to exactly one fold,
    preventing patient-level data leakage between train and validation sets.

    Stratification ensures that the proportion of each disease class is
    preserved in every fold (critical for Complete CSNB, minimum N=60).

    Splitting is performed before STFT spectrogram extraction — the fold
    indices are saved and applied to the spectrogram dataset in the same order.

    Parameters
    ----------
    df : pd.DataFrame – one row per recording
    feature_cols : list of str – feature column names
    label_col : str – integer class label column
    patient_col : str – patient identifier column
    n_splits : int – number of folds (default 5)
    random_state : int

    Returns
    -------
    dict with keys: n_splits, random_state, fold_results (list), leakage_check
    Each fold_result has: fold, train_idx, val_idx, n_train, n_val.
    """
    rng         = np.random.default_rng(random_state)
    shuffle_idx = rng.permutation(len(df))
    df          = df.iloc[shuffle_idx].reset_index(drop=True)

    X      = df[feature_cols].values
    y      = df[label_col].values
    groups = df[patient_col].values

    sgkf         = StratifiedGroupKFold(n_splits=n_splits, shuffle=True,
                                        random_state=random_state)
    fold_results = []

    for fold_idx, (train_idx, val_idx) in enumerate(sgkf.split(X, y, groups)):
        y_tr  = y[train_idx]
        y_val = y[val_idx]

        # Strict patient-level leakage check
        tr_patients  = set(groups[train_idx])
        val_patients = set(groups[val_idx])
        assert len(tr_patients & val_patients) == 0, \
            f'DATA LEAKAGE: {len(tr_patients & val_patients)} patients in both sets.'

        # Stratification check: StratifiedGroupKFold enforces this
        # algorithmically. We warn (not assert) so small synthetic
        # datasets do not crash on legitimate sampling variation.
        for cls in np.unique(y):
            p_tr  = float((y_tr  == cls).mean())
            p_val = float((y_val == cls).mean())
            if abs(p_tr - p_val) > 0.10:
                warnings.warn(
                    f'Fold {fold_idx+1}: class {cls} proportion '
                    f'differs >10pp (train={p_tr:.3f}, val={p_val:.3f}).')

        cls_counts = {int(k): int(v)
                      for k, v in zip(*np.unique(y_val, return_counts=True))}
        print(f'  Fold {fold_idx+1}: train={len(y_tr)}, val={len(y_val)}, '
              f'classes={cls_counts}')
        fold_results.append({
            'fold'     : fold_idx + 1,
            'train_idx': train_idx,
            'val_idx'  : val_idx,
            'n_train'  : len(y_tr),
            'n_val'    : len(y_val),
        })

    return {
        'n_splits'    : n_splits,
        'random_state': random_state,
        'fold_results': fold_results,
        'leakage_check': 'PASS',
    }


# ══════════════════════════════════════════════════════════════════════════════
# 3. Centre-level leakage prevention
# ══════════════════════════════════════════════════════════════════════════════

def verify_centre_stratification(train_df:   pd.DataFrame,
                                  ext_df:     pd.DataFrame,
                                  centre_col: str = 'centre_id') -> dict:
    """Verify no external validation centre appears in the training set.

    External validation centres must be completely independent of the training
    set. Any overlap invalidates the external validation results and must be
    corrected before reporting.

    External centre IDs must follow the 'EXT_' prefix naming convention to
    prevent accidental training inclusion in future data collection rounds.

    Parameters
    ----------
    train_df, ext_df : pd.DataFrame – must contain centre_col
    centre_col : str

    Returns
    -------
    dict with keys: status, train_centres, ext_centres, overlap_detected

    Raises
    ------
    ValueError if any overlap is detected.
    """
    train_centres = set(train_df[centre_col].unique())
    ext_centres   = set(ext_df[centre_col].unique())
    overlap       = train_centres & ext_centres

    if overlap:
        raise ValueError(
            f'DATA LEAKAGE DETECTED: {len(overlap)} centre(s) appear in both '
            f'training and external validation sets: {overlap}. '
            f'Remove all recordings from these centres from the training set '
            f'before proceeding. External validation results computed with '
            f'this leakage are invalid and must not be reported.')

    non_prefixed = [c for c in ext_centres if not str(c).startswith('EXT_')]
    if non_prefixed:
        warnings.warn(
            f'External centres {non_prefixed} do not follow the EXT_ naming '
            f'convention. Add EXT_ prefix to prevent accidental training inclusion.')

    print('Centre stratification verified: PASS')
    print(f'  Training centres : {sorted(train_centres)}')
    print(f'  External centres : {sorted(ext_centres)}')
    print(f'  Overlap          : NONE')

    return {
        'status'          : 'PASS',
        'train_centres'   : sorted(train_centres),
        'ext_centres'     : sorted(ext_centres),
        'overlap_detected': False,
    }


# ══════════════════════════════════════════════════════════════════════════════
# 4. AUC-ROC with DeLong 95% CI
# ══════════════════════════════════════════════════════════════════════════════

def delong_auc_ci(y_true:  np.ndarray,
                  y_score: np.ndarray,
                  alpha:   float = DELONG_ALPHA) -> dict:
    """Compute AUC-ROC and 95% CI using the DeLong method.

    Implements DeLong, DeLong & Clarke-Pearson (1988).
    Uses structural component (placement value) decomposition for
    variance estimation — more accurate than bootstrap for AUC, and
    explicitly required by TRIPOD-AI guidelines.

    Parameters
    ----------
    y_true  : np.ndarray – binary labels (0/1) for one class (one-vs-rest)
    y_score : np.ndarray – predicted probability for the positive class
    alpha   : float – significance level (default 0.05 → 95% CI)

    Returns
    -------
    dict with keys: auc, ci_lower, ci_upper, se, n_pos, n_neg
    Returns None values with a message if insufficient cases.
    """
    pos = y_score[y_true == 1]
    neg = y_score[y_true == 0]
    n1, n0 = len(pos), len(neg)

    if n1 == 0 or n0 == 0:
        return {'auc': None, 'ci_lower': None, 'ci_upper': None,
                'se': None, 'message': 'Insufficient cases for AUC computation.'}

    # Placement values (structural components)
    pv_pos = np.array([np.mean(p > neg) + 0.5 * np.mean(p == neg)
                       for p in pos])
    pv_neg = np.array([np.mean(n < pos) + 0.5 * np.mean(n == pos)
                       for n in neg])

    auc    = float(np.mean(pv_pos))
    var_pv = (np.var(pv_pos, ddof=1) / n1) + (np.var(pv_neg, ddof=1) / n0)
    se     = float(np.sqrt(var_pv))
    z      = stats.norm.ppf(1 - alpha / 2)
    ci_lo  = max(0.0, auc - z * se)
    ci_hi  = min(1.0, auc + z * se)

    return {
        'auc'     : round(auc,   4),
        'ci_lower': round(ci_lo, 4),
        'ci_upper': round(ci_hi, 4),
        'se'      : round(se,    5),
        'n_pos'   : n1,
        'n_neg'   : n0,
    }


def compute_per_class_auc(y_true:      np.ndarray,
                           y_proba:     np.ndarray,
                           class_names: list) -> dict:
    """Compute one-vs-rest AUC with DeLong 95% CI for each class.

    Parameters
    ----------
    y_true : np.ndarray, shape (n_samples,) – integer class labels
    y_proba : np.ndarray, shape (n_samples, n_classes) – predicted probabilities
    class_names : list of str

    Returns
    -------
    dict {class_name: delong_result} plus 'macro_average' key
    """
    n_classes = len(class_names)
    y_bin     = label_binarize(y_true, classes=list(range(n_classes)))
    results   = {}

    for c, name in enumerate(class_names):
        results[name] = delong_auc_ci(y_bin[:, c], y_proba[:, c])
        r = results[name]
        if r['auc'] is not None:
            print(f'  {name:38s}: AUC={r["auc"]:.4f} '
                  f'[{r["ci_lower"]:.4f}–{r["ci_upper"]:.4f}]')
        else:
            print(f'  {name:38s}: {r["message"]}')

    valid_aucs = [v['auc'] for v in results.values() if v['auc'] is not None]
    macro_auc  = round(float(np.mean(valid_aucs)), 4) if valid_aucs else None
    print(f'  {"Macro-average":38s}: AUC={macro_auc:.4f}')
    results['macro_average'] = {'auc': macro_auc}
    return results


# ══════════════════════════════════════════════════════════════════════════════
# 5. Calibration curves and Brier Score
# ══════════════════════════════════════════════════════════════════════════════

def compute_calibration_metrics(y_true:      np.ndarray,
                                 y_proba_cal: np.ndarray,
                                 class_names: list,
                                 n_bins:      int   = CALIBRATION_N_BINS,
                                 output_dir:  str   = 'outputs/validation',
                                 brier_warn:  float = BRIER_WARN) -> dict:
    """Compute calibration curves and Brier Score per class (§16.5.3).

    Produces an 8-panel reliability diagram (7 classes + unused panel).
    CALIBRATION_WARNING is raised for any class with Brier Score > brier_warn.
    Classes exceeding the threshold must NOT appear in clinical probability
    outputs until Platt scaling is rerun on a larger calibration set.

    Parameters
    ----------
    y_true : np.ndarray, shape (n_samples,) – integer class labels
    y_proba_cal : np.ndarray, shape (n_samples, n_classes) – Platt-scaled probs
    class_names : list of str
    n_bins : int – number of probability bins for reliability diagram
    output_dir : str
    brier_warn : float – CALIBRATION_WARNING threshold (default 0.25)

    Returns
    -------
    dict with keys: per_class {class_name: brier_score}, macro (float)
    """
    os.makedirs(output_dir, exist_ok=True)
    n_classes = len(class_names)
    y_bin     = label_binarize(y_true, classes=list(range(n_classes)))

    fig, axes = plt.subplots(2, 4, figsize=(20, 10))
    axes_flat = axes.flatten()
    brier_scores = {}

    for c, name in enumerate(class_names):
        bs = float(brier_score_loss(y_bin[:, c], y_proba_cal[:, c]))
        brier_scores[name] = round(bs, 4)

        frac_pos, mean_pred = calibration_curve(
            y_bin[:, c], y_proba_cal[:, c],
            n_bins=n_bins, strategy='uniform')

        ax = axes_flat[c]
        ax.plot([0, 1], [0, 1], '--', color='#CCCCCC', linewidth=1)
        ax.plot(mean_pred, frac_pos, 'o-', color='#2E75B6',
                linewidth=2, markersize=6)
        ax.set_title(f'{name}\nBrier={bs:.3f}'
                     + (' ⚠' if bs > brier_warn else ''),
                     fontsize=9, fontweight='bold')
        ax.set_xlabel('Mean predicted probability', fontsize=8)
        ax.set_ylabel('Fraction of positives', fontsize=8)
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.grid(True, alpha=0.2)

        if bs > brier_warn:
            warnings.warn(
                f'CALIBRATION_WARNING: {name} Brier Score {bs:.4f} > '
                f'{brier_warn}. This class must NOT appear in clinical '
                f'probability outputs until Platt scaling is rerun on a '
                f'larger calibration set.',
                UserWarning,
            )

    axes_flat[-1].axis('off')   # 8th panel unused
    plt.suptitle('Per-Class Calibration Plots (Post Platt Scaling)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    plot_path = os.path.join(output_dir, 'calibration_plots.png')
    plt.savefig(plot_path, dpi=150, bbox_inches='tight')
    plt.close()

    macro_brier = round(float(np.mean(list(brier_scores.values()))), 4)
    print(f'Brier Scores: {brier_scores}')
    print(f'Macro Brier : {macro_brier}')
    print(f'Saved: {plot_path}')

    return {'per_class': brier_scores, 'macro': macro_brier}


# ══════════════════════════════════════════════════════════════════════════════
# 6. ComBat batch effect harmonisation
# ══════════════════════════════════════════════════════════════════════════════

def apply_combat_harmonisation(feature_matrix: np.ndarray,
                                batch_labels:   np.ndarray,
                                covariates:     pd.DataFrame,
                                fit_params:     dict = None,
                                feature_names:  list = None) -> dict:
    """Apply ComBat harmonisation to remove device/site batch effects (§16.6.1).

    ⚠️  CRITICAL: fit_params=None fits ComBat on the provided data.
    Always fit on training data only. Pass the returned fit_params to
    all subsequent calls on validation and test data.

    Requires: pip install neuroCombat

    Parameters
    ----------
    feature_matrix : np.ndarray, shape (n_samples, n_features)
    batch_labels : np.ndarray, shape (n_samples,) – device/site label per sample
    covariates : pd.DataFrame – must contain 'age_strata' and 'sex' columns
                 (biological covariates that should NOT be removed)
    fit_params : dict or None
        None  → fit new ComBat model on the provided data (training only)
        dict  → apply pre-fitted parameters (validation / test / deployment)
    feature_names : list of str, optional – for logging

    Returns
    -------
    dict with keys: harmonised_features (np.ndarray), combat_params (dict),
                    n_batches (int), n_features (int)
    """
    try:
        from neuroCombat import neuroCombat
    except ImportError:
        raise ImportError(
            'neuroCombat is required for ComBat harmonisation. '
            'Install with: pip install neuroCombat')

    # neuroCombat expects (n_features, n_samples) — transpose
    data_T = feature_matrix.T
    covars_dict = {
        'age_strata': covariates['age_strata'].map(
            {'le35': 0, '36to59': 1, 'ge60': 2}).values,
        'sex':        covariates['sex'].map({'M': 0, 'F': 1}).values,
        'batch':      batch_labels,
    }
    covars_df = pd.DataFrame(covars_dict)

    if fit_params is None:
        result     = neuroCombat(
            dat             = data_T,
            covars          = covars_df,
            batch_col       = 'batch',
            continuous_cols = [],
            categorical_cols= ['age_strata', 'sex'],
        )
        harmonised = result['data'].T
        fit_params = result['estimates']
        print('ComBat fitted on training data.')
        print(f'  Batches identified : {np.unique(batch_labels).tolist()}')
        print(f'  Features harmonised: {data_T.shape[0]}')
    else:
        from neuroCombat import neuroCombat_harmonize
        harmonised = neuroCombat_harmonize(
            dat       = data_T,
            estimates = fit_params,
            batch_col = 'batch',
            covars    = covars_df,
        ).T
        print('ComBat applied using pre-fitted parameters.')

    return {
        'harmonised_features': harmonised,
        'combat_params'      : fit_params,
        'n_batches'          : int(len(np.unique(batch_labels))),
        'n_features'         : int(data_T.shape[0]),
    }


# ══════════════════════════════════════════════════════════════════════════════
# 7. Integrated validation report
# ══════════════════════════════════════════════════════════════════════════════

def build_validation_report(internal_cv_results: dict,
                             external_auc:        dict,
                             brier_scores:        dict,
                             combat_params:       dict,
                             sap_hash:            str,
                             class_names:         list,
                             model_version:       str = 'v1.0.0') -> dict:
    """Assemble a machine-readable validation report for the Model Card (§16.7).

    Serialises to JSON and saves to outputs/validation/validation_report.json.
    Structure complies with TRIPOD-AI (Collins et al., 2024).

    Parameters
    ----------
    internal_cv_results : dict – from run_stratified_cv()
    external_auc : dict – from compute_per_class_auc() on external data
    brier_scores : dict – from compute_calibration_metrics()
    combat_params : dict – from apply_combat_harmonisation()
    sap_hash : str – SHA-256 hex digest from verify_sap_hash()
    class_names : list of str
    model_version : str

    Returns
    -------
    dict – full validation report structure
    """
    os.makedirs('outputs/validation', exist_ok=True)

    macro_ext = external_auc.get('macro_average', {}).get('auc')
    deployment_cleared = (macro_ext is not None
                          and macro_ext >= ALBASU_REF_AUC)

    report = {
        'model_version'          : model_version,
        'generated_at'           : datetime.datetime.now().isoformat(),
        'sap_hash_verified'      : sap_hash,
        'validation_standard'    : 'TRIPOD-AI (Collins et al., 2024)',
        'normative_reference'    : ('Robson et al. (2025), '
                                    'DOI:10.1007/s10633-025-10009-2'),
        'primary_outcome'        : ('Macro-AUC-ROC, Stage 2 six-class, '
                                    'external validation'),
        'stage1_binary': {
            'classifier'         : 'ViT Small, Hamming STFT',
            'minimum_sensitivity': STAGE1_MIN_SENS,
            'auc_internal_point' : '[computed from internal CV]',
            'auc_external_point' : '[computed from external validation]',
            'auc_external_95ci'  : '[DeLong method]',
            'deployment_cleared' : deployment_cleared,
        },
        'stage2_multiclass': {
            'classifier'              : 'ViT Small, Hamming STFT, 6-class',
            'macro_auc_internal'      : '[computed]',
            'macro_auc_external'      : macro_ext,
            'macro_auc_albasu_ref'    : ALBASU_REF_AUC,
            'per_class_auc'           : external_auc,
            'brier_scores'            : brier_scores,
            'calibration_method'      : 'Platt scaling (Chapter 14)',
            'minimum_class_sensitivity': STAGE2_MIN_SENS,
            'classes_below_threshold' : '[list of classes with sensitivity < 0.75]',
        },
        'batch_harmonisation': {
            'method'               : 'ComBat (neuroCombat)',
            'batch_variable'       : 'device_manufacturer',
            'biological_covariates': ['age_strata', 'sex'],
            'n_batches'            : combat_params.get('n_batches'),
            'params_path'          : 'outputs/validation/combat_params.pkl',
        },
        'fair_data': {
            'principles'     : 'Wilkinson et al. (2016)',
            'data_doi'       : '[OSF DOI on data release]',
            'model_weights_url': ('github.com/AI-Fairness-com/'
                                  'ERG-Analysis-API/releases'),
        },
        'tripod_ai_compliance' : 'docs/tripod_ai_compliance.csv',
        'performance_table_path': 'outputs/validation/performance_table.csv',
        'calibration_plot_path' : 'outputs/validation/calibration_plots.png',
    }

    report_path = 'outputs/validation/validation_report.json'
    with open(report_path, 'w') as f:
        json.dump(report, f, indent=2, default=str)
    print(f'Validation report saved: {report_path}')
    return report


# ══════════════════════════════════════════════════════════════════════════════
# Smoke test
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    rng = np.random.default_rng(RANDOM_SEED)
    N_REC   = 500
    N_CLASS = 7
    N_FEAT  = 28

    # ── Synthetic dataset ─────────────────────────────────────────────────
    class_p  = [0.28, 0.18, 0.15, 0.12, 0.10, 0.09, 0.08]
    y_all    = rng.choice(N_CLASS, size=N_REC, p=class_p)
    X_all    = rng.normal(0, 1, (N_REC, N_FEAT)).astype(np.float32)
    for c in range(N_CLASS):
        X_all[y_all == c, 0] += c * 1.5
    pat_ids  = np.repeat(np.arange(N_REC // 2), 2)[:N_REC]

    feat_names = [f'feat_{i:02d}' for i in range(N_FEAT)]
    df_all     = pd.DataFrame(X_all, columns=feat_names)
    df_all['label']      = y_all
    df_all['patient_id'] = pat_ids
    df_all['centre_id']  = np.where(pat_ids < N_REC // 4, 'SITE_A', 'SITE_B')

    # ── 1. SAP hash (synthetic) ───────────────────────────────────────────
    print('=== SAP hash verification ===')
    sap_dummy = '/tmp/dummy_sap.pdf'
    with open(sap_dummy, 'wb') as f:
        f.write(b'%PDF dummy SAP content for smoke test')
    sap_result = verify_sap_hash(sap_dummy, registered_hash=None)
    sap_hash   = sap_result['computed_hash']
    print(f'  Hash: {sap_hash[:24]}...\n')

    # ── 2. Stratified CV ──────────────────────────────────────────────────
    print('=== Five-fold stratified CV ===')
    cv_result = run_stratified_cv(df_all, feat_names, n_splits=N_FOLDS)
    print(f'  Leakage check: {cv_result["leakage_check"]}\n')

    # ── 3. Centre stratification ──────────────────────────────────────────
    print('=== Centre stratification ===')
    train_df = df_all[df_all.centre_id.isin(['SITE_A', 'SITE_B'])].copy()
    ext_df   = df_all.sample(80, random_state=42).copy()
    ext_df['centre_id'] = 'EXT_IRAN_001'
    verify_centre_stratification(train_df, ext_df)
    print()

    # ── 4. Per-class AUC with DeLong CI ───────────────────────────────────
    print('=== Per-class AUC (DeLong CI) ===')
    # Simulate calibrated probabilities: softmax of noisy class signal
    logits = rng.normal(0, 1, (N_REC, N_CLASS)).astype(float)
    for c in range(N_CLASS):
        logits[y_all == c, c] += 3.0
    e = np.exp(logits - logits.max(axis=1, keepdims=True))
    y_proba = e / e.sum(axis=1, keepdims=True)
    auc_results = compute_per_class_auc(y_all, y_proba, ALL_CLASSES)
    print()

    # ── 5. Calibration metrics ────────────────────────────────────────────
    print('=== Calibration metrics ===')
    os.makedirs('outputs/validation', exist_ok=True)
    cal_result = compute_calibration_metrics(
        y_all, y_proba, ALL_CLASSES, output_dir='outputs/validation')
    print()

    # ── 6. AUC forest plot ────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(9, 5))
    cls_list = [n for n in ALL_CLASSES if auc_results.get(n, {}).get('auc')]
    aucs  = [auc_results[n]['auc']      for n in cls_list]
    cis_lo = [auc_results[n]['ci_lower'] for n in cls_list]
    cis_hi = [auc_results[n]['ci_upper'] for n in cls_list]
    yerr  = [np.array(aucs) - np.array(cis_lo),
             np.array(cis_hi) - np.array(aucs)]
    y_pos = np.arange(len(cls_list))
    ax.barh(y_pos, aucs, xerr=yerr, color='#2E75B6', ecolor='#1F4E79',
            capsize=4, alpha=0.85)
    ax.axvline(ALBASU_REF_AUC, color='red', ls='--', lw=1.2,
               label=f'Albasu et al. 2024 reference ({ALBASU_REF_AUC})')
    ax.axvline(0.5, color='gray', ls=':', lw=0.8, label='Chance (0.5)')
    ax.set_yticks(y_pos)
    ax.set_yticklabels([c[:30] for c in cls_list], fontsize=9)
    ax.set_xlabel('AUC-ROC  (95% CI, DeLong method)', fontsize=10)
    ax.set_title('Chapter 16 – Per-Class AUC Forest Plot\n'
                 '(synthetic data smoke test)', fontsize=11, fontweight='bold')
    ax.legend(fontsize=9)
    ax.set_xlim(0.4, 1.05)
    ax.grid(True, axis='x', alpha=0.25)
    plt.tight_layout()
    plt.savefig('ch16_fig1_auc_forest.png', dpi=150, bbox_inches='tight')
    print('Saved: ch16_fig1_auc_forest.png')

    # ── 7. Validation report ──────────────────────────────────────────────
    print('\n=== Build validation report ===')
    report = build_validation_report(
        internal_cv_results = cv_result,
        external_auc        = auc_results,
        brier_scores        = cal_result['per_class'],
        combat_params       = {'n_batches': 2},
        sap_hash            = sap_hash,
        class_names         = ALL_CLASSES,
        model_version       = 'v1.0.0',
    )
    print(f'  deployment_cleared: {report["stage1_binary"]["deployment_cleared"]}')
    print(f'  macro_auc_external: {report["stage2_multiclass"]["macro_auc_external"]}')

    plt.show()