# -*- coding: utf-8 -*-
"""Appendices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-Rg3i8uwE6xkWXyDhlOACKiYd1QeT8w
"""

# -*- coding: utf-8 -*-
"""
appendices_a_to_f.py
======================
Hands-On Electroretinography in the Age of AI
Appendices A – F

  Appendix A  Standardised ERG CSV Schema
  Appendix B  FHIR Integration (reference only – JSON examples in /data/fhir_examples/)
  Appendix C  Sample Size and Power Calculations (Hanley-McNeil method)
  Appendix D  Model Card Template (reference – full JSON via Chapter 17)
  Appendix E  TRIPOD-AI Compliance Checklist (reference table)
  Appendix F  Installation and Environment Setup
               F.1  Google Colab (recommended for book readers)
               F.2  Local installation: Windows / macOS / Linux
               F.3  requirements.txt (locked dependency list)
               F.4  Docker container (Mode B offline API deployment)
               F.5  Installation verification script

Repository : https://github.com/AI-Fairness-com/ERG-Analysis-API
Author     : Hamid
Licence    : See repo root LICENSE
"""

import os
import sys
import numpy as np
from scipy import stats


# ══════════════════════════════════════════════════════════════════════════════
# APPENDIX A – Standardised ERG CSV Schema
# ══════════════════════════════════════════════════════════════════════════════
"""
Every ERG recording submitted to the API must conform to the Standardised
ERG CSV schema below. All fields are required unless marked optional.

Required columns (in any order):
  patient_id            – string  : anonymous patient identifier
  recording_date        – string  : ISO 8601 date (YYYY-MM-DD)
  age_years             – integer : patient age at recording
  sex                   – string  : M / F / Other
  eye                   – string  : OD / OS / OU
  electrode_type        – string  : contact_lens / gold_foil / dtl_fiber / skin
  device_manufacturer   – string  : device make and model
  protocol              – string  : DA_0.01 / DA_3.0 / DA_10.0 / LA_3.0 / LA_30Hz
  centre_id             – string  : recording centre identifier (prefix EXT_ for external)
  time_ms               – float   : time axis in milliseconds (one row per sample)
  amplitude_uv          – float   : ERG amplitude in microvolts (one row per sample)

Derived / pre-computed columns (optional; computed by pipeline if absent):
  b_wave_amplitude_uv   – float   : ISCEV trough-to-peak b-wave amplitude (µV)
  b_wave_implicit_time_ms – float : b-wave implicit time (ms)
  a_wave_amplitude_uv   – float   : ISCEV baseline-to-trough a-wave amplitude (µV)
  a_wave_implicit_time_ms – float : a-wave implicit time (ms)
  ba_ratio              – float   : b/a amplitude ratio (absolute values)
  phnr_amplitude_uv     – float   : PhNR amplitude (LA 3.0 only, µV)
  op2_amplitude_uv      – float   : OP2 amplitude (µV)
  op2_implicit_time_ms  – float   : OP2 implicit time (ms)
  op_power_ratio        – float   : OP/b-wave Welch PSD power ratio
  snr_db                – float   : signal-to-noise ratio (dB)
  flash_duration_ms     – float   : stimulus flash duration (ms) — optional
  dark_adaptation_min   – float   : dark adaptation duration (min) — DA protocols

Notes
-----
- The ba_ratio must be computed as abs(b_wave_amplitude_uv) / abs(a_wave_amplitude_uv)
  to ensure the ratio is positive regardless of waveform polarity conventions.
  This must be stated explicitly in any methods section.
- OP detection follows Chapter 9 §9.1.5: OP1 excluded (peaks before 25 ms
  post-stimulus); OP2 is the first valid peak at or after 25 ms.
- Fixed OP search window: 25–80 ms post-stimulus for standard ISCEV protocols.
- The centre_id field must use the EXT_ prefix for all external validation
  centres (Chapter 16 §16.4) to prevent accidental training inclusion.
"""

# CSV header string for programmatic file creation
CSV_SCHEMA_HEADER = (
    'patient_id,recording_date,age_years,sex,eye,electrode_type,'
    'device_manufacturer,protocol,centre_id,'
    'b_wave_amplitude_uv,b_wave_implicit_time_ms,'
    'a_wave_amplitude_uv,a_wave_implicit_time_ms,ba_ratio,'
    'phnr_amplitude_uv,op2_amplitude_uv,op2_implicit_time_ms,'
    'op_power_ratio,snr_db,flash_duration_ms,dark_adaptation_min,'
    'time_ms,amplitude_uv'
)

REQUIRED_FIELDS = [
    'patient_id', 'recording_date', 'age_years', 'sex', 'eye',
    'electrode_type', 'device_manufacturer', 'protocol', 'centre_id',
    'time_ms', 'amplitude_uv',
]

VALID_ELECTRODE_TYPES = ['contact_lens', 'gold_foil', 'dtl_fiber', 'skin']
VALID_PROTOCOLS       = ['DA_0.01', 'DA_3.0', 'DA_10.0', 'LA_3.0', 'LA_30Hz']
VALID_EYES            = ['OD', 'OS', 'OU']


# ══════════════════════════════════════════════════════════════════════════════
# APPENDIX C – Sample Size and Power Calculations
# ══════════════════════════════════════════════════════════════════════════════

def hanley_mcneil_sample_size(assumed_auc: float,
                               alpha:       float = 0.05 / 7,
                               power:       float = 0.80) -> dict:
    """Compute minimum positive-class sample size for AUC power.

    Implements the Hanley and McNeil (1982) method.

    Reference
    ---------
    Hanley JA, McNeil BJ. The meaning and use of the area under a receiver
    operating characteristic (ROC) curve. Radiology. 1982;143(1):29-36.

    Parameters
    ----------
    assumed_auc : float
        Expected AUC for the classifier on this disease class.
    alpha : float
        Significance level (two-tailed).
        Default is 0.05/7 = 0.0071 (Bonferroni-corrected for seven
        simultaneous one-vs-rest AUC tests; Appendix C §C.5).
    power : float
        Required statistical power (default 0.80).

    Returns
    -------
    dict with keys: assumed_auc, min_n_pos, min_n_neg, total_min_n,
                    training_n, alpha, power.
    training_n is set to 3 × min_n_pos to account for the 70/20/10
    train/val/test split (minimum in the training partition = min_n_pos).

    Notes
    -----
    The values returned by this function are the Hanley-McNeil minimum
    only. Table C.6 in the appendix shows higher Phase 1 targets because
    they incorporate the Riley et al. (2020) prediction model criterion
    (§C.3) applied in addition to the Hanley-McNeil criterion. Use the
    PHASE1_TARGETS dict for the book's locked target sample sizes.

    Assumes equal numbers of positive and negative cases (balanced evaluation
    set). For imbalanced evaluation sets, adjust min_n_neg separately.
    The Bonferroni-corrected alpha for seven simultaneous one-vs-rest tests
    is alpha / 7 = 0.0071 (Appendix C §C.5).
    """
    z_alpha = stats.norm.ppf(1 - alpha / 2)   # 1.960 at alpha=0.05
    z_beta  = stats.norm.ppf(power)            # 0.842 at power=0.80

    def _auc_variance(auc: float, n_pos: int, n_neg: int) -> float:
        Q1 = auc / (2 - auc)
        Q2 = 2 * auc ** 2 / (1 + auc)
        return (
            auc * (1 - auc)
            + (n_pos - 1) * (Q1 - auc ** 2)
            + (n_neg - 1) * (Q2 - auc ** 2)
        ) / (n_pos * n_neg)

    for n in range(10, 2000):
        var_null = _auc_variance(0.5,         n, n)
        var_alt  = _auc_variance(assumed_auc, n, n)
        required = z_alpha * np.sqrt(var_null) + z_beta * np.sqrt(var_alt)
        if (assumed_auc - 0.5) >= required:
            return {
                'assumed_auc' : assumed_auc,
                'min_n_pos'   : n,
                'min_n_neg'   : n,
                'total_min_n' : 2 * n,
                'training_n'  : 3 * n,
                'alpha'       : alpha,
                'power'       : power,
            }

    return {'error': 'No solution found within n=2000. Check assumed_auc > 0.5.'}


# Phase 1 target sample sizes (Appendix C, Table C.6)
PHASE1_TARGETS = {
    'Normal'                          : {'assumed_auc': 0.95, 'target_n': 200},
    'Diabetic Retinopathy (early)'    : {'assumed_auc': 0.88, 'target_n': 150},
    'Glaucoma (early)'                : {'assumed_auc': 0.86, 'target_n': 120},
    'Retinitis Pigmentosa / Rod Dystrophy': {'assumed_auc': 0.95, 'target_n': 80},
    'Age-Related Macular Degeneration': {'assumed_auc': 0.82, 'target_n': 100},
    'Cone Dystrophy'                  : {'assumed_auc': 0.88, 'target_n': 60},
    'Complete CSNB'                   : {'assumed_auc': 0.93, 'target_n': 60},
}


# ══════════════════════════════════════════════════════════════════════════════
# APPENDIX F – Installation verification script
# ══════════════════════════════════════════════════════════════════════════════

def verify_installation(data_path: str = 'data/synthetic/case02_early_dr.csv') -> dict:
    """Verify that all pipeline dependencies are correctly installed.

    Run this script from the repository root after installation.
    Expected output: all stages PASS.

    Parameters
    ----------
    data_path : str
        Path to the Chapter 3 synthetic sample CSV file (relative to repo root).

    Returns
    -------
    dict {stage_name: 'PASS ...' or 'FAIL: <error message>'}
    """
    results = {}
    print(f'Python version: {sys.version}')

    # Stage 1: Core scientific stack
    try:
        import numpy as np        # noqa: F401
        import scipy.signal       # noqa: F401
        import pandas as pd       # noqa: F401
        import matplotlib         # noqa: F401
        results['core_stack'] = 'PASS'
    except ImportError as e:
        results['core_stack'] = f'FAIL: {e}'

    # Stage 2: Biosignal I/O
    try:
        import mne                # noqa: F401
        results['mne'] = f'PASS (mne {mne.__version__})'
    except ImportError as e:
        results['mne'] = f'FAIL: {e}'

    # Stage 3: Machine learning
    try:
        import sklearn            # noqa: F401
        import imblearn           # noqa: F401
        results['ml_stack'] = 'PASS'
    except ImportError as e:
        results['ml_stack'] = f'FAIL: {e}'

    # Stage 4: Deep learning
    try:
        import torch
        import timm
        model = timm.create_model(
            'vit_small_r26_s32_224', pretrained=False, num_classes=7)
        del model
        results['deep_learning'] = (
            f'PASS (torch {torch.__version__}, '
            f'CUDA: {torch.cuda.is_available()})')
    except Exception as e:
        results['deep_learning'] = f'FAIL: {e}'

    # Stage 5: Explainability
    try:
        import shap               # noqa: F401
        results['shap'] = 'PASS'
    except ImportError as e:
        results['shap'] = f'FAIL: {e}'

    # Stage 6: Batch harmonisation (optional)
    try:
        from neuroCombat import neuroCombat   # noqa: F401
        results['neuroCombat'] = 'PASS'
    except ImportError as e:
        results['neuroCombat'] = f'FAIL (optional): {e}'

    # Stage 7: FHIR output (optional)
    try:
        from fhir.resources.observation import Observation   # noqa: F401
        results['fhir'] = 'PASS'
    except ImportError as e:
        results['fhir'] = f'FAIL (optional): {e}'

    # Stage 8: Load synthetic ERG data (Chapter 3 sample)
    try:
        import pandas as pd
        df = pd.read_csv(data_path)
        assert len(df) > 0, 'Empty dataframe'
        results['sample_data'] = f'PASS ({len(df)} rows loaded)'
    except Exception as e:
        results['sample_data'] = f'FAIL: {e}'

    # Print results
    print('\n=== Installation Verification Results ===')
    all_pass = True
    for stage, status in results.items():
        icon = 'OK  ' if status.startswith('PASS') else 'FAIL'
        print(f'  [{icon}] {stage:<25s}: {status}')
        if status.startswith('FAIL') and 'optional' not in status:
            all_pass = False

    print()
    if all_pass:
        print('All required stages PASS. Pipeline is ready.')
    else:
        print('One or more required stages FAILED. '
              'Run: pip install -r requirements.txt')
    return results


# ══════════════════════════════════════════════════════════════════════════════
# APPENDIX F – requirements.txt (locked dependency list)
# ══════════════════════════════════════════════════════════════════════════════

REQUIREMENTS_TXT = """\
# ERG Analysis API – locked dependency list
# Generated for Python 3.11
# Install with: pip install -r requirements.txt

# ── Core scientific stack ──────────────────────────────────────────────────
numpy==1.26.4
scipy==1.13.0
pandas==2.2.2
matplotlib==3.9.0
scikit-image==0.23.2

# ── Biosignal I/O ──────────────────────────────────────────────────────────
mne==1.7.1

# ── Wavelet transforms ────────────────────────────────────────────────────
PyWavelets==1.6.0

# ── Machine learning ──────────────────────────────────────────────────────
scikit-learn==1.5.0
imbalanced-learn==0.12.3
statsmodels==0.14.2

# ── Deep learning ─────────────────────────────────────────────────────────
# PyTorch: install the CUDA-enabled version for GPU support.
# Visit https://pytorch.org/get-started for the correct command for your system.
# The CPU-only version is installed here as a safe default:
torch==2.3.0
torchvision==0.18.0
timm==0.9.16

# ── Explainability ────────────────────────────────────────────────────────
shap==0.45.1

# ── Batch harmonisation (optional) ───────────────────────────────────────
neuroCombat==0.2.12

# ── FHIR output (optional) ────────────────────────────────────────────────
fhir.resources==7.1.0

# ── Power and sample size ─────────────────────────────────────────────────
# (scipy.stats is used directly; no additional package required)

# ── API server (Mode A cloud deployment) ─────────────────────────────────
fastapi==0.111.0
uvicorn[standard]==0.30.1
pydantic==2.7.1

# ── Utilities ─────────────────────────────────────────────────────────────
joblib==1.4.2
tqdm==4.66.4
"""

DOCKERFILE = """\
# ── ERG Analysis API Dockerfile ──────────────────────────────────────────────
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install system dependencies required by MNE-Python and neuroCombat
RUN apt-get update && apt-get install -y \\
    libgomp1 \\
    libglib2.0-0 \\
    libsm6 \\
    libxext6 \\
    libxrender-dev \\
    git \\
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies first (Docker layer caching)
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \\
    pip install --no-cache-dir -r requirements.txt

# Copy pipeline source code
COPY src/     ./src/
COPY api/     ./api/
COPY models/  ./models/
COPY data/ISCEV_ffERG_reference_data.xlsx ./data/
COPY data/cor_table_dtl_v1.pkl            ./data/
COPY config/  ./config/

# Set environment variables
ENV PYTHONPATH=/app/src
ENV ERG_MODEL_VERSION=v1.0.0
ENV ERG_NORMATIVE_VERSION=Robson2025_v1

# Expose FastAPI port
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s \\
    CMD curl -f http://localhost:8000/health || exit 1

# Start the FastAPI server
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""


# ══════════════════════════════════════════════════════════════════════════════
# Helpers: write requirements.txt and Dockerfile to disk
# ══════════════════════════════════════════════════════════════════════════════

def write_requirements(path: str = 'requirements.txt') -> None:
    """Write the locked requirements.txt to disk."""
    with open(path, 'w') as f:
        f.write(REQUIREMENTS_TXT)
    print(f'Saved: {path}')


def write_dockerfile(path: str = 'Dockerfile') -> None:
    """Write the Dockerfile to disk."""
    with open(path, 'w') as f:
        f.write(DOCKERFILE)
    print(f'Saved: {path}')


# ══════════════════════════════════════════════════════════════════════════════
# Smoke test
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    import matplotlib.pyplot as plt

    # ── Appendix C: sample size table ─────────────────────────────────────
    print('=== Appendix C – Sample Size Calculations (Hanley-McNeil) ===\n')
    print(f'{"Disease Class":<40s} {"AUC":>6s} {"min_n_pos":>10s} {"training_N":>12s}')
    print('-' * 72)
    for cls, info in PHASE1_TARGETS.items():
        r = hanley_mcneil_sample_size(info['assumed_auc'])
        if 'error' not in r:
            print(f'{cls:<40s} {info["assumed_auc"]:>6.2f} '
                  f'{r["min_n_pos"]:>10d} {r["training_n"]:>12d}')
        else:
            print(f'{cls:<40s}  ERROR: {r["error"]}')

    # ── Power curve figure ─────────────────────────────────────────────────
    auc_range = np.linspace(0.60, 0.99, 80)
    n_required = []
    for auc in auc_range:
        r = hanley_mcneil_sample_size(auc)
        n_required.append(r.get('min_n_pos', np.nan))

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(auc_range, n_required, color='#2E75B6', lw=2)
    ax.axhline(60,  color='#F9A825', ls='--', lw=1.2,
               label='Minimum feasible N (rare disease, N=60)')
    ax.axhline(100, color='#2E7D32', ls='--', lw=1.2,
               label='Conservative minimum (N=100)')
    for cls, info in PHASE1_TARGETS.items():
        r = hanley_mcneil_sample_size(info['assumed_auc'])
        if 'error' not in r:
            ax.scatter(info['assumed_auc'], r['min_n_pos'],
                       s=60, zorder=5, color='#C62828')
    ax.set_xlabel('Assumed AUC', fontsize=11)
    ax.set_ylabel('Minimum positive-class N (80% power)', fontsize=11)
    ax.set_title('Appendix C – Hanley-McNeil Sample Size Requirements\n'
                 '(α=0.05, power=0.80, balanced evaluation set)',
                 fontsize=11, fontweight='bold')
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig('appendix_c_sample_size.png', dpi=150, bbox_inches='tight')
    print('\nSaved: appendix_c_sample_size.png')

    # ── Appendix F: write artefacts ───────────────────────────────────────
    print('\n=== Appendix F – Writing installation artefacts ===')
    write_requirements('requirements.txt')
    write_dockerfile('Dockerfile')

    # ── Appendix F: run verification (will FAIL on most items in sandbox) ─
    print('\n=== Appendix F – Installation verification ===')
    verify_installation(data_path='data/synthetic/case02_early_dr.csv')

    plt.show()