# -*- coding: utf-8 -*-
"""Chapter_17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGGpyZZ_pYoJg7Z5HKvJ30e1FuvIAM8x
"""

# -*- coding: utf-8 -*-
"""
chapter_17_model_card_drift.py
================================
Hands-On Electroretinography in the Age of AI
Chapter 17 – Model Card and Post-Deployment Monitoring

Implements the Model Card generation and drift detection pipeline:

  VERSION CONTROL (§17.3)
    generate_version_stamp      – SHA-256 stamp for every API report
    compare_version_stamps      – Serial report version comparison + clinical flag

  DRIFT DETECTION (§17.4)
    shewhart_auc_monitor        – Shewhart rolling AUC control chart
                                  (3-sigma limits, sudden shift detection)
    page_hinkley_drift_test     – Page-Hinkley test for gradual monotonic drift

  MODEL CARD (§17.5)
    build_model_card_json       – Google Model Card 2.0 JSON generator

Locked constants (pre-registered SAP / TRIPOD-AI):
  Semantic versioning     : MAJOR.MINOR.PATCH
    MAJOR – normative reference or model architecture change
    MINOR – feature set or training data change
    PATCH – calibration or bug fix
  Drift detection windows : 90-day rolling AUC baseline
  Shewhart sigma limits   : 2.0 (WARNING), 3.0 (OUT_OF_CONTROL)
  Page-Hinkley parameters : delta=0.01, lambda=50
  Revalidation schedule   : 12-month mandatory + drift-triggered

Reference performance (Albasu et al. 2024 point estimates):
  Stage 1 AUC ≥ 0.94  (binary Normal vs Abnormal)
  Stage 2 macro-AUC 0.888  (six disease classes)
  All must be replaced with project-specific figures before regulatory submission.

Repository : https://github.com/AI-Fairness-com/ERG-Analysis-API
Author     : Hamid
Licence    : See repo root LICENSE
"""

# ── Dependencies ───────────────────────────────────────────────────────────────
# Run once in your Colab session:
#   !pip install pandas matplotlib -q

import os
import json
import hashlib
import datetime
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ── Locked project constants ───────────────────────────────────────────────────
SIGMA_WARNING       = 2.0
SIGMA_ALARM         = 3.0
BASELINE_DAYS       = 90
PH_DELTA            = 0.01    # Page-Hinkley tolerated mean shift (AUC units)
PH_LAMBDA           = 50.0    # Page-Hinkley alarm threshold
REVALIDATION_MONTHS = 12

ALBASU_STAGE1_AUC   = 0.94    # Albasu et al. (2024) reference estimate
ALBASU_STAGE2_AUC   = 0.888   # Albasu et al. (2024) reference estimate


# ══════════════════════════════════════════════════════════════════════════════
# 1. Version stamp generation and comparison
# ══════════════════════════════════════════════════════════════════════════════

def generate_version_stamp(api_version:        str,
                            model_weights_path: str,
                            config_dict:        dict,
                            normative_version:  str) -> dict:
    """Generate a version stamp for embedding in every API report.

    The stamp is stored in the Layer 4 audit record of every report. Any
    field change across two reports signals a version boundary and triggers
    a VERSION_MISMATCH warning in the Layer 3 Specialist Report header.

    Parameters
    ----------
    api_version : str
        Semantic version string, e.g. '1.0.0'.
    model_weights_path : str
        Path to the .pt model weights file. SHA-256 hash is computed.
    config_dict : dict
        Config-API reproducibility dictionary (Chapter 8 STFT_CONFIG et al.).
        SHA-256 hash of the JSON-serialised dict is stored.
    normative_version : str
        Normative dataset version identifier, e.g. 'Robson2025_v1'.

    Returns
    -------
    dict with keys: api_version, model_weights_hash, config_hash,
                    normative_ref_version, generated_at
    """
    def sha256_file(path: str) -> str:
        with open(path, 'rb') as f:
            return hashlib.sha256(f.read()).hexdigest()

    def sha256_dict(d: dict) -> str:
        return hashlib.sha256(
            json.dumps(d, sort_keys=True).encode()
        ).hexdigest()

    return {
        'api_version'          : api_version,
        'model_weights_hash'   : sha256_file(model_weights_path),
        'config_hash'          : sha256_dict(config_dict),
        'normative_ref_version': normative_version,
        'generated_at'         : datetime.datetime.now().isoformat(),
    }


def compare_version_stamps(stamp_a: dict, stamp_b: dict) -> dict:
    """Compare version stamps from two serial reports.

    Called automatically when a serial report comparison is requested
    (e.g. longitudinal monitoring in Chapter 18). Returns a clinical flag
    and a human-readable message for the Layer 3 Specialist Report header.

    Clinical flags:
      VERSION_IDENTICAL      – safe for direct serial comparison
      VERSION_MINOR_CHANGE   – comparison valid with caution
      VERSION_MAJOR_CHANGE   – serial comparison must be interpreted carefully;
                               normative reference or model may have changed
      VERSION_CONFIG_CHANGE  – processing configuration differs; specialist review

    Parameters
    ----------
    stamp_a, stamp_b : dict – outputs of generate_version_stamp()

    Returns
    -------
    dict with keys: flag, changed_fields, message
    """
    fields  = ['api_version', 'model_weights_hash',
               'config_hash', 'normative_ref_version']
    changes = {f: (stamp_a.get(f), stamp_b.get(f))
               for f in fields if stamp_a.get(f) != stamp_b.get(f)}

    if not changes:
        return {
            'flag'          : 'VERSION_IDENTICAL',
            'changed_fields': {},
            'message'       : ('Both reports generated by identical pipeline. '
                               'Serial comparison is valid.'),
        }

    if 'api_version' in changes:
        v_a, v_b     = changes['api_version']
        major_change = v_a.split('.')[0] != v_b.split('.')[0]
        flag    = 'VERSION_MAJOR_CHANGE' if major_change else 'VERSION_MINOR_CHANGE'
        prefix  = ('MAJOR version change: normative reference or model '
                   if major_change else 'Minor version change: ')
        message = (
            f'CAUTION: Reports generated by different API versions '
            f'({v_a} vs {v_b}). {prefix}'
            f'may have changed. Serial comparison should be interpreted '
            f'with caution. See Model Card §17.3 for details.')
    else:
        flag    = 'VERSION_CONFIG_CHANGE'
        message = ('Processing configuration changed between reports. '
                   'Serial comparison should be reviewed by a specialist.')

    return {'flag': flag, 'changed_fields': changes, 'message': message}


# ══════════════════════════════════════════════════════════════════════════════
# 2. Shewhart rolling AUC control chart
# ══════════════════════════════════════════════════════════════════════════════

def shewhart_auc_monitor(auc_series:    pd.Series,
                          baseline_days: int   = BASELINE_DAYS,
                          sigma_warning: float = SIGMA_WARNING,
                          sigma_alarm:   float = SIGMA_ALARM,
                          output_dir:    str   = 'outputs/drift') -> dict:
    """Shewhart control chart for rolling AUC drift detection (§17.4.1).

    Baseline statistics (mean and SD) are estimated from the first
    baseline_days time points. Each subsequent AUC value is classified as:
      IN_CONTROL    – within baseline_mean ± sigma_warning × sigma
      WARNING       – beyond ±2σ but within ±3σ
      OUT_OF_CONTROL – beyond ±3σ

    Overall status: OUT_OF_CONTROL if any alarm; WARNING if ≥3 warnings;
    IN_CONTROL otherwise.

    Parameters
    ----------
    auc_series : pd.Series
        Index = date or deployment month, values = rolling macro-AUC.
    baseline_days : int
        Number of initial time points used to estimate baseline statistics.
    sigma_warning, sigma_alarm : float
        Warning and alarm sigma multipliers (default 2.0 and 3.0).
    output_dir : str

    Returns
    -------
    dict with keys: status, baseline_mu, baseline_sigma,
                    lcl_warn, ucl_warn, lcl_alarm, ucl_alarm, flags,
                    n_warnings, n_alarms
    """
    os.makedirs(output_dir, exist_ok=True)

    baseline  = auc_series.iloc[:baseline_days]
    mu        = float(baseline.mean())
    sigma     = float(baseline.std(ddof=1))

    lcl_warn  = mu - sigma_warning * sigma
    ucl_warn  = mu + sigma_warning * sigma
    lcl_alarm = mu - sigma_alarm   * sigma
    ucl_alarm = mu + sigma_alarm   * sigma

    flags = []
    for val in auc_series:
        if val < lcl_alarm or val > ucl_alarm:
            flags.append('OUT_OF_CONTROL')
        elif val < lcl_warn or val > ucl_warn:
            flags.append('WARNING')
        else:
            flags.append('IN_CONTROL')

    # ── Plot ──────────────────────────────────────────────────────────────
    colour_map = {'IN_CONTROL'   : '#2E75B6',
                  'WARNING'      : '#FFC000',
                  'OUT_OF_CONTROL': '#C00000'}

    fig, ax = plt.subplots(figsize=(12, 5))

    # Background bands
    ax.axhspan(lcl_alarm, lcl_warn,  alpha=0.08, color='#FFC000')
    ax.axhspan(ucl_warn,  ucl_alarm, alpha=0.08, color='#FFC000')
    ax.axhspan(-1,        lcl_alarm, alpha=0.08, color='#C00000')
    ax.axhspan(ucl_alarm, 2,         alpha=0.08, color='#C00000')
    ax.axhspan(lcl_warn,  ucl_warn,  alpha=0.06, color='#2E7D32')

    ax.plot(auc_series.index, auc_series.values, 'o-',
            color='#2E75B6', linewidth=1.5, markersize=5,
            label='Rolling AUC', zorder=3)
    ax.axhline(mu, color='black', linewidth=1.5, linestyle='-',
               label=f'Baseline mean ({mu:.3f})')

    for lcl, ucl, lbl, col in [
        (lcl_warn,  ucl_warn,  f'2σ Warning ({sigma_warning:.0f}σ)',  '#FFC000'),
        (lcl_alarm, ucl_alarm, f'3σ Alarm ({sigma_alarm:.0f}σ)',      '#C00000'),
    ]:
        ax.axhline(lcl, color=col, linewidth=1.2, linestyle='--',
                   label=f'LCL {lbl}')
        ax.axhline(ucl, color=col, linewidth=1.2, linestyle='--',
                   label=f'UCL {lbl}')

    for x, y, flag in zip(auc_series.index, auc_series.values, flags):
        ax.scatter(x, y, color=colour_map[flag], zorder=5, s=60)

    ax.set_xlabel('Deployment month', fontsize=11)
    ax.set_ylabel('90-day rolling macro-AUC', fontsize=11)
    ax.set_title('Shewhart Rolling AUC Control Chart', fontsize=12,
                 fontweight='bold')
    ax.legend(fontsize=8, loc='lower left')
    ax.set_ylim(max(0, lcl_alarm - 3 * sigma), min(1, ucl_alarm + 3 * sigma))
    plt.tight_layout()
    plot_path = os.path.join(output_dir, 'shewhart_auc.png')
    plt.savefig(plot_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f'Saved: {plot_path}')

    n_warning = flags.count('WARNING')
    n_alarm   = flags.count('OUT_OF_CONTROL')
    status    = ('OUT_OF_CONTROL' if n_alarm > 0
                 else 'WARNING' if n_warning > 2
                 else 'IN_CONTROL')
    print(f'Shewhart monitor: {status}  '
          f'(warnings={n_warning}, alarms={n_alarm})')

    return {
        'status'         : status,
        'baseline_mu'    : round(mu,        4),
        'baseline_sigma' : round(sigma,     4),
        'lcl_warn'       : round(lcl_warn,  4),
        'ucl_warn'       : round(ucl_warn,  4),
        'lcl_alarm'      : round(lcl_alarm, 4),
        'ucl_alarm'      : round(ucl_alarm, 4),
        'flags'          : flags,
        'n_warnings'     : n_warning,
        'n_alarms'       : n_alarm,
    }


# ══════════════════════════════════════════════════════════════════════════════
# 3. Page-Hinkley test for gradual drift
# ══════════════════════════════════════════════════════════════════════════════

def page_hinkley_drift_test(auc_series:    pd.Series,
                             baseline_days: int   = BASELINE_DAYS,
                             delta:         float = PH_DELTA,
                             lam:           float = PH_LAMBDA) -> dict:
    """Page-Hinkley test for gradual monotonic AUC drift (§17.4.2).

    Detects sustained downward trends too slow for Shewhart rules.
    Accumulates deviations of each AUC value from the baseline mean.
    An alarm is triggered when M_t − PH_t > lambda, where M_t is the
    running maximum of the cumulative sum.

    Parameters
    ----------
    auc_series : pd.Series
        Index = date or deployment month, values = rolling macro-AUC.
    baseline_days : int
        Initial points used to estimate baseline mean.
    delta : float
        Tolerated mean shift before detection in AUC units (default 0.01).
    lam : float
        Alarm threshold (default 50, calibrated to 90-day baseline).

    Returns
    -------
    dict with keys: alarm_triggered, alarm_index, alarm_date, ph_values,
                    m_values, delta, lambda_threshold
    """
    mu = float(auc_series.iloc[:baseline_days].mean())

    ph_vals = []
    ph      = 0.0
    m_max   = 0.0
    alarm_idx  = None
    alarm_date = None

    for i, (date, val) in enumerate(auc_series.items()):
        m_t = float(val) - mu - delta
        ph  = ph + m_t
        m_max = max(m_max, ph)
        ph_vals.append(ph)

        if m_max - ph > lam and alarm_idx is None:
            alarm_idx  = i
            alarm_date = date
            print(f'Page-Hinkley ALARM at index {i} (date={date}): '
                  f'M_t - PH_t = {m_max - ph:.2f} > lambda={lam}')

    triggered = alarm_idx is not None
    if not triggered:
        print(f'Page-Hinkley: no alarm triggered (max M_t-PH_t < {lam})')

    return {
        'alarm_triggered'  : triggered,
        'alarm_index'      : alarm_idx,
        'alarm_date'       : str(alarm_date) if alarm_date else None,
        'ph_values'        : ph_vals,
        'delta'            : delta,
        'lambda_threshold' : lam,
    }


# ══════════════════════════════════════════════════════════════════════════════
# 4. Google Model Card 2.0 JSON generator
# ══════════════════════════════════════════════════════════════════════════════

def build_model_card_json(validation_report: dict,
                           api_version:       str = '1.0.0',
                           normative_version: str = 'Robson2025_v1',
                           output_path:       str = 'docs/model_card_v1.0.0.json'
                           ) -> dict:
    """Generate machine-readable Google Model Card 2.0 JSON (§17.5).

    Populated from the Chapter 16 validation_report.json. The JSON and the
    Word Model Card must contain identical performance figures — any discrepancy
    is a TRIPOD-AI compliance failure.

    ⚠️  Performance figures from Albasu et al. (2024) are reference estimates
    only. All values marked '[computed]' must be replaced with project-specific
    validated figures (Chapter 16) before regulatory submission.

    Parameters
    ----------
    validation_report : dict – output of build_validation_report() (Chapter 16)
    api_version : str – semantic version string
    normative_version : str – normative dataset version identifier
    output_path : str – output JSON path

    Returns
    -------
    dict – full Model Card structure (also saved as JSON)
    """
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path)
                else '.', exist_ok=True)

    mc = {
        'schema_version' : 'google_model_card_2.0',
        'generated_at'   : datetime.datetime.now().isoformat(),
        'model_details'  : {
            'name'      : 'ERG Analysis API',
            'version'   : api_version,
            'type'      : 'Two-stage ViT Small classifier, full-field ERG',
            'input'     : ('STFT spectrogram 224×224 px (Hamming, nperseg=64) '
                           '+ 28 engineered features (Chapter 9)'),
            'output'    : ('Traffic Light (GREEN/AMBER/RED) + probability vector '
                           '(Stage 1: Normal/Abnormal; Stage 2: six disease classes)'
                           ' + SHAP attribution (Chapter 14)'),
            'reference' : 'Albasu et al. (2024); McCulloch et al. (2023)',
            'repository': 'github.com/AI-Fairness-com/ERG-Analysis-API',
        },
        'intended_use'   : {
            'primary_use'  : ('Clinical decision support for adult full-field '
                              'ERG triage in line with ISCEV 2022 standards'),
            'target_users' : ['Retinal electrophysiologist',
                              'Specialist ophthalmologist',
                              'Optometrist (extended scope)'],
            'age_range'    : '18–80 years',
            'out_of_scope' : [
                'Paediatric patients (< 18 years)',
                'Pattern ERG',
                'Multifocal ERG',
                'EOG',
                'Autonomous diagnosis (mandatory clinician review)',
                'Non-ISCEV-compliant recordings',
                'Serial comparison across MAJOR version boundaries without flagging',
                'Disease classes outside the six trained categories',
            ],
        },
        'metrics'        : {
            'primary'               : 'Macro-AUC-ROC, Stage 2, external validation',
            'stage1_auc_threshold'  : 0.90,
            'stage2_auc_threshold'  : 0.80,
            'sensitivity_threshold' : 0.75,
            'brier_threshold'       : 0.25,
            'albasu_reference_auc'  : ALBASU_STAGE2_AUC,
            'note'                  : ('Albasu et al. 2024 figures are reference '
                                       'estimates. Replace with project-specific '
                                       'figures before regulatory submission.'),
        },
        'quantitative_analyses': validation_report.get('stage2_multiclass', {}),
        'normative_reference'  : normative_version,
        'tripod_ai_compliance' : 'docs/tripod_ai_compliance.csv',
        'ethical_considerations': {
            'fairness_subgroups'         : ['age_stratum', 'sex', 'device_type'],
            'explainability'             : ('3-level SHAP (Chapter 14): '
                                            'feature-level, spectrogram saliency, '
                                            'plain-language narrative'),
            'calibration_guard'          : ('Platt scaling + Brier Score ≥ 0.25 '
                                            'probability suppression'),
            'automation_bias_mitigation' : ('Mandatory clinician review for all '
                                            'non-GREEN results'),
            'ai_fairness_registration'   : 'Charity Commission reference 5278177',
        },
        'version_history'      : [],   # populated by release pipeline
        'revalidation_schedule': (f'{REVALIDATION_MONTHS}-month mandatory; '
                                  'drift-triggered as needed'),
        'drift_detection'      : {
            'method'        : ('Shewhart rolling AUC (3σ limits) + '
                               'Page-Hinkley test'),
            'window_days'   : BASELINE_DAYS,
            'alarm_delta'   : PH_DELTA,
            'alarm_lambda'  : PH_LAMBDA,
            'sigma_warning' : SIGMA_WARNING,
            'sigma_alarm'   : SIGMA_ALARM,
        },
    }

    with open(output_path, 'w') as f:
        json.dump(mc, f, indent=2)
    print(f'Model Card JSON saved: {output_path}')
    return mc


# ══════════════════════════════════════════════════════════════════════════════
# Smoke test
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    import tempfile

    rng = np.random.default_rng(42)
    os.makedirs('outputs/drift', exist_ok=True)
    os.makedirs('docs',          exist_ok=True)

    # ── 1. Version stamp ──────────────────────────────────────────────────
    print('=== Version stamp ===')
    dummy_weights = tempfile.NamedTemporaryFile(suffix='.pt', delete=False)
    dummy_weights.write(b'\x00' * 1024)
    dummy_weights.close()

    cfg_v1 = {'stft_window': 'hamming', 'nperseg': 64,
              'noverlap': 56, 'fs': 2000.0}
    cfg_v2 = {'stft_window': 'hamming', 'nperseg': 64,
              'noverlap': 56, 'fs': 2000.0, 'norm': 'db_zscore'}

    stamp_1_0 = generate_version_stamp('1.0.0', dummy_weights.name,
                                        cfg_v1, 'Robson2025_v1')
    stamp_1_1 = generate_version_stamp('1.1.0', dummy_weights.name,
                                        cfg_v2, 'Robson2025_v1')
    stamp_2_0 = generate_version_stamp('2.0.0', dummy_weights.name,
                                        cfg_v1, 'Robson2025_v2')

    for label, a, b in [
        ('v1.0 vs v1.0 (identical)', stamp_1_0, stamp_1_0),
        ('v1.0 vs v1.1 (minor)',     stamp_1_0, stamp_1_1),
        ('v1.0 vs v2.0 (major)',     stamp_1_0, stamp_2_0),
    ]:
        cmp = compare_version_stamps(a, b)
        print(f'  {label}: {cmp["flag"]}')
    print()

    # ── 2. Synthetic 18-month AUC series (Figure 17.2 scenario) ──────────
    print('=== Shewhart control chart ===')
    months      = pd.date_range('2024-01', periods=18, freq='ME')
    auc_stable  = rng.normal(0.883, 0.012, 9)
    auc_drift   = np.array([0.848, 0.843, 0.839, 0.849, 0.869,
                             0.881, 0.884, 0.887, 0.882])
    auc_vals    = np.concatenate([auc_stable, auc_drift])
    auc_series  = pd.Series(auc_vals, index=months)

    shew = shewhart_auc_monitor(
        auc_series, baseline_days=9,
        output_dir='outputs/drift')
    print(f'  Baseline mu : {shew["baseline_mu"]}')
    print(f'  LCL/UCL warn: {shew["lcl_warn"]} / {shew["ucl_warn"]}')
    print(f'  Status      : {shew["status"]}\n')

    # ── 3. Page-Hinkley test ──────────────────────────────────────────────
    print('=== Page-Hinkley test ===')
    ph = page_hinkley_drift_test(
        auc_series, baseline_days=9,
        delta=PH_DELTA, lam=PH_LAMBDA)
    print(f'  Alarm triggered: {ph["alarm_triggered"]}\n')

    # ── 4. Model Card ─────────────────────────────────────────────────────
    print('=== Model Card JSON ===')
    dummy_report = {
        'stage2_multiclass': {
            'macro_auc_external'   : 0.888,
            'macro_auc_albasu_ref' : 0.888,
            'calibration_method'   : 'Platt scaling',
        }
    }
    mc = build_model_card_json(
        dummy_report,
        api_version='1.0.0',
        normative_version='Robson2025_v1',
        output_path='docs/model_card_v1.0.0.json',
    )
    print(f'  Schema         : {mc["schema_version"]}')
    print(f'  Out-of-scope   : {len(mc["intended_use"]["out_of_scope"])} items')
    print(f'  Drift method   : {mc["drift_detection"]["method"]}')
    print()

    # ── 5. Summary figure: version stamps + drift flags timeline ─────────
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Left: Shewhart chart (already saved separately; recreate inline)
    ax = axes[0]
    mu_s, sig_s = shew['baseline_mu'], shew['baseline_sigma']
    flag_cols   = {'IN_CONTROL'   : '#2E75B6',
                   'WARNING'      : '#FFC000',
                   'OUT_OF_CONTROL': '#C00000'}
    ax.axhspan(shew['lcl_alarm'], shew['lcl_warn'],  alpha=0.10, color='#FFC000')
    ax.axhspan(shew['ucl_warn'],  shew['ucl_alarm'], alpha=0.10, color='#FFC000')
    ax.axhspan(0, shew['lcl_alarm'], alpha=0.10, color='#C00000')
    ax.axhspan(shew['lcl_warn'],  shew['ucl_warn'], alpha=0.07, color='#2E7D32')
    ax.plot(range(18), auc_vals, 'o-', color='#2E75B6', lw=1.5, ms=5, zorder=3)
    ax.axhline(mu_s, color='black', lw=1.5, ls='-',
               label=f'Baseline μ={mu_s:.3f}')
    ax.axhline(shew['lcl_warn'],  color='#FFC000', lw=1.2, ls='--')
    ax.axhline(shew['ucl_warn'],  color='#FFC000', lw=1.2, ls='--',
               label='±2σ warning')
    ax.axhline(shew['lcl_alarm'], color='#C00000', lw=1.2, ls='--')
    ax.axhline(shew['ucl_alarm'], color='#C00000', lw=1.2, ls='--',
               label='±3σ alarm')
    for i, (y, flag) in enumerate(zip(auc_vals, shew['flags'])):
        ax.scatter(i, y, color=flag_cols[flag], zorder=5, s=60)
    ax.set_xlabel('Deployment month', fontsize=10)
    ax.set_ylabel('Rolling macro-AUC', fontsize=10)
    ax.set_title('Shewhart Control Chart\n(Figure 17.2 scenario)',
                 fontsize=11, fontweight='bold')
    ax.legend(fontsize=8)
    ax.set_ylim(shew['lcl_alarm'] - 0.02, shew['ucl_alarm'] + 0.02)
    ax.grid(True, alpha=0.2)

    # Right: Page-Hinkley cumulative statistic
    ax2 = axes[1]
    ph_vals = ph['ph_values']
    m_vals  = np.maximum.accumulate(ph_vals)
    ax2.plot(range(18), ph_vals, color='#2E75B6', lw=1.5, label='PH_t')
    ax2.plot(range(18), m_vals,  color='#C62828', lw=1.0,
             ls='--', label='M_t (running max)')
    ax2.fill_between(range(18),
                     np.array(m_vals) - PH_LAMBDA,
                     np.array(ph_vals),
                     where=np.array(m_vals) - np.array(ph_vals) > PH_LAMBDA,
                     alpha=0.25, color='#C62828', label='Alarm zone')
    ax2.axhline(0, color='gray', lw=0.7, ls=':')
    ax2.set_xlabel('Deployment month', fontsize=10)
    ax2.set_ylabel('Cumulative statistic', fontsize=10)
    ax2.set_title(f'Page-Hinkley Test\n'
                  f'(δ={PH_DELTA}, λ={PH_LAMBDA:.0f})',
                  fontsize=11, fontweight='bold')
    ax2.legend(fontsize=8)
    ax2.grid(True, alpha=0.2)

    fig.suptitle('Chapter 17 – Post-Deployment Drift Detection',
                 fontsize=12, fontweight='bold')
    plt.tight_layout()
    plt.savefig('ch17_fig1_drift_detection.png', dpi=150, bbox_inches='tight')
    print('Saved: ch17_fig1_drift_detection.png')
    plt.show()

    # Cleanup
    os.unlink(dummy_weights.name)