# -*- coding: utf-8 -*-
"""Chapter_11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VV5VaS6ULby1tXp7T7AOoR_HI5BNZEbs
"""

# -*- coding: utf-8 -*-
"""
chapter_11_erg_missing_data.py
================================
Hands-On Electroretinography in the Age of AI
Chapter 11 – Missing Data Handling

Implements the missing data pipeline for ERG feature matrices:

  ENCODING
    add_missing_indicators            – NaN → sentinel + binary indicator columns
    exclude_high_missingness_features – Drop columns exceeding missingness threshold

  PROTOCOL COMPLETENESS
    compute_protocol_completeness     – Completeness factor + Layer 1 flag

  IMPUTATION (training pipeline only)
    mice_impute                       – MICE multiple imputation (fit on train only)
    pool_predictions                  – Rubin's rules probability pooling

  VALIDATION
    sensitivity_analysis_missing_data – Complete-case vs imputed AUC comparison
                                        (TRIPOD-AI Item 10b)

Missing data mechanisms and treatment (§11.1–11.2):
  MNAR-physiological  → sentinel value (−9999 for amplitudes) + binary indicator
  MAR / MCAR          → binary indicator + MICE in training; complete-case in deployment
  Protocol-NA         → NaN, feature excluded for non-applicable protocols

CRITICAL deployment rule:
  MICE imputation is used ONLY in model training (Chapters 12–13).
  The production API uses complete-case analysis with transparent missing-data
  communication in the clinical report (Chapter 19).

Repository : https://github.com/AI-Fairness-com/ERG-Analysis-API
Author     : Hamid
Licence    : See repo root LICENSE
"""

# ── Dependencies ───────────────────────────────────────────────────────────────
# Run once in your Colab session:
#   !pip install scikit-learn pandas -q

import numpy as np
import pandas as pd
from typing import Union
from sklearn.experimental import enable_iterative_imputer   # noqa: F401
from sklearn.impute import IterativeImputer
from sklearn.linear_model import BayesianRidge
from sklearn.metrics import roc_auc_score

# ── Locked constants ───────────────────────────────────────────────────────────
ISCEV_PROTOCOLS       = ['DA 0.01', 'DA 3', 'DA 10', 'LA 3', 'LA 30 Hz']
MISSINGNESS_THRESHOLD = 0.40    # global and per-class exclusion threshold
SENTINEL_AMP          = -9999.0 # sentinel for MNAR-physiological amplitude absence
TRIPOD_AUC_THRESHOLD  = 0.05    # max permitted AUC difference (TRIPOD-AI Item 10b)

# ── Imputation strategy reference (§11.2 Table) ───────────────────────────────
# Used as documentation and by the smoke-test helper; not called at runtime.
IMPUTATION_STRATEGY = {
    'a_amp_uv_MNAR_physiological' : 'sentinel(-9999) + indicator',
    'a_amp_uv_MAR_technical'      : 'MICE or mean + indicator',
    'b_amp_uv_MNAR_physiological' : 'sentinel(-9999) + indicator',
    'op_amp_MNAR_physiological'   : 'zero + indicator op_absent_physiological',
    'op_amp_MAR_hardware'         : 'NaN + indicator hardware_bw_insufficient',
    'op2_implicit_ms'             : 'mean + indicator (zero implausible for timing)',
    'phnr_amp_uv_MNAR'            : 'sentinel(-9999) + indicator',
    'phnr_amp_uv_protocol_NA'     : 'NaN, excluded for DA protocols',
    'implicit_times_MAR_technical': 'MICE using correlated timing features',
}


# ══════════════════════════════════════════════════════════════════════════════
# 1. NaN indicator encoding
# ══════════════════════════════════════════════════════════════════════════════

def add_missing_indicators(df:         pd.DataFrame,
                            features:   list,
                            fill_value: Union[float, str] = 0.0) -> pd.DataFrame:
    """Add binary indicator columns for NaN values then fill NaNs.

    For each feature in the list:
      1. Creates a new column ``{feature}_missing`` (1 = was NaN, 0 = observed).
      2. Fills the NaN in the original column with fill_value.

    Parameters
    ----------
    df : pd.DataFrame
        Feature DataFrame (will not be modified in-place).
    features : list of str
        Column names to process.
    fill_value : float or 'mean'
        Replacement value for NaN entries.
        • 0.0  – use for MNAR-physiological amplitudes (zero = absent response).
        • 'mean' – use for MAR timing features (column training mean).

    Returns
    -------
    pd.DataFrame with original columns filled and new ``*_missing`` columns added.

    Notes
    -----
    apply ONLY to the training set first, then apply the same fill_value
    (including any computed mean) to val/test to avoid leakage.
    """
    df = df.copy()
    for feat in features:
        if feat not in df.columns:
            continue
        df[f'{feat}_missing'] = df[feat].isna().astype(int)
        fill = df[feat].mean(skipna=True) if fill_value == 'mean' else fill_value
        df[feat] = df[feat].fillna(fill)
    return df


# ══════════════════════════════════════════════════════════════════════════════
# 2. Feature exclusion by missingness threshold
# ══════════════════════════════════════════════════════════════════════════════

def exclude_high_missingness_features(df_train:         pd.DataFrame,
                                       df_val:           pd.DataFrame,
                                       df_test:          pd.DataFrame,
                                       label_col:        str   = 'label',
                                       threshold_global: float = MISSINGNESS_THRESHOLD,
                                       threshold_class:  float = MISSINGNESS_THRESHOLD
                                       ) -> tuple:
    """Remove features with excessive missingness from all three partitions.

    Thresholds are computed on the training set only to prevent leakage.
    Both a global threshold (across all classes) and a per-class threshold
    are applied; a feature is excluded if it fails either check.

    Corresponding ``*_missing`` indicator columns are also removed when their
    parent feature is excluded.

    Parameters
    ----------
    df_train, df_val, df_test : pd.DataFrame
        Feature DataFrames from patient_level_split() (Chapter 10).
    label_col : str
        Name of the integer class label column.
    threshold_global : float
        Maximum permitted fraction of NaN values globally (default 0.40).
    threshold_class : float
        Maximum permitted fraction of NaN values within any single class
        (default 0.40).

    Returns
    -------
    tuple (df_train, df_val, df_test, excluded_features_list)
    """
    feature_cols = [c for c in df_train.columns
                    if c != label_col and '_missing' not in c]
    to_exclude   = set()

    # Global check
    global_miss     = df_train[feature_cols].isna().mean()
    global_excluded = global_miss[global_miss > threshold_global].index.tolist()
    to_exclude.update(global_excluded)
    if global_excluded:
        print(f'Globally excluded ({threshold_global:.0%} threshold): '
              f'{global_excluded}')

    # Per-class check
    for cls in df_train[label_col].unique():
        sub      = df_train[df_train[label_col] == cls][feature_cols]
        cls_miss = sub.isna().mean()
        cls_excl = cls_miss[cls_miss > threshold_class].index.tolist()
        if cls_excl:
            print(f'  Class {cls}: per-class excluded {cls_excl}')
            to_exclude.update(cls_excl)

    # Drop corresponding indicator columns too
    indicator_cols = [f'{f}_missing' for f in to_exclude
                      if f'{f}_missing' in df_train.columns]
    to_exclude.update(indicator_cols)
    drop_cols = list(to_exclude)

    df_train = df_train.drop(columns=drop_cols, errors='ignore')
    df_val   = df_val.drop(  columns=drop_cols, errors='ignore')
    df_test  = df_test.drop( columns=drop_cols, errors='ignore')

    print(f'Total features excluded: {len(drop_cols)}')
    return df_train, df_val, df_test, drop_cols


# ══════════════════════════════════════════════════════════════════════════════
# 3. Protocol completeness factor
# ══════════════════════════════════════════════════════════════════════════════

def compute_protocol_completeness(present_protocols: list,
                                   passed_qc:         list) -> dict:
    """Compute the protocol completeness factor and Layer 1 flag.

    The completeness factor multiplies the classifier confidence score in the
    Layer 1 Traffic Light report. A PARTIAL flag triggers a dashed badge
    border and mandatory caveat text in the Layer 2 summary.

    Parameters
    ----------
    present_protocols : list of str
        Protocol names present in the recording (subset of ISCEV_PROTOCOLS).
    passed_qc : list of str
        Protocols that passed quality grading (subset of present_protocols).

    Returns
    -------
    dict with keys:
      completeness_factor   – float in [0, 1]
      n_protocols_passed    – int
      n_protocols_total     – int (always 5)
      layer1_flag           – 'COMPLETE' / 'PARTIAL' / 'SEVERELY_INCOMPLETE'
      missing_protocols     – list of missing protocol names

    Flag thresholds:
      COMPLETE            factor == 1.0  (all 5 protocols present and passed QC)
      PARTIAL             0.6 ≤ factor < 1.0  (3–4 protocols)
      SEVERELY_INCOMPLETE factor < 0.6   (≤ 2 protocols)
    """
    n_total   = len(ISCEV_PROTOCOLS)
    n_passed  = sum(p in passed_qc for p in ISCEV_PROTOCOLS)
    factor    = n_passed / n_total
    missing   = [p for p in ISCEV_PROTOCOLS if p not in present_protocols]

    if factor == 1.0:
        flag = 'COMPLETE'
    elif factor >= 0.6:
        flag = 'PARTIAL'
    else:
        flag = 'SEVERELY_INCOMPLETE'

    return {
        'completeness_factor': round(factor, 2),
        'n_protocols_passed' : n_passed,
        'n_protocols_total'  : n_total,
        'layer1_flag'        : flag,
        'missing_protocols'  : missing,
    }


# ══════════════════════════════════════════════════════════════════════════════
# 4. MICE multiple imputation  ⚠️  training pipeline only
# ══════════════════════════════════════════════════════════════════════════════

def mice_impute(X_train:       np.ndarray,
                X_val:         np.ndarray,
                X_test:        np.ndarray,
                n_imputations: int = 5,
                max_iter:      int = 10,
                random_state:  int = 42) -> list:
    """Apply MICE multiple imputation to train/val/test partitions.

    ⚠️  TRAINING PIPELINE ONLY.
    Do NOT use in the production API deployment path. See §11.4.2 and
    the module docstring for the rationale.

    The imputer is FIT on X_train only, then APPLIED (transform) to all three
    partitions. Fitting on val or test data would constitute data leakage.

    Uses BayesianRidge as the imputation estimator (scikit-learn default for
    IterativeImputer), which is robust to collinearity between ERG features.

    Parameters
    ----------
    X_train, X_val, X_test : np.ndarray
        Feature matrices from patient_level_split() with NaN for missing values.
    n_imputations : int
        Number of independent imputed datasets to generate (default 5).
        Increase to 10–20 for publication-quality uncertainty estimates.
    max_iter : int
        Maximum MICE rounds per imputation (default 10).
    random_state : int
        Base seed; each imputation uses random_state + i for reproducibility.

    Returns
    -------
    list of n_imputations tuples: [(X_train_imp, X_val_imp, X_test_imp), ...]
    Pool the classifier predictions across imputations with pool_predictions().
    """
    imputed_sets = []
    for seed in range(random_state, random_state + n_imputations):
        imp = IterativeImputer(
            estimator        = BayesianRidge(),
            max_iter         = max_iter,
            random_state     = seed,
            initial_strategy = 'mean',
            imputation_order = 'ascending',   # most-complete features first
        )
        imp.fit(X_train)   # FIT on training data only
        imputed_sets.append((
            imp.transform(X_train),
            imp.transform(X_val),
            imp.transform(X_test),
        ))
    print(f'MICE complete: {n_imputations} imputed datasets generated.')
    return imputed_sets


def pool_predictions(proba_list: list) -> np.ndarray:
    """Average predicted probabilities across imputed datasets (Rubin's rules).

    Parameters
    ----------
    proba_list : list of np.ndarray
        Each array has shape (n_samples, n_classes) — one per imputed dataset.

    Returns
    -------
    np.ndarray, shape (n_samples, n_classes)
        Mean probability across imputations.
    """
    return np.mean(np.stack(proba_list, axis=0), axis=0)


# ══════════════════════════════════════════════════════════════════════════════
# 5. Sensitivity analysis (TRIPOD-AI Item 10b)
# ══════════════════════════════════════════════════════════════════════════════

def sensitivity_analysis_missing_data(df_test:       pd.DataFrame,
                                       y_pred_proba:  np.ndarray,
                                       label_col:     str   = 'label',
                                       auc_threshold: float = TRIPOD_AUC_THRESHOLD
                                       ) -> dict:
    """Compare classifier AUC on complete-case vs full imputed test subset.

    Required by TRIPOD-AI Item 10b when any imputation is performed.
    A difference > auc_threshold triggers an 'INVESTIGATE' flag that must
    be documented in the Model Card (Chapter 17) as an imputation sensitivity
    finding.

    Parameters
    ----------
    df_test : pd.DataFrame
        Test-partition DataFrame with ``*_missing`` indicator columns present.
    y_pred_proba : np.ndarray, shape (n_test, n_classes)
        Pooled predicted probabilities (output of pool_predictions()).
    label_col : str
        Integer class label column name.
    auc_threshold : float
        Maximum acceptable |AUC_all − AUC_complete_case| (default 0.05).

    Returns
    -------
    dict with keys: auc_all_subjects, auc_complete_case, absolute_difference,
                    n_complete_case, n_total, tripod_ai_flag ('PASS'/'INVESTIGATE').
    """
    indicator_cols = [c for c in df_test.columns if c.endswith('_missing')]
    complete_mask  = (
        (df_test[indicator_cols] == 0).all(axis=1)
        if indicator_cols
        else pd.Series([True] * len(df_test), index=df_test.index)
    )

    y_true     = df_test[label_col].values
    y_true_cc  = y_true[complete_mask]
    y_proba_cc = y_pred_proba[complete_mask]

    all_cls = np.arange(y_pred_proba.shape[1])
    auc_all = roc_auc_score(y_true,    y_pred_proba,
                            multi_class='ovr', average='macro',
                            labels=all_cls)
    # Complete-case AUC requires all classes to be present
    cc_classes = np.unique(y_true_cc)
    if len(cc_classes) < y_pred_proba.shape[1]:
        auc_cc = float('nan')
        diff   = float('nan')
        print(f'  Note: complete-case subset contains only '
              f'{len(cc_classes)}/{ y_pred_proba.shape[1]} classes '
              f'-- CC AUC undefined; increase dataset size for reliable estimate.')
    else:
        auc_cc = roc_auc_score(y_true_cc, y_proba_cc,
                               multi_class='ovr', average='macro',
                               labels=all_cls)
        diff   = abs(auc_all - auc_cc)

    flag   = 'INVESTIGATE' if diff > auc_threshold else 'PASS'
    result = {
        'auc_all_subjects'   : round(auc_all, 4),
        'auc_complete_case'  : round(auc_cc,  4),
        'absolute_difference': round(diff,    4),
        'n_complete_case'    : int(complete_mask.sum()),
        'n_total'            : len(y_true),
        'tripod_ai_flag'     : flag,
    }
    print(f'Sensitivity analysis (TRIPOD-AI §10b): '
          f'AUC all={auc_all:.4f}  CC={auc_cc:.4f}  '
          f'Δ={diff:.4f}  [{flag}]')
    return result


# ══════════════════════════════════════════════════════════════════════════════
# Smoke test
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    import matplotlib.pyplot as plt
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.preprocessing import LabelBinarizer

    rng = np.random.default_rng(42)

    # ── Synthetic feature DataFrame: 300 recordings, 7 classes ───────────
    N_REC   = 600
    N_FEAT  = 20
    N_CLASS = 7

    class_probs = [0.30, 0.20, 0.15, 0.12, 0.10, 0.08, 0.05]
    y_all       = rng.choice(N_CLASS, size=N_REC, p=class_probs)
    X_raw       = rng.normal(0, 1, (N_REC, N_FEAT)).astype(np.float32)
    for c in range(N_CLASS):
        X_raw[y_all == c, 0] += c * 1.2
        X_raw[y_all == c, 1] -= c * 0.6

    feat_names  = [f'feat_{i:02d}' for i in range(N_FEAT)]
    df_all      = pd.DataFrame(X_raw, columns=feat_names)
    df_all['label'] = y_all

    # Inject structured missingness
    # feat_00–02: MNAR-physiological (missing more in high-class)
    for i, col in enumerate(['feat_00', 'feat_01', 'feat_02']):
        mnar_mask = (y_all >= 4) & (rng.random(N_REC) < 0.55)
        df_all.loc[mnar_mask, col] = np.nan

    # feat_10–12: high missingness (>40%) → should be excluded
    for col in ['feat_10', 'feat_11', 'feat_12']:
        df_all.loc[rng.random(N_REC) < 0.50, col] = np.nan

    # feat_15–16: moderate MAR missingness
    for col in ['feat_15', 'feat_16']:
        df_all.loc[rng.random(N_REC) < 0.20, col] = np.nan

    # Simple 70/20/10 split (recording-level for smoke test)
    idx     = rng.permutation(N_REC)
    n_tr    = int(0.70 * N_REC)
    n_va    = int(0.20 * N_REC)
    df_tr   = df_all.iloc[idx[:n_tr]].reset_index(drop=True)
    df_va   = df_all.iloc[idx[n_tr: n_tr + n_va]].reset_index(drop=True)
    df_te   = df_all.iloc[idx[n_tr + n_va:]].reset_index(drop=True)

    # ── 1. Missingness heatmap ────────────────────────────────────────────
    miss_rate = df_tr[feat_names].isna().mean().sort_values(ascending=False)
    fig1, ax1 = plt.subplots(figsize=(12, 3))
    x_pos = list(range(len(miss_rate)))
    ax1.bar(x_pos, miss_rate.values,
            color=['#C62828' if v > MISSINGNESS_THRESHOLD
                   else '#2E75B6' for v in miss_rate.values])
    ax1.axhline(MISSINGNESS_THRESHOLD, color='red', ls='--', lw=1.2,
                label=f'Exclusion threshold ({MISSINGNESS_THRESHOLD:.0%})')
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(list(miss_rate.index), rotation=45, ha='right', fontsize=8)
    ax1.set_ylabel('Missingness fraction', fontsize=10)
    ax1.set_title('Feature Missingness in Training Set',
                  fontsize=12, fontweight='bold')
    ax1.legend(fontsize=9)
    ax1.grid(True, axis='y', alpha=0.3)
    plt.tight_layout()
    fig1.savefig('ch11_fig1_missingness.png', dpi=150, bbox_inches='tight')
    print('Saved: ch11_fig1_missingness.png\n')

    # ── 2. Add missing indicators ─────────────────────────────────────────
    print('=== NaN indicator encoding ===')
    amp_feats    = ['feat_00', 'feat_01', 'feat_02']
    timing_feats = ['feat_15', 'feat_16']

    df_tr = add_missing_indicators(df_tr, amp_feats,    fill_value=0.0)
    df_tr = add_missing_indicators(df_tr, timing_feats, fill_value='mean')
    df_va = add_missing_indicators(df_va, amp_feats,    fill_value=0.0)
    df_va = add_missing_indicators(df_va, timing_feats, fill_value='mean')
    df_te = add_missing_indicators(df_te, amp_feats,    fill_value=0.0)
    df_te = add_missing_indicators(df_te, timing_feats, fill_value='mean')
    print(f'Columns after indicator encoding: {df_tr.shape[1]}\n')

    # ── 3. Feature exclusion ──────────────────────────────────────────────
    print('=== Feature exclusion ===')
    df_tr, df_va, df_te, excluded = exclude_high_missingness_features(
        df_tr, df_va, df_te)
    print(f'Excluded: {excluded}\n')

    # ── 4. Protocol completeness ──────────────────────────────────────────
    print('=== Protocol completeness ===')
    for present, passed in [
        (ISCEV_PROTOCOLS, ISCEV_PROTOCOLS),
        (['DA 3', 'DA 10', 'LA 3'], ['DA 3', 'LA 3']),
        (['DA 3'], ['DA 3']),
    ]:
        pc = compute_protocol_completeness(present, passed)
        print(f'  present={len(present)}  passed={pc["n_protocols_passed"]}  '
              f'factor={pc["completeness_factor"]:.2f}  '
              f'flag={pc["layer1_flag"]}  '
              f'missing={pc["missing_protocols"]}')
    print()

    # ── 5. MICE imputation ────────────────────────────────────────────────
    print('=== MICE imputation ===')
    fc      = [c for c in df_tr.columns if c != 'label']
    X_tr_r  = df_tr[fc].values.astype(float)
    X_va_r  = df_va[fc].values.astype(float)
    X_te_r  = df_te[fc].values.astype(float)
    y_tr_r  = df_tr['label'].values
    y_va_r  = df_va['label'].values
    y_te_r  = df_te['label'].values

    imputed = mice_impute(X_tr_r, X_va_r, X_te_r,
                          n_imputations=3, max_iter=5)
    print(f'  Imputed datasets: {len(imputed)}\n')

    # ── 6. Train RF on each imputation, pool probabilities ────────────────
    print('=== Classifier + Rubin pooling ===')
    proba_list = []
    lb         = LabelBinarizer().fit(y_tr_r)
    for i, (X_tr_i, _, X_te_i) in enumerate(imputed):
        clf = RandomForestClassifier(n_estimators=50, max_depth=6,
                                      random_state=42 + i, n_jobs=-1)
        clf.fit(X_tr_i, y_tr_r)
        proba_list.append(clf.predict_proba(X_te_i))

    y_proba_pooled = pool_predictions(proba_list)
    all_cls_lb     = np.arange(N_CLASS)
    auc_pooled     = roc_auc_score(lb.transform(y_te_r), y_proba_pooled,
                                    multi_class='ovr', average='macro')
    print(f'  Pooled macro AUC on test set: {auc_pooled:.4f}\n')

    # ── 7. Sensitivity analysis (TRIPOD-AI Item 10b) ──────────────────────
    print('=== Sensitivity analysis (TRIPOD-AI §10b) ===')
    df_te_annot = df_te.copy()
    df_te_annot['label'] = y_te_r
    sa = sensitivity_analysis_missing_data(df_te_annot, y_proba_pooled)
    print(f'  n_complete_case = {sa["n_complete_case"]} / {sa["n_total"]}\n')

    # ── 8. Summary bar chart ──────────────────────────────────────────────
    fig2, axes = plt.subplots(1, 2, figsize=(12, 4))

    # Left: complete-case vs all-imputed AUC
    axes[0].bar(['All subjects\n(imputed)', 'Complete case only'],
                [sa['auc_all_subjects'], sa['auc_complete_case']],
                color=['#2E75B6', '#2E7D32'])
    axes[0].set_ylim(0, 1)
    axes[0].set_ylabel('Macro AUC-ROC', fontsize=10)
    axes[0].set_title(f'TRIPOD-AI Sensitivity Analysis\n'
                      f'Δ = {sa["absolute_difference"]:.4f}  '
                      f'[{sa["tripod_ai_flag"]}]',
                      fontsize=11, fontweight='bold')
    axes[0].grid(True, axis='y', alpha=0.3)

    # Right: missingness rate after exclusion
    remaining_feats = [c for c in df_tr.columns
                       if c != 'label' and '_missing' not in c]
    miss_after = df_tr[remaining_feats].isna().mean().sort_values(ascending=False)
    axes[1].bar(range(len(miss_after)), miss_after.values, color='#2E75B6')
    axes[1].axhline(MISSINGNESS_THRESHOLD, color='red', ls='--', lw=1.0)
    axes[1].set_xticks([])
    axes[1].set_ylabel('Missingness fraction', fontsize=10)
    axes[1].set_title(f'Missingness After Exclusion\n'
                      f'({len(remaining_feats)} features retained)',
                      fontsize=11, fontweight='bold')
    axes[1].grid(True, axis='y', alpha=0.3)

    fig2.suptitle('Chapter 11 – Missing Data Pipeline Summary',
                  fontsize=12, fontweight='bold')
    plt.tight_layout()
    fig2.savefig('ch11_fig2_missing_data_summary.png', dpi=150,
                 bbox_inches='tight')
    print('Saved: ch11_fig2_missing_data_summary.png')
    plt.show()