# -*- coding: utf-8 -*-
"""Chapter_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18rtbqA6jaN5xISIdsBzrOHqXsy7-2uqP
"""

# -*- coding: utf-8 -*-
"""
chapter_04_erg_visualisation.py
================================
Hands-On Electroretinography in the Age of AI
Chapter 4 – ERG Signal Visualisation and Quality Control

Provides five reusable functions:

  plot_erg_waveform        – Annotated ERG waveform (a/b-wave, OP panel,
                             normative reference band)
  plot_erg_spectrogram     – STFT spectrogram with pre-stimulus normalisation
  add_snr_overlay          – SNR noise-floor band and quality badge on any axis
  plot_baseline_drift      – Pre-stimulus baseline drift indicator
  build_interactive_waveform – Plotly interactive viewer (HTML export)
  plot_mferg_heatmap       – Topographic mfERG amplitude and quality maps

All functions accept the standardised ERG dict produced by the Chapter 3
loaders (keys: time_ms, amplitude_uv, fs_hz, electrode_type, patient_id).

Repository : https://github.com/AI-Fairness-com/ERG-Analysis-API
Author     : Hamid
Licence    : See repo root LICENSE
"""

# ── Dependencies ───────────────────────────────────────────────────────────────
# Run once in your Colab session before importing this module:
#   !pip install mne scipy plotly -q

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib.patches import RegularPolygon
from matplotlib.collections import PatchCollection
from numpy.lib.stride_tricks import sliding_window_view
from scipy.signal import butter, sosfiltfilt, stft
import plotly.graph_objects as go


# ══════════════════════════════════════════════════════════════════════════════
# 1. Annotated ERG waveform
# ══════════════════════════════════════════════════════════════════════════════

def plot_erg_waveform(recording: dict,
                     norms:     dict  = None,
                     protocol:  str   = 'DA 3.0',
                     show_ops:  bool  = True,
                     title:     str   = None) -> plt.Figure:
    """Produce a fully annotated ERG waveform figure (ISCEV 2022 conventions).

    Parameters
    ----------
    recording : dict
        Standardised ERG dict from any Chapter 3 loader.
        Required keys: time_ms, amplitude_uv, fs_hz.
    norms : dict, optional
        Normative reference dict with keys time_ms, p10, p90 (arrays).
    protocol : str
        ISCEV protocol label for the figure title.
    show_ops : bool
        When True, adds a second panel with the 75–300 Hz OP-filtered trace.
    title : str, optional
        Override the auto-generated figure title.

    Returns
    -------
    plt.Figure
    """
    t   = recording['time_ms']
    amp = recording['amplitude_uv']
    fs  = recording['fs_hz']
    elc = recording.get('electrode_type', 'unknown')

    # Stimulus onset sample (closest sample to t = 0 ms).
    s0 = int(np.argmin(np.abs(t)))

    # a-wave trough: first minimum in the 5–40 ms post-stimulus window.
    post_t   = t[s0:]
    post_amp = amp[s0:]
    a_win    = (post_t >= 5) & (post_t <= 40)
    if a_win.any():
        a_local = int(np.argmin(post_amp[a_win]))
        a_gi    = s0 + int(np.where(a_win)[0][0]) + a_local
    else:
        a_gi = s0 + int(np.argmin(post_amp[:60]))

    # b-wave peak: maximum after the a-wave trough.
    b_gi = a_gi + int(np.argmax(amp[a_gi:]))

    a_amp_uv  = amp[a_gi]               # baseline-to-trough (ISCEV)
    b_amp_uv  = amp[b_gi] - amp[a_gi]   # trough-to-peak (ISCEV)
    a_time_ms = t[a_gi]
    b_time_ms = t[b_gi]

    n = 2 if show_ops else 1
    fig, axes = plt.subplots(
        n, 1, figsize=(12, 4 * n), sharex=True,
        gridspec_kw={'height_ratios': [3, 1] if n == 2 else [1]})
    ax = axes[0] if n == 2 else axes

    # Normative reference band.
    if norms is not None:
        ax.fill_between(norms['time_ms'], norms['p10'], norms['p90'],
                        alpha=0.18, color='gray',
                        label='Normative range (10th–90th centile)')

    # Main waveform.
    ax.plot(t, amp, color='#2E75B6', linewidth=1.8,
            label=f'{protocol} ERG  |  {elc} electrode')
    ax.axhline(0, color='gray', linewidth=0.7, linestyle=':')
    ax.axvline(0, color='red',  linewidth=1.0, linestyle='--', alpha=0.7,
               label='Stimulus onset (t = 0 ms)')

    # a-wave: double-headed bracket from baseline to trough.
    ax.annotate('', xy=(a_time_ms, amp[a_gi]), xytext=(a_time_ms, 0),
                arrowprops=dict(arrowstyle='<->', color='#C62828', lw=1.4))
    ax.text(a_time_ms + 4, amp[a_gi] / 2,
            f'a: {abs(a_amp_uv):.0f} µV\n@ {a_time_ms:.0f} ms',
            fontsize=8.5, color='#C62828', va='center')

    # b-wave: bracket from a-wave trough to b-wave peak (ISCEV trough-to-peak).
    ax.annotate('', xy=(b_time_ms, amp[b_gi]), xytext=(b_time_ms, amp[a_gi]),
                arrowprops=dict(arrowstyle='<->', color='#1F4E79', lw=1.4))
    ax.text(b_time_ms + 4, (amp[b_gi] + amp[a_gi]) / 2,
            f'b: {b_amp_uv:.0f} µV\n@ {b_time_ms:.0f} ms',
            fontsize=8.5, color='#1F4E79', va='center')

    ax.set_ylabel('Amplitude (µV)', fontsize=11)
    ax.legend(loc='lower right', fontsize=9)
    ax.grid(True, alpha=0.25)

    # OP panel: 75–300 Hz bandpass isolates oscillatory potentials.
    if show_ops:
        sos = butter(4, [75, 300], btype='bandpass', fs=fs, output='sos')
        op  = sosfiltfilt(sos, amp)
        axes[1].plot(t, op, color='#2E7D32', linewidth=1.2,
                     label='Oscillatory potentials (75–300 Hz)')
        axes[1].axhline(0, color='gray', linewidth=0.7, linestyle=':')
        axes[1].set_ylabel('OP amplitude (µV)', fontsize=11)
        axes[1].legend(loc='lower right', fontsize=9)
        axes[1].grid(True, alpha=0.25)

    plt.xlabel('Time (ms)', fontsize=11)
    auto_title = (title if title else
                  f'{protocol}  |  {elc}  |  '
                  f'a = {abs(a_amp_uv):.0f} µV @ {a_time_ms:.0f} ms  |  '
                  f'b = {b_amp_uv:.0f} µV @ {b_time_ms:.0f} ms')
    fig.suptitle(auto_title, fontsize=12, fontweight='bold')
    plt.tight_layout()
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# 2. STFT spectrogram
# ══════════════════════════════════════════════════════════════════════════════

def plot_erg_spectrogram(recording: dict,
                         protocol:  str   = 'DA 3.0',
                         fmin_hz:   float = 0.0,
                         fmax_hz:   float = 300.0,
                         nperseg:   int   = 64,
                         noverlap:  int   = 56,
                         title:     str   = None) -> plt.Figure:
    """Compute and display an STFT spectrogram of an ERG recording.

    Parameters
    ----------
    recording : dict
        Standardised ERG dict (Chapter 3 format).
    protocol : str
        Protocol label for the figure title.
    fmin_hz, fmax_hz : float
        Frequency display range in Hz.
    nperseg : int
        STFT window length in samples.
    noverlap : int
        Number of overlapping samples between windows.
    title : str, optional
        Override the auto-generated figure title.

    Returns
    -------
    plt.Figure
    """
    t   = recording['time_ms']
    amp = recording['amplitude_uv']
    fs  = recording['fs_hz']

    # STFT with Hann window to minimise spectral leakage.
    freqs, t_stft, Zxx = stft(amp, fs=fs, nperseg=nperseg,
                               noverlap=noverlap, window='hann')

    # Align STFT time axis to stimulus onset at t = 0 ms.
    stim_idx = int(np.argmin(np.abs(t)))
    t_ms     = t_stft * 1000 - t[stim_idx]

    # Convert to dB and normalise relative to mean pre-stimulus energy.
    amp_db   = 20 * np.log10(np.abs(Zxx) + 1e-12)
    pre_cols = t_ms < 0
    if pre_cols.any():
        baseline = np.mean(amp_db[:, pre_cols], axis=1, keepdims=True)
        amp_db   = amp_db - baseline

    # Crop to requested frequency range.
    fmask    = (freqs >= fmin_hz) & (freqs <= fmax_hz)
    f_plot   = freqs[fmask]
    amp_plot = amp_db[fmask, :]

    fig, ax = plt.subplots(figsize=(12, 5))
    pcm = ax.pcolormesh(t_ms, f_plot, amp_plot,
                        shading='gouraud', cmap='inferno')

    # Key frequency band boundaries.
    for freq, colour, label in [
        (30,  'white', '30 Hz  (b-wave / OP boundary)'),
        (75,  'cyan',  '75 Hz  (OP lower limit)'),
        (300, 'cyan',  '300 Hz (OP upper limit)'),
    ]:
        if fmin_hz <= freq <= fmax_hz:
            ax.axhline(freq, color=colour, linewidth=0.8,
                       linestyle='--', alpha=0.65, label=label)

    ax.axvline(0, color='red', linewidth=1.2, linestyle='--',
               alpha=0.85, label='Stimulus onset')

    plt.colorbar(pcm, ax=ax, label='Amplitude (dB re pre-stimulus baseline)')
    ax.set_xlabel('Time (ms)', fontsize=11)
    ax.set_ylabel('Frequency (Hz)', fontsize=11)
    ax.legend(loc='upper right', fontsize=8, framealpha=0.6)
    fig.suptitle(
        title if title else
        f'STFT Spectrogram  |  {protocol}  |  fs = {int(fs)} Hz  |  '
        f'nperseg = {nperseg}  noverlap = {noverlap}',
        fontsize=12, fontweight='bold')
    plt.tight_layout()
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# 3. SNR overlay
# ══════════════════════════════════════════════════════════════════════════════

def add_snr_overlay(ax:           plt.Axes,
                    time_ms:      np.ndarray,
                    amplitude_uv: np.ndarray,
                    fs:           float,
                    electrode:    str   = 'dtl',
                    pre_ms:       float = 200.0) -> dict:
    """Add an SNR noise-floor band and quality badge to an existing waveform axis.

    Parameters
    ----------
    ax : plt.Axes
        Matplotlib axis on which to draw the overlay.
    time_ms : np.ndarray
        Time axis in milliseconds.
    amplitude_uv : np.ndarray
        Amplitude array in microvolts.
    fs : float
        Sampling rate in Hz.
    electrode : str
        Electrode type key for threshold lookup
        ('contact_lens', 'gold_foil', 'dtl', 'skin').
    pre_ms : float
        Pre-stimulus window length in milliseconds used to estimate noise RMS.

    Returns
    -------
    dict with keys: snr, snr_db, quality_flag, noise_rms_uv
    """
    pre_n = int(pre_ms * fs / 1000)
    noise = amplitude_uv[:pre_n]
    n_rms = float(np.sqrt(np.mean(noise ** 2)))

    # ±2 × RMS noise envelope.
    ax.fill_between(time_ms, -2 * n_rms, 2 * n_rms,
                    alpha=0.15, color='orange',
                    label=f'±2× noise RMS  ({n_rms:.1f} µV)')

    # SNR from the 250 ms post-stimulus signal window.
    sig     = amplitude_uv[pre_n: pre_n + int(0.25 * fs)]
    s_pk2pk = float(np.max(sig) - np.min(sig))
    snr     = s_pk2pk / n_rms if n_rms > 0 else 0.0
    snr_db  = 20 * np.log10(snr) if snr > 0 else -99.0

    # Electrode-specific PASS and WARNING thresholds (Chapter 2, Section 2.3).
    thresholds = {'contact_lens': 8, 'gold_foil': 6, 'dtl': 4, 'skin': 3}
    warn_thresholds = {'contact_lens': 4.0, 'gold_foil': 3.0, 'dtl': 2.5, 'skin': 1.5}
    key = electrode.lower().replace(' ', '_')
    pass_thr = thresholds.get(key, 4)
    warn_thr = warn_thresholds.get(key, 2.5)

    flag = 'PASS' if snr >= pass_thr else ('WARNING' if snr >= warn_thr else 'FAIL')
    col  = {'PASS': '#2E7D32', 'WARNING': '#F9A825', 'FAIL': '#C62828'}[flag]

    ax.text(0.02, 0.97,
            f'Quality: {flag}   SNR: {snr:.1f}  ({snr_db:.1f} dB)',
            transform=ax.transAxes, fontsize=9.5, va='top',
            color='white', fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.35', facecolor=col, alpha=0.92))

    return {'snr': snr, 'snr_db': snr_db,
            'quality_flag': flag, 'noise_rms_uv': n_rms}


# ══════════════════════════════════════════════════════════════════════════════
# 4. Baseline drift indicator
# ══════════════════════════════════════════════════════════════════════════════

def plot_baseline_drift(recording:          dict,
                        ax:                 plt.Axes = None,
                        drift_threshold_uv: float    = 10.0) -> dict:
    """Display a baseline drift indicator for the pre-stimulus window.

    Parameters
    ----------
    recording : dict
        Standardised ERG dict (Chapter 3 format).
    ax : plt.Axes, optional
        If provided, draws the drift trace onto this axis.
    drift_threshold_uv : float
        Drift amplitude (µV) above which drift is flagged.

    Returns
    -------
    dict with keys: drift_detected (bool), max_drift_uv (float)
    """
    t   = recording['time_ms']
    amp = recording['amplitude_uv']
    fs  = recording['fs_hz']

    pre_t   = t[t < 0]
    pre_amp = amp[t < 0]

    # 100 ms sliding mean to reveal slow drift trends.
    w = max(1, int(0.1 * fs))
    if len(pre_amp) >= w:
        wins       = sliding_window_view(pre_amp, w)
        drift_mean = np.mean(wins, axis=1)
        drift_t    = pre_t[w // 2: w // 2 + len(drift_mean)]
    else:
        drift_mean, drift_t = pre_amp, pre_t

    max_drift      = float(np.max(np.abs(drift_mean)))
    drift_detected = max_drift > drift_threshold_uv

    if ax is not None:
        ax.plot(drift_t, drift_mean, color='#E65100', linewidth=1.4,
                label='100 ms running mean')
        ax.axhline(0, color='gray', linewidth=0.7, linestyle=':')
        ax.axhline( drift_threshold_uv, color='red', linewidth=0.8,
                   linestyle='--', alpha=0.6)
        ax.axhline(-drift_threshold_uv, color='red', linewidth=0.8,
                   linestyle='--', alpha=0.6,
                   label=f'±{drift_threshold_uv:.0f} µV drift limit')
        lbl = 'DRIFT DETECTED' if drift_detected else 'Baseline stable'
        col = '#C62828' if drift_detected else '#2E7D32'
        ax.set_title(
            f'Baseline drift  |  max = {max_drift:.1f} µV  |  {lbl}',
            fontsize=10, color=col)
        ax.set_xlabel('Time (ms)', fontsize=10)
        ax.set_ylabel('Drift (µV)', fontsize=10)
        ax.legend(fontsize=9)

    return {'drift_detected': drift_detected, 'max_drift_uv': max_drift}


# ══════════════════════════════════════════════════════════════════════════════
# 5. Interactive Plotly waveform viewer
# ══════════════════════════════════════════════════════════════════════════════

def build_interactive_waveform(recording: dict,
                                norms:     dict = None,
                                protocol:  str  = 'DA 3.0') -> go.Figure:
    """Build the interactive Plotly waveform viewer used in the API clinical report.

    Features
    --------
    - ERG waveform with hover tooltip (time ms, amplitude µV)
    - Normative reference band (10th–90th centile), toggleable in legend
    - OP-filtered trace (75–300 Hz), hidden by default, toggleable
    - Stimulus onset marker
    - Exports as self-contained HTML with no Python dependency

    Parameters
    ----------
    recording : dict
        Standardised ERG dict (Chapter 3 format).
    norms : dict, optional
        Normative reference dict with keys time_ms, p10, p90 (arrays).
    protocol : str
        ISCEV protocol label.

    Returns
    -------
    go.Figure

    Notes
    -----
    Save as self-contained HTML for embedding in the clinical report:
        fig.write_html('report/patient_waveform.html', include_plotlyjs='cdn')
    """
    t   = recording['time_ms']
    amp = recording['amplitude_uv']
    fs  = recording['fs_hz']
    elc = recording.get('electrode_type', 'unknown')
    pid = recording.get('patient_id', 'Unknown')

    fig = go.Figure()

    # Normative reference band as a filled polygon.
    if norms is not None:
        x_band = list(norms['time_ms']) + list(norms['time_ms'])[::-1]
        y_band = list(norms['p90'])     + list(norms['p10'])[::-1]
        fig.add_trace(go.Scatter(
            x=x_band, y=y_band, fill='toself',
            fillcolor='rgba(180,180,180,0.22)',
            line=dict(color='rgba(0,0,0,0)'),
            name='Normative range (10th–90th centile)',
            hoverinfo='skip'))

    # Main ERG waveform.
    fig.add_trace(go.Scatter(
        x=t.tolist(), y=amp.tolist(),
        mode='lines', name=f'{protocol} ERG',
        line=dict(color='#2E75B6', width=2),
        hovertemplate='Time: %{x:.1f} ms<br>Amplitude: %{y:.1f} µV<extra></extra>'))

    # OP-filtered trace (hidden by default; toggle from legend).
    sos = butter(4, [75, 300], btype='bandpass', fs=fs, output='sos')
    op  = sosfiltfilt(sos, amp)
    fig.add_trace(go.Scatter(
        x=t.tolist(), y=op.tolist(),
        mode='lines', name='OPs (75–300 Hz)',
        line=dict(color='#2E7D32', width=1.2),
        visible='legendonly',
        hovertemplate='Time: %{x:.1f} ms<br>OP: %{y:.1f} µV<extra></extra>'))

    # Stimulus onset marker.
    fig.add_vline(x=0, line_width=1.2, line_dash='dash', line_color='red',
                  annotation_text='Stimulus onset',
                  annotation_position='top right')

    fig.update_layout(
        title=dict(
            text=f'ERG  |  Patient: {pid}  |  {protocol}  |  {elc} electrode',
            font=dict(size=14, family='Arial')),
        xaxis=dict(title='Time (ms)', gridcolor='#EEEEEE'),
        yaxis=dict(title='Amplitude (µV)', gridcolor='#EEEEEE',
                   zeroline=True, zerolinecolor='gray', zerolinewidth=0.8),
        legend=dict(orientation='h', y=-0.20),
        plot_bgcolor='white', height=480)

    return fig


# ══════════════════════════════════════════════════════════════════════════════
# 6. Topographic mfERG heatmap
# ══════════════════════════════════════════════════════════════════════════════

def plot_mferg_heatmap(mferg_data:    dict,
                       snr_threshold: float = 2.5,
                       show_quality:  bool  = True) -> plt.Figure:
    """Topographic mfERG heatmap with optional signal quality overlay.

    Parameters
    ----------
    mferg_data : dict
        Required keys:
          amplitudes  – 1-D array of per-element P1 amplitudes (nV/deg²)
          snr_values  – 1-D array of per-element SNR values
          coords      – list of (x, y) hex centre coordinates
          hex_radius  – float, radius of each hexagon in the coordinate system
    snr_threshold : float
        SNR below which a hex element is considered low quality (display only).
    show_quality : bool
        When True, adds a second panel showing per-element SNR quality map.

    Returns
    -------
    plt.Figure
    """
    amps   = np.array(mferg_data['amplitudes'])
    snrs   = np.array(mferg_data['snr_values'])
    coords = mferg_data['coords']
    r      = mferg_data['hex_radius']

    n_panels = 2 if show_quality else 1
    fig, axes = plt.subplots(1, n_panels, figsize=(6 * n_panels, 6))
    if n_panels == 1:
        axes = [axes]

    # Amplitude heatmap.
    amp_norm = plt.Normalize(vmin=0, vmax=float(np.nanpercentile(amps, 95)))
    amp_cmap = cm.get_cmap('RdYlBu_r')
    patches, colours = [], []
    for i, (x, y) in enumerate(coords):
        patches.append(RegularPolygon(
            (x, y), numVertices=6, radius=r * 0.94, orientation=np.pi / 6))
        val = amps[i] if i < len(amps) else 0
        colours.append(amp_cmap(amp_norm(val)))
    pc = PatchCollection(patches, facecolor=colours,
                         edgecolor='white', linewidth=0.4)
    axes[0].add_collection(pc)
    axes[0].autoscale_view()
    sm = plt.cm.ScalarMappable(cmap=amp_cmap, norm=amp_norm)
    plt.colorbar(sm, ax=axes[0], label='P1 amplitude (nV/deg²)')
    axes[0].set_title('mfERG Amplitude Map', fontsize=12, fontweight='bold')
    axes[0].set_aspect('equal')
    axes[0].axis('off')

    # Quality map: green = adequate SNR; red = below threshold.
    if show_quality:
        snr_norm = plt.Normalize(vmin=0, vmax=max(6, float(np.nanmax(snrs))))
        snr_cmap = cm.get_cmap('RdYlGn')
        q_patches, q_colours = [], []
        for i, (x, y) in enumerate(coords):
            q_patches.append(RegularPolygon(
                (x, y), numVertices=6, radius=r * 0.94, orientation=np.pi / 6))
            val = snrs[i] if i < len(snrs) else 0
            q_colours.append(snr_cmap(snr_norm(val)))
        qc = PatchCollection(q_patches, facecolor=q_colours,
                             edgecolor='white', linewidth=0.4)
        axes[1].add_collection(qc)
        axes[1].autoscale_view()
        sm2 = plt.cm.ScalarMappable(cmap=snr_cmap, norm=snr_norm)
        plt.colorbar(sm2, ax=axes[1], label='SNR per element')
        axes[1].set_title('mfERG Signal Quality Map', fontsize=12, fontweight='bold')
        axes[1].set_aspect('equal')
        axes[1].axis('off')

    fig.suptitle('Multifocal ERG Topographic Analysis',
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# Smoke test – runs only when executed directly; safe to import as a module
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    # Synthetic ERG: 200 ms pre-stimulus baseline + 300 ms post-stimulus response
    fs   = 2000
    t    = np.linspace(-200, 300, int(0.5 * fs), endpoint=False)
    noise = np.random.normal(0, 4, len(t))
    resp  = np.zeros(len(t))
    post  = t >= 0
    resp[post] = (
        -80  * np.exp(-((t[post] - 20)  ** 2) / (2 * 6  ** 2)) +   # a-wave
         250 * np.exp(-((t[post] - 55)  ** 2) / (2 * 12 ** 2)) +   # b-wave
         20  * np.sin(2 * np.pi * 120 * t[post] / 1000) *
               np.exp(-t[post] / 60)                                 # OPs
    )
    amp = resp + noise

    recording = {
        'time_ms':       t,
        'amplitude_uv':  amp,
        'fs_hz':         fs,
        'electrode_type': 'DTL fibre',
        'patient_id':    'TEST_001',
    }

    # 1. Annotated waveform
    fig1 = plot_erg_waveform(recording, protocol='DA 3.0')
    fig1.savefig('ch4_fig1_waveform.png', dpi=150, bbox_inches='tight')
    print('Saved: ch4_fig1_waveform.png')

    # 2. STFT spectrogram
    fig2 = plot_erg_spectrogram(recording, protocol='DA 3.0')
    fig2.savefig('ch4_fig2_spectrogram.png', dpi=150, bbox_inches='tight')
    print('Saved: ch4_fig2_spectrogram.png')

    # 3. SNR overlay on a fresh axis
    fig3, ax3 = plt.subplots(figsize=(12, 4))
    ax3.plot(t, amp, color='#2E75B6', linewidth=1.4)
    qc = add_snr_overlay(ax3, t, amp, fs, electrode='dtl')
    ax3.set_xlabel('Time (ms)'); ax3.set_ylabel('Amplitude (µV)')
    fig3.suptitle('SNR Overlay Demo', fontweight='bold')
    plt.tight_layout()
    fig3.savefig('ch4_fig3_snr_overlay.png', dpi=150, bbox_inches='tight')
    print(f'Saved: ch4_fig3_snr_overlay.png  |  QC: {qc}')

    # 4. Baseline drift
    fig4, ax4 = plt.subplots(figsize=(10, 3))
    drift = plot_baseline_drift(recording, ax=ax4)
    plt.tight_layout()
    fig4.savefig('ch4_fig4_drift.png', dpi=150, bbox_inches='tight')
    print(f'Saved: ch4_fig4_drift.png  |  Drift: {drift}')

    # 5. Interactive Plotly viewer
    fig5 = build_interactive_waveform(recording, protocol='DA 3.0')
    fig5.write_html('ch4_fig5_interactive.html', include_plotlyjs='cdn')
    print('Saved: ch4_fig5_interactive.html')

    # 6. mfERG heatmap (61-element synthetic grid)
    n_hex  = 61
    radius = 1.0
    cols   = [0, 1, 2, 3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 5, 4, 3, 2, 1, 0]
    coords = []
    row, col_count = 0, [5, 6, 7, 8, 7, 8, 7, 6, 5]
    y = 0.0
    for count in col_count:
        x_start = -(count - 1) * radius
        for c in range(count):
            coords.append((x_start + 2 * c * radius, y))
        y += radius * 1.732
    coords = coords[:n_hex]
    mferg_data = {
        'amplitudes':  np.abs(np.random.normal(25, 8, n_hex)),
        'snr_values':  np.abs(np.random.normal(4,  1, n_hex)),
        'coords':      coords,
        'hex_radius':  radius,
    }
    fig6 = plot_mferg_heatmap(mferg_data)
    fig6.savefig('ch4_fig6_mferg.png', dpi=150, bbox_inches='tight')
    print('Saved: ch4_fig6_mferg.png')

    plt.show()
