# -*- coding: utf-8 -*-
"""Chapter_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQm2MiiQibD5fHlcnaxsksDr5FvaATUX
"""

# -*- coding: utf-8 -*-
"""
chapter_08_erg_spectrogram_generation.py
==========================================
Hands-On Electroretinography in the Age of AI
Chapter 8 – Spectrogram Generation for Deep Learning

Implements the full spectrogram pipeline from filtered ERG sweep to
model-ready image input:

  STFT_CONFIG                  – Locked project-wide STFT configuration dict
  generate_erg_spectrogram     – Filtered ERG → normalised 224×224 float32 array
  validate_windows             – Empirical window-function selection via AUC-ROC
  flatten_spectrogram_for_ml   – Downsample + flatten for classical ML input
  SpectrogramPCAReducer        – PCA dimensionality reduction for classical ML

Pipeline summary (§8.3):
  1. STFT with Hamming window, nperseg=64, noverlap=56, fs=2000 Hz
  2. Power spectrogram → dB → z-score normalisation (clip ±3σ → [0, 1])
  3. Bicubic resize to 224×224 (ViT/CNN input resolution)

Repository : https://github.com/AI-Fairness-com/ERG-Analysis-API
Author     : Hamid
Licence    : See repo root LICENSE
"""

# ── Dependencies ───────────────────────────────────────────────────────────────
# Run once in your Colab session:
#   !pip install scipy scikit-image scikit-learn -q

import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import stft
from skimage.transform import resize
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, LabelBinarizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold


# ── Locked project-wide STFT configuration ────────────────────────────────────
# All parameters stored here for reproducibility across training and deployment.
# Any change to these values invalidates previously generated spectrograms and
# requires retraining the classifier from scratch.
STFT_CONFIG = {
    'window'   : 'hamming',    # empirically validated on project dataset (§8.2)
    'nperseg'  : 64,           # 32 ms window at 2000 Hz
    'noverlap' : 56,           # 87.5% overlap → 4 ms hop size
    'fs'       : 2000.0,       # Hz; must match recording metadata
    'fmin_hz'  : 0.0,          # include full ISCEV passband from DC
    'fmax_hz'  : 300.0,        # ISCEV upper cutoff
    'output_h' : 224,          # output image height (pixels)
    'output_w' : 224,          # output image width (pixels)
    'norm'     : 'db_zscore',  # normalisation strategy (see generate_erg_spectrogram)
}


# ══════════════════════════════════════════════════════════════════════════════
# 1. Core spectrogram generator
# ══════════════════════════════════════════════════════════════════════════════

def generate_erg_spectrogram(signal_uv:   np.ndarray,
                              config:      dict = None,
                              return_axes: bool = False):
    """Generate a normalised 2-D spectrogram array from a filtered ERG sweep.

    Steps
    -----
    1. Compute STFT with the configured window, nperseg, and noverlap.
    2. Convert complex STFT output to power in dB.
    3. Crop to the clinical frequency range [fmin_hz, fmax_hz].
    4. Normalise: z-score within the recording, clip to ±3σ, rescale to [0, 1].
    5. Bicubic resize to (output_h, output_w) for fixed-size model input.

    Parameters
    ----------
    signal_uv : np.ndarray
        1-D filtered ERG array in µV (output of Chapter 5 pipeline).
    config : dict, optional
        STFT configuration dict. Defaults to STFT_CONFIG above.
    return_axes : bool
        When True, also return (freqs_hz, times_s) for axis labelling.

    Returns
    -------
    S_norm : np.ndarray
        2-D float32 array, shape (output_h, output_w), values in [0, 1].
        Ready for single-channel image input. Add a channel dimension before
        passing to a ViT or CNN:  S_norm[np.newaxis, ...]  or
        torch.tensor(S_norm).unsqueeze(0).
    freqs, times : np.ndarray (only when return_axes=True)
        Frequency axis (Hz) and time axis (s) of the raw STFT output,
        before cropping and resizing.

    Notes
    -----
    Normalisation strategy 'db_zscore' is amplitude-invariant: a recording
    with a large b-wave and one with a small b-wave will have the same mean
    and std after normalisation. The spectral PATTERN is preserved; only
    absolute amplitude differences between recordings are removed. This is
    intentional — the ViT classifier learns from spectral shape, not raw
    amplitude, because amplitude is handled separately by the Traffic Light
    z-score framework (Chapter 15).
    """
    cfg = config or STFT_CONFIG

    # Step 1 – STFT
    freqs, times, Zxx = stft(signal_uv,
                              fs       = cfg['fs'],
                              window   = cfg['window'],
                              nperseg  = cfg['nperseg'],
                              noverlap = cfg['noverlap'])

    # Step 2 – Power in dB
    power = np.abs(Zxx) ** 2
    S_db  = 10 * np.log10(power + 1e-12)

    # Step 3 – Crop to clinical frequency range
    fmask = (freqs >= cfg['fmin_hz']) & (freqs <= cfg['fmax_hz'])
    S_db  = S_db[fmask, :]
    freqs_cropped = freqs[fmask]

    # Step 4 – Normalisation
    if cfg['norm'] == 'db_zscore':
        mu    = S_db.mean()
        sigma = S_db.std() + 1e-8
        S_n   = (S_db - mu) / sigma
        S_n   = np.clip(S_n, -3, 3)
        S_n   = (S_n + 3) / 6.0          # rescale to [0, 1]
    elif cfg['norm'] == 'minmax':
        lo, hi = S_db.min(), S_db.max()
        S_n    = (S_db - lo) / (hi - lo + 1e-8)
    else:
        raise ValueError(f'Unknown normalisation strategy: {cfg["norm"]}')

    # Step 5 – Bicubic resize to fixed output dimensions
    S_norm = resize(S_n,
                    (cfg['output_h'], cfg['output_w']),
                    order=3,
                    anti_aliasing=True,
                    preserve_range=True).astype(np.float32)

    if return_axes:
        return S_norm, freqs_cropped, times
    return S_norm


# ══════════════════════════════════════════════════════════════════════════════
# 2. Window-function empirical validation
# ══════════════════════════════════════════════════════════════════════════════

WINDOWS  = ['boxcar', 'triang', 'hann', 'hamming', 'blackman']
_NPERSEG  = STFT_CONFIG['nperseg']
_NOVERLAP = STFT_CONFIG['noverlap']
_FS       = STFT_CONFIG['fs']


def _spectro_features(signal_uv: np.ndarray, window: str) -> np.ndarray:
    """Compute a flattened 64×64 log-power spectrogram feature vector.

    Internal helper used by validate_windows(). Intentionally uses a smaller
    output size (64×64) than the production pipeline (224×224) to keep
    cross-validation runtime tractable.
    """
    _, _, Zxx   = stft(signal_uv, fs=_FS, window=window,
                       nperseg=_NPERSEG, noverlap=_NOVERLAP)
    S           = np.abs(Zxx) ** 2
    S_small     = resize(S, (64, 64), anti_aliasing=True, preserve_range=True)
    return np.log1p(S_small).ravel()


def validate_windows(X_sweeps: np.ndarray,
                     y_labels: np.ndarray) -> dict:
    """Empirically select the best STFT window via 5-fold stratified AUC-ROC.

    Evaluates all five candidate windows against the project dataset using a
    Random Forest classifier. The window with the highest mean macro AUC-ROC
    across folds is selected and should be locked into STFT_CONFIG['window'].

    Parameters
    ----------
    X_sweeps : np.ndarray
        Shape (n_recordings, n_samples). Filtered ERG sweeps.
    y_labels : np.ndarray
        Shape (n_recordings,). Integer class labels.

    Returns
    -------
    dict
        {window_name: mean_auc_roc} for all five candidate windows.

    Notes
    -----
    On the project dataset (Baker et al., 2025, N=407), 'hamming' achieved
    the highest macro AUC-ROC and is the locked default in STFT_CONFIG.
    Re-run this function if the training set changes materially.
    """
    lb      = LabelBinarizer().fit(y_labels)
    cv      = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    results = {}

    for win in WINDOWS:
        print(f'Evaluating window: {win} ...', end=' ', flush=True)
        X_feat    = np.array([_spectro_features(x, win) for x in X_sweeps])
        fold_aucs = []
        for train_idx, test_idx in cv.split(X_feat, y_labels):
            clf = RandomForestClassifier(n_estimators=100, max_depth=8,
                                         random_state=42, n_jobs=-1)
            clf.fit(X_feat[train_idx], y_labels[train_idx])
            y_prob = clf.predict_proba(X_feat[test_idx])
            auc    = roc_auc_score(lb.transform(y_labels[test_idx]),
                                   y_prob, multi_class='ovr', average='macro')
            fold_aucs.append(auc)
        mean_auc       = float(np.mean(fold_aucs))
        results[win]   = mean_auc
        print(f'AUC = {mean_auc:.4f}')

    best = max(results, key=results.get)
    print(f'\nSelected window: {best}  (AUC = {results[best]:.4f})')
    print('Lock selection into STFT_CONFIG[\'window\'] before generating '
          'the training spectrogram batch.')
    return results


# ══════════════════════════════════════════════════════════════════════════════
# 3. Classical ML helpers
# ══════════════════════════════════════════════════════════════════════════════

def flatten_spectrogram_for_ml(S_norm:     np.ndarray,
                                small_size: int = 32) -> np.ndarray:
    """Downsample a normalised 224×224 spectrogram and flatten to 1-D.

    Reduces the 224×224 image (50,176 values) to a small_size×small_size
    vector (default 1,024 values) suitable as input to SVM or Random Forest
    classifiers (Chapter 12). For the ViT classifier (Chapter 13), use the
    full 224×224 array directly.

    Parameters
    ----------
    S_norm : np.ndarray
        Output of generate_erg_spectrogram(), shape (output_h, output_w).
    small_size : int
        Target side length in pixels (default 32 → 1,024 features).

    Returns
    -------
    np.ndarray
        1-D float32 feature vector of length small_size².
    """
    S_small = resize(S_norm, (small_size, small_size),
                     order=3, anti_aliasing=True, preserve_range=True)
    return S_small.ravel().astype(np.float32)


class SpectrogramPCAReducer:
    """PCA-based dimensionality reducer for spectrogram feature vectors.

    Fit on the training set; apply to validation, test, and deployment
    recordings. Combines StandardScaler (zero mean, unit variance) with PCA
    to produce a compact, decorrelated feature matrix for classical ML.

    Parameters
    ----------
    n_components : int
        Number of PCA components to retain (default 128).
    small_size : int
        Intermediate downsampling size before PCA (default 32 → 1,024 input
        features per spectrogram).

    Example
    -------
    reducer = SpectrogramPCAReducer(n_components=128)
    X_train = reducer.fit_transform(train_spectrograms)   # (N, 128)
    X_test  = reducer.transform(test_spectrograms)        # (M, 128)
    # Pass X_train / X_test to SVM or Random Forest in Chapter 12.
    """

    def __init__(self, n_components: int = 128, small_size: int = 32):
        self.pca        = PCA(n_components=n_components, random_state=42)
        self.scaler     = StandardScaler()
        self.small_size = small_size

    def fit(self, spectrograms: list) -> 'SpectrogramPCAReducer':
        """Fit scaler and PCA on a list of (output_h, output_w) arrays."""
        X         = np.array([flatten_spectrogram_for_ml(S, self.small_size)
                               for S in spectrograms])
        X_scaled  = self.scaler.fit_transform(X)
        self.pca.fit(X_scaled)
        explained = self.pca.explained_variance_ratio_.cumsum()
        print(f'PCA: {self.pca.n_components_} components explain '
              f'{100 * explained[-1]:.1f}% of variance')
        return self

    def transform(self, spectrograms: list) -> np.ndarray:
        """Transform a list of spectrograms to PCA feature matrix."""
        X = np.array([flatten_spectrogram_for_ml(S, self.small_size)
                      for S in spectrograms])
        return self.pca.transform(self.scaler.transform(X))

    def fit_transform(self, spectrograms: list) -> np.ndarray:
        """Fit and transform in one step."""
        return self.fit(spectrograms).transform(spectrograms)


# ══════════════════════════════════════════════════════════════════════════════
# Smoke test
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':

    # ── Synthetic ERG signals (same model as Chapters 5–7) ────────────────
    fs    = int(STFT_CONFIG['fs'])
    epoch = 500      # ms
    pre   = 100      # ms pre-stimulus
    N     = int(fs * epoch / 1000)
    t_ms  = np.linspace(0, epoch, N, endpoint=False)

    def make_sweep(a_amp=-120, b_amp=280, op_scale=1.0,
                   noise_sd=5, seed=0) -> np.ndarray:
        rng = np.random.default_rng(seed)
        sig = np.zeros(N)
        sig += a_amp * np.exp(-((t_ms - (pre + 20)) ** 2) / (2 * 8  ** 2))
        sig += b_amp * np.exp(-((t_ms - (pre + 60)) ** 2) / (2 * 18 ** 2))
        for op_t, op_a in [(28, 18), (35, 22), (45, 16), (58, 10)]:
            sig += (op_scale * op_a
                    * np.sin(2 * np.pi * 120 * (t_ms - (pre + op_t)) / 1000)
                    * np.exp(-((t_ms - (pre + op_t)) ** 2) / (2 * 5 ** 2)))
        return sig + rng.normal(0, noise_sd, N)

    normal   = make_sweep(seed=0)
    early_dr = make_sweep(b_amp=230, op_scale=0.4, seed=1)   # reduced OPs
    adv_rp   = make_sweep(a_amp=-10, b_amp=22, op_scale=0.05, seed=2)  # near-extinct

    # ── 1. Generate spectrograms ───────────────────────────────────────────
    S_normal   = generate_erg_spectrogram(normal,   STFT_CONFIG)
    S_early_dr = generate_erg_spectrogram(early_dr, STFT_CONFIG)
    S_adv_rp   = generate_erg_spectrogram(adv_rp,   STFT_CONFIG)

    print(f'Spectrogram shape : {S_normal.shape}  dtype={S_normal.dtype}')
    print(f'Value range       : [{S_normal.min():.3f}, {S_normal.max():.3f}]')

    # ── 2. Visual comparison of three spectrograms ────────────────────────
    fig1, axes = plt.subplots(1, 3, figsize=(15, 5))
    for ax, S, label in zip(axes,
                             [S_normal, S_early_dr, S_adv_rp],
                             ['Normal', 'Early DR', 'Advanced RP']):
        ax.imshow(S, aspect='auto', origin='lower',
                  cmap='inferno', vmin=0, vmax=1)
        ax.set_title(label, fontsize=12)
        ax.set_xlabel('Time (resized)', fontsize=9)
        ax.set_ylabel('Frequency (resized)', fontsize=9)
    fig1.suptitle('Normalised ERG Spectrograms (224×224, Hamming, db_zscore)',
                  fontsize=12, fontweight='bold')
    plt.tight_layout()
    fig1.savefig('ch8_fig1_spectrograms.png', dpi=150, bbox_inches='tight')
    print('Saved: ch8_fig1_spectrograms.png')

    # ── 3. Spectrogram with labelled frequency/time axes ──────────────────
    # Plot the raw (pre-resize) STFT so pcolormesh axes and data are consistent.
    cfg = STFT_CONFIG
    from scipy.signal import stft as _stft
    freqs_raw, times_raw, Zxx = _stft(normal, fs=cfg['fs'],
                                       window=cfg['window'],
                                       nperseg=cfg['nperseg'],
                                       noverlap=cfg['noverlap'])
    S_db_raw = 10 * np.log10(np.abs(Zxx) ** 2 + 1e-12)
    fmask    = (freqs_raw >= cfg['fmin_hz']) & (freqs_raw <= cfg['fmax_hz'])
    S_db_raw = S_db_raw[fmask, :]
    freqs    = freqs_raw[fmask]
    mu, sigma = S_db_raw.mean(), S_db_raw.std() + 1e-8
    S_plot   = np.clip((S_db_raw - mu) / sigma, -3, 3)
    S_plot   = (S_plot + 3) / 6.0
    times_ms = times_raw * 1000 - pre    # align to stimulus onset

    fig2, ax2 = plt.subplots(figsize=(11, 5))
    img = ax2.pcolormesh(times_ms, freqs, S_plot,
                         cmap='inferno', shading='nearest', vmin=0, vmax=1)
    ax2.axvline(0, color='cyan', lw=1.2, ls='--', label='Stimulus onset')
    ax2.axhspan(75, 300, alpha=0.12, color='orange', label='OP band')
    ax2.set_xlabel('Time (ms)', fontsize=11)
    ax2.set_ylabel('Frequency (Hz)', fontsize=11)
    ax2.set_title('Normalised Spectrogram – Normal DA 3.0 (labelled axes)',
                  fontsize=12, fontweight='bold')
    plt.colorbar(img, ax=ax2, label='Normalised power [0, 1]')
    ax2.legend(fontsize=9)
    plt.tight_layout()
    fig2.savefig('ch8_fig2_spectrogram_axes.png', dpi=150, bbox_inches='tight')
    print('Saved: ch8_fig2_spectrogram_axes.png')

    # ── 4. PCA dimensionality reduction smoke test ─────────────────────────
    # Build a small synthetic dataset: 30 recordings, 3 classes
    spectrograms = []
    labels       = []
    for cls, (a, b, op, ns) in enumerate([
            (-120, 280, 1.0,  5),   # Normal
            (-80,  230, 0.4,  6),   # Early DR
            (-10,   22, 0.05, 7),   # Advanced RP
    ]):
        for seed in range(10):
            sig = make_sweep(a_amp=a, b_amp=b, op_scale=op,
                             noise_sd=ns, seed=seed + cls * 10)
            spectrograms.append(generate_erg_spectrogram(sig, STFT_CONFIG))
            labels.append(cls)

    reducer = SpectrogramPCAReducer(n_components=10, small_size=16)
    X_pca   = reducer.fit_transform(spectrograms)
    print(f'\nPCA output shape: {X_pca.shape}')

    # Scatter plot of first two PCA components
    fig3, ax3 = plt.subplots(figsize=(7, 6))
    colours = ['#2E75B6', '#E65100', '#C62828']
    names   = ['Normal', 'Early DR', 'Advanced RP']
    for cls in range(3):
        mask = np.array(labels) == cls
        ax3.scatter(X_pca[mask, 0], X_pca[mask, 1],
                    color=colours[cls], label=names[cls], s=60, alpha=0.8)
    ax3.set_xlabel('PC 1', fontsize=11)
    ax3.set_ylabel('PC 2', fontsize=11)
    ax3.set_title('PCA of Spectrogram Features (10 recordings × 3 classes)',
                  fontsize=11, fontweight='bold')
    ax3.legend(fontsize=10)
    ax3.grid(True, alpha=0.25)
    plt.tight_layout()
    fig3.savefig('ch8_fig3_pca_scatter.png', dpi=150, bbox_inches='tight')
    print('Saved: ch8_fig3_pca_scatter.png')

    plt.show()
