# -*- coding: utf-8 -*-
"""Chapter_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGjUxRGOq73OYAv2GZMLi9XvvgSZ692y
"""

# -*- coding: utf-8 -*-
"""
chapter_03_erg_signal_loading.py
=================================
Hands-On Electroretinography in the Age of AI
Chapter 3 – Loading and Inspecting ERG Signals

Demonstrates two ingestion paths:
  A. EDF  → MNE-Python  (device-native binary format)
  B. CSV  → pandas      (standardised template format)

Both paths produce identically structured NumPy arrays (time_ms, amplitude_uV)
and a quality-control summary (sampling rate, duration, noise RMS, SNR).
Path B also produces an annotated waveform plot saved as a PNG.

Repository : https://github.com/AI-Fairness-com/ERG-Analysis-API
Author     : Hamid
Licence    : See repo root LICENSE
"""

# ── 0. Dependencies ────────────────────────────────────────────────────────────
# Run once in your Colab session (no-op if already installed):
#   !pip install mne -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# ══════════════════════════════════════════════════════════════════════════════
# PATH A – EDF ingestion via MNE-Python
# ══════════════════════════════════════════════════════════════════════════════

from google.colab import files
files.upload()  # select normal_001_DA3.csv


def load_edf(edf_path: str) -> tuple:
    """Load a single ERG channel from an EDF file.

    Parameters
    ----------
    edf_path : str
        Path to the .edf file.  In Colab, upload first:
            from google.colab import files; files.upload()

    Returns
    -------
    times_ms : np.ndarray  – time axis in milliseconds
    erg_uV   : np.ndarray  – amplitude in microvolts
    fs       : float       – sampling rate in Hz

    Notes
    -----
    Unit check: raw.info['chs'][0]['unit'] should equal 107 (volts).
    Some devices export in mV (unit 201) – multiply by 1e3 instead of 1e6.
    """
    import mne  # imported here so the module loads without mne installed
    raw      = mne.io.read_raw_edf(edf_path, preload=True, verbose=False)
    erg_data = raw.get_data(picks='ERG')[0]   # volts
    erg_uV   = erg_data * 1e6                 # convert V → µV
    times_ms = raw.times * 1000               # convert s  → ms
    fs       = raw.info['sfreq']
    print(f'[EDF] Loaded {len(erg_uV)} samples at {fs:.0f} Hz')
    print(f'      Duration: {times_ms[-1]:.1f} ms  |  '
          f'Range: {erg_uV.min():.1f} to {erg_uV.max():.1f} µV')
    return times_ms, erg_uV, fs


# ══════════════════════════════════════════════════════════════════════════════
# PATH B – CSV ingestion (standardised template format)
# ══════════════════════════════════════════════════════════════════════════════

def load_csv(csv_path: str) -> tuple:
    """Load an ERG recording from the project's standardised CSV template.

    Expected columns: time_ms, amplitude_uV, protocol, eye,
                      electrode_type, patient_id

    Parameters
    ----------
    csv_path : str
        Path to the CSV file.  In Colab, upload first:
            from google.colab import files; files.upload()
        Then pass the bare filename (e.g. 'normal_001_DA3.csv').

    Returns
    -------
    time_ms   : np.ndarray
    amplitude : np.ndarray
    fs        : float
    """
    df        = pd.read_csv(csv_path)
    time_ms   = df['time_ms'].values
    amplitude = df['amplitude_uV'].values
    fs        = 1000.0 / (time_ms[1] - time_ms[0])
    print(df.head())
    return time_ms, amplitude, fs


# ══════════════════════════════════════════════════════════════════════════════
# Quality control
# ══════════════════════════════════════════════════════════════════════════════

def quality_report(time_ms: np.ndarray,
                   amplitude: np.ndarray,
                   fs: float,
                   pre_stim_end_ms: float = 100.0) -> dict:
    """Compute and print a concise QC summary.

    Parameters
    ----------
    time_ms         : time axis (ms)
    amplitude       : amplitude array (µV)
    fs              : sampling rate (Hz)
    pre_stim_end_ms : end of pre-stimulus baseline window (ms); default 100

    Returns
    -------
    dict with keys: fs, duration_ms, amp_min, amp_max, noise_rms, snr, flag
    """
    duration_ms = time_ms[-1] - time_ms[0]
    pre_mask    = time_ms < pre_stim_end_ms
    noise_rms   = np.sqrt(np.mean(amplitude[pre_mask] ** 2))
    snr         = (amplitude.max() - amplitude.min()) / noise_rms
    flag        = 'PASS' if snr >= 4 else ('WARNING' if snr >= 2.5 else 'FAIL')

    print(f'Sampling rate   : {fs:.0f} Hz')
    print(f'Duration        : {duration_ms:.0f} ms')
    print(f'Amplitude range : {amplitude.min():.1f} to {amplitude.max():.1f} µV')
    print(f'Noise RMS       : {noise_rms:.1f} µV')
    print(f'SNR (approx.)   : {snr:.1f}')
    print(f'Quality flag    : {flag}')

    return dict(fs=fs, duration_ms=duration_ms,
                amp_min=amplitude.min(), amp_max=amplitude.max(),
                noise_rms=noise_rms, snr=snr, flag=flag)


# ══════════════════════════════════════════════════════════════════════════════
# Annotated waveform plot
# ══════════════════════════════════════════════════════════════════════════════

def plot_waveform(time_ms: np.ndarray,
                 amplitude: np.ndarray,
                 qc: dict,
                 pre_stim_end_ms: float = 100.0,
                 save_path: str = 'chapter3_normal_waveform.png') -> None:
    """Plot and save an annotated ERG waveform.

    Annotations: pre-stimulus baseline shading, stimulus onset marker,
    a-wave trough, and b-wave peak.
    """
    post_mask = time_ms >= pre_stim_end_ms
    post_stim = amplitude[post_mask]
    post_time = time_ms[post_mask]

    a_idx = np.argmin(post_stim)
    b_idx = np.argmax(post_stim)
    a_time, a_amp = post_time[a_idx], post_stim[a_idx]
    b_time, b_amp = post_time[b_idx], post_stim[b_idx]

    fig, ax = plt.subplots(figsize=(12, 5))
    ax.axvspan(0, pre_stim_end_ms, alpha=0.10, color='gray',
               label='Pre-stimulus baseline')
    ax.plot(time_ms, amplitude, color='#2E75B6', linewidth=1.6,
            label='ERG waveform (DTL fibre, DA 3.0)')
    ax.axvline(pre_stim_end_ms, color='red', linewidth=1.2,
               linestyle='--', label=f'Stimulus onset (t = {pre_stim_end_ms:.0f} ms)')
    ax.axhline(0, color='gray', linewidth=0.6, linestyle=':')

    arrow = dict(arrowstyle='->', color='black')
    ax.annotate(f'a-wave\n{a_amp:.0f} µV @ {a_time:.0f} ms',
                xy=(a_time, a_amp), xytext=(a_time + 30, a_amp - 30),
                arrowprops=arrow, fontsize=9)
    ax.annotate(f'b-wave\n{b_amp:.0f} µV @ {b_time:.0f} ms',
                xy=(b_time, b_amp), xytext=(b_time + 20, b_amp + 20),
                arrowprops=arrow, fontsize=9)

    ax.set_xlabel('Time (ms)', fontsize=12)
    ax.set_ylabel('Amplitude (µV)', fontsize=12)
    ax.set_title(
        f'ERG Recording – Normal Subject | DA 3.0 Protocol | DTL Fibre | '
        f'SNR = {qc["snr"]:.1f}  [{qc["flag"]}]',
        fontsize=12)
    ax.legend(fontsize=10)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.show()
    print(f'Saved: {save_path}')


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':

    # ── Path A: EDF ────────────────────────────────────────────────────────
    # Colab: !pip install mne -q
    #        from google.colab import files; files.upload()
    # Then replace the filename below.
    #
    # times_ms, erg_uV, fs = load_edf('patient_001.edf')
    # qc = quality_report(times_ms, erg_uV, fs)

    # ── Path B: CSV ────────────────────────────────────────────────────────
    # Colab: from google.colab import files; files.upload()
    # Then replace the filename below.
    #
    time_ms, amplitude, fs = load_csv('normal_001_DA3.csv')
    qc = quality_report(time_ms, amplitude, fs)
    plot_waveform(time_ms, amplitude, qc)