# -*- coding: utf-8 -*-
"""Chapter_19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZncf2zKs2HVyUUrrdhHqvaUVwURmnvX
"""

# -*- coding: utf-8 -*-
"""
chapter_19_api_pipeline.py
============================
Hands-On Electroretinography in the Age of AI
Chapter 19 – Clinical Case Studies and Complete API Pipeline

This chapter contains no new code: it is the integration chapter that assembles
every component from Chapters 1–18 into a complete end-to-end pipeline and
exercises it across eight clinical case studies plus one data quality failure case.

This module provides:

  ERGAPIConfig          – Single config object carrying all locked parameters
  validate_csv_schema   – CSV schema validation (HALT on missing required fields)
  run_single_visit_pipeline – Complete 8-stage pipeline for one recording
  run_longitudinal_pipeline – Serial pipeline for patients with prior visits
  CaseStudyRunner       – Runs all 9 case studies and saves outputs

Eight processing stages (§19.10.1):
  Stage 1  CSV ingestion and schema validation
  Stage 2  Signal processing (Chapters 5–7)
  Stage 3  Feature extraction (Chapter 9)
  Stage 4  Normative Z-score + Traffic Light (Chapter 15)
  Stage 5  Missing data handling (Chapter 11)
  Stage 6  Classifier: Stage 1 binary + Stage 2 six-class (Chapters 12–13)
  Stage 7  Explainability: SHAP three levels (Chapter 14)
  Stage 8  Report generation: Layer 1–4 (Chapters 17–18)

Three pipeline output states (§19.9):
  PASS            – full report + SHAP attribution
  WARNING         – full report + SHAP suppressed + mandatory caveats
  HALT            – Layer 1 error report only, specific remediation message

Two deployment modes (§19.10.2):
  Mode A  Cloud REST API, GPU, ViT Small primary, ~0.8 s/recording
  Mode B  Offline Python package, CPU, Random Forest primary, ~4.2 s/recording

Case studies (§19.1–19.9):
  1  Normal ERG with hydroxychloroquine baseline (Mrs. T., 67 y)
  2  Early diabetic retinopathy, fundus-negative (Mr. K., 51 y)
  3  Retinitis pigmentosa / rod dystrophy, PRPF31 (Ms. F., 34 y)
  4  Longitudinal follow-up, RP year 5 (Mr. P., 48 y)
  5  Early glaucoma, pre-perimetric (Mr. D., 58 y)
  6  Age-related macular degeneration, early (Mrs. H., 72 y)
  7  Cone dystrophy, bilateral (Mr. A., 29 y)
  8  Complete CSNB, Schubert-Bornschein (Master J., 14 y)
  9  Data quality failure: SIGNAL_QUALITY_WARNING + ELECTRODE_UNKNOWN

Repository : https://github.com/AI-Fairness-com/ERG-Analysis-API
Author     : Hamid
Licence    : See repo root LICENSE
"""

# ── Dependencies ───────────────────────────────────────────────────────────────
import os
import json
import datetime
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from dataclasses import dataclass, field
from typing import Optional, Dict, Any

# ── Locked project constants ───────────────────────────────────────────────────
API_VERSION       = '1.0.0'
NORMATIVE_VERSION = 'Robson2025_v1'

# Traffic Light thresholds (Chapter 10 / Chapter 15)
TL_GREEN = 2.0
TL_AMBER = 3.0

# SNR thresholds by electrode type (Chapter 2 §2.4)
SNR_THRESHOLDS = {
    'contact_lens': {'pass': 8.0, 'warn': 5.0},
    'gold_foil'   : {'pass': 6.0, 'warn': 4.0},
    'dtl_fiber'   : {'pass': 4.0, 'warn': 2.5},
    'skin'        : {'pass': 3.0, 'warn': 1.5},
}

# Required CSV schema fields (Appendix A)
REQUIRED_CSV_FIELDS = [
    'patient_id', 'date', 'age', 'sex',
    'electrode_type', 'protocol', 'eye',
    'time_ms', 'amplitude_uv',
]

# SHAP suppression threshold: suppress if SNR < this value for electrode type
SHAP_SUPPRESS_WARN = True   # always suppress SHAP on WARNING recordings

# Case study parameter catalogue (§19.1–19.9)
# Each dict provides the synthetic ERG parameters for the case
CASE_STUDIES = {
    'CS01_Normal_HCQ': {
        'patient_id'    : 'MRS_T_001',
        'age'           : 67,
        'sex'           : 'F',
        'electrode'     : 'dtl_fiber',
        'protocol'      : 'DA_3.0',
        'disease_class' : 'Normal',
        'b_amp_uv'      : 175.0,   # normal for ≥60y DTL
        'b_implicit_ms' : 51.2,
        'a_amp_uv'      : 88.0,
        'phnr_amp_uv'   : 26.0,
        'op2_amp_uv'    : 18.0,
        'snr_db'        : 7.2,
        'hcq_patient'   : True,
        'notes'         : 'Hydroxychloroquine baseline; all parameters GREEN',
    },
    'CS02_EarlyDR': {
        'patient_id'    : 'MR_K_002',
        'age'           : 51,
        'sex'           : 'M',
        'electrode'     : 'dtl_fiber',
        'protocol'      : 'DA_3.0',
        'disease_class' : 'Diabetic Retinopathy (early)',
        'b_amp_uv'      : 162.0,
        'b_implicit_ms' : 54.8,
        'a_amp_uv'      : 82.0,
        'phnr_amp_uv'   : 24.5,
        'op2_amp_uv'    : 14.2,
        'op2_implicit_ms': 34.1,   # delayed (Z = +3.8, RED)
        'snr_db'        : 8.4,
        'notes'         : 'Fundus-negative; OP2 implicit time RED; dominant SHAP',
    },
    'CS03_RP': {
        'patient_id'    : 'MS_F_003',
        'age'           : 34,
        'sex'           : 'F',
        'electrode'     : 'dtl_fiber',
        'protocol'      : 'DA_3.0',
        'disease_class' : 'Retinitis Pigmentosa / Rod Dystrophy',
        'b_amp_uv'      : 31.0,    # Z = −6.2, RED
        'b_implicit_ms' : 74.1,    # Z = +4.8, RED
        'a_amp_uv'      : 18.0,
        'phnr_amp_uv'   : 22.0,
        'op2_amp_uv'    : 3.2,
        'snr_db'        : 5.1,
        'notes'         : 'PRPF31 variant; diffuse negative SHAP pattern',
    },
    'CS04_Longitudinal_RP': {
        'patient_id'    : 'MR_P_004',
        'age'           : 48,
        'sex'           : 'M',
        'electrode'     : 'dtl_fiber',
        'protocol'      : 'DA_3.0',
        'disease_class' : 'Retinitis Pigmentosa / Rod Dystrophy',
        'b_amp_uv'      : 41.0,    # 5th annual visit; below 50% baseline (94 µV)
        'b_implicit_ms' : 70.3,
        'a_amp_uv'      : 22.0,
        'op2_amp_uv'    : 4.1,
        'snr_db'        : 4.8,
        'visit_number'  : 5,
        'baseline_b_amp': 94.0,    # year 0 baseline
        'prior_b_amp'   : 51.8,    # year 4 (for CoR check)
        'notes'         : 'RP_AMPLITUDE_MILESTONE triggered; BELOW_MDC95 visit flag',
    },
    'CS05_Glaucoma': {
        'patient_id'    : 'MR_D_005',
        'age'           : 58,
        'sex'           : 'M',
        'electrode'     : 'dtl_fiber',
        'protocol'      : 'LA_3.0',
        'disease_class' : 'Glaucoma (early)',
        'b_amp_uv'      : 168.0,
        'b_implicit_ms' : 30.4,
        'phnr_amp_uv'   : 12.8,    # reduced (Z = −3.1, RED)
        'snr_db'        : 7.8,
        'notes'         : 'Pre-perimetric; PhNR dominant SHAP contributor',
    },
    'CS06_AMD': {
        'patient_id'    : 'MRS_H_006',
        'age'           : 72,
        'sex'           : 'F',
        'electrode'     : 'dtl_fiber',
        'protocol'      : 'LA_30Hz',
        'disease_class' : 'Age-Related Macular Degeneration',
        'b_amp_uv'      : 118.0,
        'b_implicit_ms' : 51.8,
        'la30_amp_uv'   : 68.0,    # mildly reduced
        'stage2_proba'  : 0.54,    # low confidence — honest reporting
        'snr_db'        : 6.2,
        'notes'         : 'Lowest confidence; AMD Brier Score 0.18; AMBER',
    },
    'CS07_ConeDystrophy': {
        'patient_id'    : 'MR_A_007',
        'age'           : 29,
        'sex'           : 'M',
        'electrode'     : 'dtl_fiber',
        'protocol'      : 'LA_3.0',
        'disease_class' : 'Cone Dystrophy',
        'b_amp_uv'      : 182.0,   # scotopic normal
        'b_implicit_ms' : 50.2,
        'la30_amp_uv'   : 42.0,    # photopic reduced (Z = −3.4, RED)
        'phnr_amp_uv'   : 18.0,
        'snr_db'        : 6.9,
        'notes'         : 'Selective photopic abnormality; cross-electrode transference',
    },
    'CS08_CSNB': {
        'patient_id'    : 'MASTER_J_008',
        'age'           : 14,
        'sex'           : 'M',
        'electrode'     : 'contact_lens',
        'protocol'      : 'DA_3.0',
        'disease_class' : 'Complete CSNB',
        'b_amp_uv'      : 28.0,    # Schubert-Bornschein negative ERG
        'b_implicit_ms' : 52.1,
        'a_amp_uv'      : 210.0,   # preserved a-wave
        'ba_ratio'      : 0.13,    # < 1.0 → negative ERG (Z = −8.1, RED)
        'snr_db'        : 9.1,
        'notes'         : 'Highest-confidence classification (AUC 0.93); non-progressive',
    },
    'CS09_DataQuality': {
        'patient_id'    : 'MR_G_009',
        'age'           : 71,
        'sex'           : 'M',
        'electrode_A'   : 'skin',
        'electrode_B'   : None,    # missing → HALT
        'protocol'      : 'LA_3.0',
        'disease_class' : 'Age-Related Macular Degeneration',
        'snr_db_A'      : 2.1,     # WARNING band (skin: warn 1.5–2.9 dB)
        'snr_db_B'      : None,
        'notes'         : 'Scenario A: SIGNAL_QUALITY_WARNING; Scenario B: HALT',
    },
}


# ══════════════════════════════════════════════════════════════════════════════
# 1. API configuration dataclass
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class ERGAPIConfig:
    """Carries all locked pipeline parameters in one serialisable object.

    Instantiate once per deployment and pass through all pipeline stages.
    Every report's Layer 4 audit record stores a hash of this config.
    """
    api_version       : str  = API_VERSION
    normative_version : str  = NORMATIVE_VERSION
    stft_window       : str  = 'hamming'
    stft_nperseg      : int  = 64
    stft_noverlap     : int  = 56
    fs_hz             : float = 2000.0
    img_size          : int  = 224
    tl_green          : float = TL_GREEN
    tl_amber          : float = TL_AMBER
    deployment_mode   : str  = 'mode_b'   # 'mode_a' (cloud) or 'mode_b' (offline)
    output_dir        : str  = 'outputs/api'
    shap_suppress_warn: bool = SHAP_SUPPRESS_WARN
    extra             : Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        import dataclasses
        return dataclasses.asdict(self)


# ══════════════════════════════════════════════════════════════════════════════
# 2. CSV schema validation (Stage 1)
# ══════════════════════════════════════════════════════════════════════════════

def validate_csv_schema(df: pd.DataFrame,
                         patient_id: str = 'UNKNOWN') -> dict:
    """Validate a submitted ERG CSV against the Standardized schema (Appendix A).

    Missing required fields trigger a HALT: the pipeline does not proceed to
    any subsequent stage. All required fields must be present and non-null.
    The electrode_type field requires a recognised value; without it no valid
    Z-score, SNR threshold, or transference correction can be applied.

    Parameters
    ----------
    df : pd.DataFrame – loaded CSV
    patient_id : str – for error report labelling

    Returns
    -------
    dict with keys: status ('PASS' or 'HALT'), missing_fields,
                    error_report (None on PASS)
    """
    missing = [f for f in REQUIRED_CSV_FIELDS if f not in df.columns]
    null_electrode = (
        'electrode_type' in df.columns and
        df['electrode_type'].isna().any()
    )

    if missing or null_electrode:
        missing_full = list(set(missing + (['electrode_type'] if null_electrode else [])))
        error_report = {
            'status'        : 'HALT',
            'patient_id'    : patient_id,
            'timestamp'     : datetime.datetime.now().isoformat(),
            'missing_fields': missing_full,
            'error_message' : (
                f'Required field(s) {missing_full} are absent or null. '
                f'No processing has been attempted. '
                f'Valid electrode_type values: '
                f'{list(SNR_THRESHOLDS.keys())}. '
                f'Resubmit with all required fields populated.'),
            'layer1_report' : 'ERROR — see error_message',
            'layer2_report' : None,
            'layer3_report' : None,
            'layer4_audit'  : None,
        }
        return {'status': 'HALT', 'missing_fields': missing_full,
                'error_report': error_report}

    return {'status': 'PASS', 'missing_fields': [], 'error_report': None}


# ══════════════════════════════════════════════════════════════════════════════
# 3. Signal quality assessment
# ══════════════════════════════════════════════════════════════════════════════

def assess_signal_quality(snr_db: float,
                           electrode_type: str) -> dict:
    """Assess signal quality and return pipeline state (PASS / WARNING / HALT).

    In WARNING mode: pipeline continues with SHAP suppressed and mandatory
    caveats on all report layers. The Traffic Light badge is shown in grey.

    Parameters
    ----------
    snr_db : float – SNR in dB (Chapter 2 §2.4)
    electrode_type : str

    Returns
    -------
    dict with keys: state ('PASS'/'WARNING'/'FAIL'), snr_db, thresholds,
                    shap_suppressed, caveats
    """
    thresholds = SNR_THRESHOLDS.get(electrode_type.lower(), SNR_THRESHOLDS['dtl_fiber'])
    pass_thr   = thresholds['pass']
    warn_thr   = thresholds['warn']

    if snr_db >= pass_thr:
        state     = 'PASS'
        caveats   = []
        suppress  = False
    elif snr_db >= warn_thr:
        state     = 'WARNING'
        suppress  = True
        caveats   = [
            'SIGNAL_QUALITY_WARNING: recording SNR is below the PASS threshold.',
            'Classification result is provided for reference only.',
            'SHAP attribution suppressed (unreliable on low-SNR signals).',
            'Repeat recording with improved electrode contact is recommended.',
        ]
    else:
        state     = 'FAIL'
        suppress  = True
        caveats   = [
            'SIGNAL_QUALITY_FAIL: recording SNR is below the minimum acceptable threshold.',
            'Classification result is NOT clinically reliable.',
            'Do not use for clinical decision-making. Repeat recording required.',
        ]

    return {
        'state'          : state,
        'snr_db'         : round(snr_db, 2),
        'thresholds'     : thresholds,
        'shap_suppressed': suppress,
        'caveats'        : caveats,
    }


# ══════════════════════════════════════════════════════════════════════════════
# 4. Traffic Light zone assignment
# ══════════════════════════════════════════════════════════════════════════════

def assign_traffic_light(z_score: float,
                          tl_green: float = TL_GREEN,
                          tl_amber: float = TL_AMBER) -> str:
    """Assign a Traffic Light zone from a Z-score (Chapter 10 Equation 10.2)."""
    abs_z = abs(z_score)
    if abs_z <= tl_green:
        return 'GREEN'
    elif abs_z <= tl_amber:
        return 'AMBER'
    return 'RED'


def composite_traffic_light(tl_list: list) -> str:
    """Return the most severe Traffic Light zone across all parameters."""
    if 'RED'   in tl_list: return 'RED'
    if 'AMBER' in tl_list: return 'AMBER'
    return 'GREEN'


# ══════════════════════════════════════════════════════════════════════════════
# 5. Layer report assembler
# ══════════════════════════════════════════════════════════════════════════════

def assemble_report(patient_id:      str,
                    case_params:     dict,
                    z_scores:        dict,
                    stage2_proba:    Optional[float],
                    disease_class:   str,
                    quality_result:  dict,
                    shap_summary:    Optional[dict],
                    config:          ERGAPIConfig,
                    version_stamp:   Optional[dict] = None,
                    longitudinal:    Optional[dict] = None) -> dict:
    """Assemble the four-layer clinical report for one recording.

    Parameters
    ----------
    patient_id : str
    case_params : dict – ERG parameter values
    z_scores : dict – {parameter: {'z': float, 'tl': str}}
    stage2_proba : float or None – calibrated top-class probability
    disease_class : str – predicted class label
    quality_result : dict – from assess_signal_quality()
    shap_summary : dict or None – top SHAP contributors (None if suppressed)
    config : ERGAPIConfig
    version_stamp : dict or None
    longitudinal : dict or None – progression summary from Chapter 18

    Returns
    -------
    dict with keys: layer1, layer2, layer3, layer4
    """
    tl_list    = [v['tl'] for v in z_scores.values()]
    composite  = composite_traffic_light(tl_list)
    timestamp  = datetime.datetime.now().isoformat()

    # Layer 1 — Traffic Light badge
    layer1 = {
        'traffic_light'     : composite,
        'patient_id'        : patient_id,
        'timestamp'         : timestamp,
        'quality_state'     : quality_result['state'],
        'badge_colour'      : (composite if quality_result['state'] == 'PASS'
                               else 'GREY'),
        'badge_label'       : (composite if quality_result['state'] == 'PASS'
                               else 'RESULT UNRELIABLE'),
    }

    # Layer 2 — Clinical summary
    conf_note = ''
    if stage2_proba is not None and stage2_proba < 0.60:
        conf_note = (
            f' This is a low-confidence classification '
            f'(probability {stage2_proba:.0%}). Clinical correlation recommended.')
    layer2 = {
        'predicted_class'  : disease_class,
        'stage2_probability': stage2_proba,
        'z_score_summary'  : {p: v['tl'] for p, v in z_scores.items()},
        'composite_tl'     : composite,
        'quality_caveats'  : quality_result['caveats'],
        'confidence_note'  : conf_note,
    }

    # Layer 3 — Specialist Report
    layer3 = {
        'per_parameter_z'  : z_scores,
        'shap_attribution' : shap_summary if not quality_result['shap_suppressed']
                             else {'suppressed': True,
                                   'reason': 'SIGNAL_QUALITY_WARNING'},
        'longitudinal'     : longitudinal,
        'clinical_notes'   : case_params.get('notes', ''),
    }

    # Layer 4 — Audit JSON
    layer4 = {
        'patient_id'      : patient_id,
        'timestamp'       : timestamp,
        'api_version'     : config.api_version,
        'version_stamp'   : version_stamp,
        'config_snapshot' : config.to_dict(),
        'raw_z_scores'    : {p: round(v['z'], 3) for p, v in z_scores.items()},
        'composite_tl'    : composite,
        'quality_result'  : quality_result,
        'case_params'     : {k: v for k, v in case_params.items()
                             if isinstance(v, (int, float, str, bool))},
    }

    return {'layer1': layer1, 'layer2': layer2,
            'layer3': layer3, 'layer4': layer4}


# ══════════════════════════════════════════════════════════════════════════════
# 6. Single-visit pipeline runner
# ══════════════════════════════════════════════════════════════════════════════

def run_single_visit_pipeline(case_params: dict,
                               norm_stats:  dict,
                               config:      ERGAPIConfig) -> dict:
    """Run the complete 8-stage single-visit pipeline for one case.

    Uses synthetic Z-scores derived from the case parameters and normative
    statistics rather than calling the full Chapter 9–15 stack, making this
    a self-contained integration test that runs without real patient data.

    Parameters
    ----------
    case_params : dict – one entry from CASE_STUDIES
    norm_stats : dict – {parameter: {'mu': float, 'sigma': float}}
    config : ERGAPIConfig

    Returns
    -------
    dict with status, report (four layers), quality_result
    """
    os.makedirs(config.output_dir, exist_ok=True)
    pid       = case_params['patient_id']
    electrode = case_params.get('electrode', case_params.get('electrode_A', 'dtl_fiber'))

    # Stage 1 – schema check (simulated for synthetic data)
    if electrode is None:
        error = validate_csv_schema(pd.DataFrame(), patient_id=pid)
        return {'status': 'HALT', 'report': error['error_report'],
                'quality_result': None}

    # Stage 2–3 – signal quality
    snr  = case_params.get('snr_db', case_params.get('snr_db_A', 5.0))
    if snr is None:
        snr = 0.0
    qual = assess_signal_quality(snr, electrode)

    # Stage 4 – Z-scores from synthetic case parameters
    z_scores = {}
    for param, stats in norm_stats.items():
        val = case_params.get(param)
        if val is None:
            continue
        z = (val - stats['mu']) / (stats['sigma'] + 1e-8)
        z_scores[param] = {'z': round(z, 3), 'tl': assign_traffic_light(z)}

    # Stage 5 – missing data handled by NaN fill (already handled by case_params)

    # Stage 6 – classification (use provided proba or derive from composite TL)
    stage2_proba = case_params.get('stage2_proba')
    if stage2_proba is None:
        comp = composite_traffic_light([v['tl'] for v in z_scores.values()])
        stage2_proba = {'GREEN': 0.88, 'AMBER': 0.72, 'RED': 0.91}[comp]

    disease_class = case_params['disease_class']

    # Stage 7 – SHAP (synthetic summary)
    if not qual['shap_suppressed'] and z_scores:
        top_feat  = sorted(z_scores.items(), key=lambda x: abs(x[1]['z']),
                           reverse=True)[:3]
        shap_summary = {
            f: {'shap': round(v['z'] * 0.08, 3), 'tl': v['tl']}
            for f, v in top_feat
        }
    else:
        shap_summary = None

    # Stage 8 – report assembly
    report = assemble_report(
        patient_id    = pid,
        case_params   = case_params,
        z_scores      = z_scores,
        stage2_proba  = stage2_proba,
        disease_class = disease_class,
        quality_result= qual,
        shap_summary  = shap_summary,
        config        = config,
    )

    return {'status': qual['state'], 'report': report, 'quality_result': qual}


# ══════════════════════════════════════════════════════════════════════════════
# 7. Case Study Runner
# ══════════════════════════════════════════════════════════════════════════════

class CaseStudyRunner:
    """Runs all 9 case studies and saves outputs to JSON and a summary figure.

    Parameters
    ----------
    config : ERGAPIConfig
    norm_stats : dict – {parameter: {'mu': float, 'sigma': float}}
                 Synthetic normative statistics for Z-score calculation.
    """

    def __init__(self, config: ERGAPIConfig, norm_stats: dict):
        self.config     = config
        self.norm_stats = norm_stats
        self.results    = {}

    def run_all(self) -> dict:
        """Run all case studies and return results dict."""
        print('Running 9 case studies...\n')
        for name, params in CASE_STUDIES.items():
            print(f'── {name} ──')
            if name == 'CS09_DataQuality':
                self._run_cs09(name, params)
            else:
                result = run_single_visit_pipeline(
                    params, self.norm_stats, self.config)
                self.results[name] = result
                l1 = result['report']['layer1']
                print(f'  Patient : {params["patient_id"]}')
                print(f'  Status  : {result["status"]}')
                print(f'  TL badge: {l1["badge_colour"]} '
                      f'({l1.get("traffic_light", "ERROR")})')
                print(f'  Disease : {params["disease_class"]}')
                if result['report']['layer2'].get('confidence_note'):
                    print(f'  ⚠ {result["report"]["layer2"]["confidence_note"][:80]}')
            print()
        return self.results

    def _run_cs09(self, name: str, params: dict):
        """Case Study 9: two-scenario data quality failure."""
        print('  Scenario A: SIGNAL_QUALITY_WARNING')
        cs09a        = dict(params)
        cs09a['electrode'] = params.get('electrode_A', 'skin')
        cs09a['snr_db']    = params.get('snr_db_A', 2.1)
        res_a = run_single_visit_pipeline(cs09a, self.norm_stats, self.config)
        print(f'    Status : {res_a["status"]}')
        print(f'    SHAP   : {"SUPPRESSED" if res_a["quality_result"]["shap_suppressed"] else "SHOWN"}')
        print(f'    Caveats: {len(res_a["quality_result"]["caveats"])} mandatory caveats')

        print('  Scenario B: ELECTRODE_UNKNOWN (HALT)')
        cs09b        = dict(params)
        cs09b['electrode'] = params.get('electrode_B')   # None → HALT
        cs09b['snr_db']    = params.get('snr_db_B', 5.0)
        res_b = run_single_visit_pipeline(cs09b, self.norm_stats, self.config)
        print(f'    Status : {res_b["status"]}')
        if res_b['status'] == 'HALT':
            print(f'    Error  : {res_b["report"]["error_message"][:80]}...')

        self.results[name] = {'scenario_A': res_a, 'scenario_B': res_b}

    def save_results(self, path: str = None):
        """Save all results to JSON."""
        out = path or os.path.join(self.config.output_dir, 'case_study_results.json')
        os.makedirs(os.path.dirname(out), exist_ok=True)

        # Serialise (convert non-serialisable types)
        def make_serial(obj):
            if isinstance(obj, dict): return {k: make_serial(v) for k, v in obj.items()}
            if isinstance(obj, list): return [make_serial(v) for v in obj]
            if isinstance(obj, np.integer): return int(obj)
            if isinstance(obj, np.floating): return float(obj)
            return obj

        with open(out, 'w') as f:
            json.dump(make_serial(self.results), f, indent=2)
        print(f'Results saved: {out}')

    def plot_summary(self) -> plt.Figure:
        """Plot a Traffic Light summary grid for all case studies."""
        tl_colour = {'GREEN': '#2E7D32', 'AMBER': '#F9A825',
                     'RED': '#C62828',   'GREY': '#9E9E9E',
                     'ERROR': '#3E3E3E'}

        cases   = [k for k in self.results if k != 'CS09_DataQuality']
        labels  = [CASE_STUDIES[c]['disease_class'][:28] for c in cases]
        colours = []
        for c in cases:
            r = self.results[c]
            if r['status'] == 'HALT':
                colours.append('ERROR')
            else:
                colours.append(r['report']['layer1']['badge_colour'])

        # CS09 — two scenarios
        labels  += ['Data Quality\n(Warning)', 'Data Quality\n(Halt)']
        colours += ['GREY', 'ERROR']

        n   = len(labels)
        fig, axes = plt.subplots(2, 5, figsize=(15, 6))
        axes_flat = axes.flatten()

        for i, (lbl, col) in enumerate(zip(labels, colours)):
            ax = axes_flat[i]
            ax.add_patch(mpatches.FancyBboxPatch(
                (0.1, 0.2), 0.8, 0.6, boxstyle='round,pad=0.05',
                facecolor=tl_colour.get(col, '#9E9E9E'),
                edgecolor='white', linewidth=2))
            ax.text(0.5, 0.5, col, ha='center', va='center',
                    fontsize=11, fontweight='bold', color='white',
                    transform=ax.transAxes)
            ax.set_title(lbl, fontsize=8, pad=4)
            ax.set_xlim(0, 1); ax.set_ylim(0, 1)
            ax.axis('off')

        # Hide unused panel (10th cell)
        axes_flat[-1].axis('off')

        fig.suptitle('Chapter 19 – Case Study Traffic Light Summary\n'
                     '(Cases 1–9: all eight ERG classification outcomes + data quality)',
                     fontsize=12, fontweight='bold')
        plt.tight_layout()
        save_path = os.path.join(self.config.output_dir,
                                 'ch19_case_study_summary.png')
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f'Saved: {save_path}')
        return fig


# ══════════════════════════════════════════════════════════════════════════════
# Smoke test / demonstration walkthrough (§19.11)
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':

    config = ERGAPIConfig(output_dir='outputs/api')
    os.makedirs(config.output_dir, exist_ok=True)

    # Synthetic normative stats (stand-in for Robson et al. 2025)
    norm_stats = {
        'b_amp_uv'      : {'mu': 180.0, 'sigma': 35.0},
        'b_implicit_ms' : {'mu':  52.0, 'sigma':  4.0},
        'a_amp_uv'      : {'mu':  95.0, 'sigma': 20.0},
        'phnr_amp_uv'   : {'mu':  28.0, 'sigma':  7.0},
        'op2_amp_uv'    : {'mu':  22.0, 'sigma':  5.5},
        'op2_implicit_ms': {'mu':  29.0, 'sigma':  2.5},
        'la30_amp_uv'   : {'mu': 120.0, 'sigma': 25.0},
        'ba_ratio'      : {'mu':   2.2, 'sigma':  0.6},
    }

    # ── Run all case studies ──────────────────────────────────────────────
    runner = CaseStudyRunner(config, norm_stats)
    results = runner.run_all()
    runner.save_results()
    fig = runner.plot_summary()
    plt.show()

    # ── Demonstration walkthrough: Case Study 2 (§19.11) ─────────────────
    print('\n' + '='*60)
    print('DEMONSTRATION WALKTHROUGH: Case Study 2 — Early DR')
    print('='*60)
    cs2 = results['CS02_EarlyDR']
    l1  = cs2['report']['layer1']
    l2  = cs2['report']['layer2']
    l3  = cs2['report']['layer3']

    print(f'\nLayer 1 — Traffic Light : {l1["badge_colour"]} ({l1["traffic_light"]})')
    print(f'\nLayer 2 — Classification : {l2["predicted_class"]}')
    print(f'          Probability    : {l2["stage2_probability"]:.0%}')
    print(f'          Z-score summary: {l2["z_score_summary"]}')

    if l3['shap_attribution'] and 'suppressed' not in l3['shap_attribution']:
        print(f'\nLayer 3 — Top SHAP contributors:')
        for feat, vals in l3['shap_attribution'].items():
            print(f'  {feat:<22s} SHAP={vals["shap"]:+.3f}  ({vals["tl"]})')
    else:
        print('\nLayer 3 — SHAP: SUPPRESSED (signal quality warning)')

    print(f'\nLayer 4 — API version : {cs2["report"]["layer4"]["api_version"]}')
    print(f'          Composite TL  : {cs2["report"]["layer4"]["composite_tl"]}')
    print('\nDemonstration complete.')