# -*- coding: utf-8 -*-
"""Chapter_13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upfHw7KYEwrYyRHEQzT3Xadt44kl5GdG
"""

# -*- coding: utf-8 -*-
"""
chapter_13_deep_learning_vit.py
=================================
Hands-On Electroretinography in the Age of AI
Chapter 13 – Deep Learning: Vision Transformer for ERG Classification

Implements the complete deep learning pipeline:

  DATA AUGMENTATION (ERG-specific, §13.3)
    ERGSpectrogramAugment   – Time masking, frequency masking, Gaussian noise,
                              brightness jitter (horizontal flip explicitly excluded)

  MODEL CONSTRUCTION (§13.2)
    build_vit_stage1        – ViT Small, 2-class binary (Normal vs Abnormal)
    build_vit_stage2        – ViT Small, 6-class disease classifier
    build_comparison_model  – DenseNet121 / ResNet50 / VGG16 for arch comparison

  TRAINING (§13.3)
    train_vit               – AdamW + CosineAnnealingLR + early stopping
                              Differential LRs: backbone 1e-5, head 1e-4
                              Gradient clipping max_norm=1.0

  TWO-STAGE CASCADE (§13.5)
    CascadeClassifier       – Stage 1 triage → Stage 2 disease classification
                              Joint confidence = p(abnormal) × p(disease|abnormal)
                              Stage 1 threshold tuned to sensitivity ≥ 0.95

  SYNTHETIC DATA VALIDATION (§13.6)
    compute_fid             – Fréchet Inception Distance (FID < 50 threshold)

Performance baselines (Albasu et al., 2024 — point estimates):
  ViT Small    macro-AUC 0.888  (Stage 2 multi-class)
  Stage 1      AUC ≥ 0.94       (binary Normal vs Abnormal)
  DenseNet121  macro-AUC 0.851
  ResNet50     macro-AUC 0.823
  VGG16        macro-AUC 0.811

Ethical constraint (§13.6.3): synthetic data TRAINING only.
  Validation and test sets must contain ZERO synthetic examples.
  All synthetic examples are tagged synthetic=True in metadata.

Repository : https://github.com/AI-Fairness-com/ERG-Analysis-API
Author     : Hamid
Licence    : See repo root LICENSE
"""

# ── Dependencies ───────────────────────────────────────────────────────────────
# Run once in your Colab session (GPU recommended):
#   !pip install torch torchvision timm pytorch-fid -q

import os
import json
import numpy as np
import torch
import torch.nn as nn
import timm
from torch.optim               import AdamW
from torch.optim.lr_scheduler  import CosineAnnealingLR
from torch.utils.data          import DataLoader, TensorDataset
import matplotlib.pyplot as plt

# ── Locked project constants ───────────────────────────────────────────────────
VIT_MODEL_NAME  = 'vit_small_r26_s32_224'   # ViT Small – primary production model
IMG_SIZE        = 224                         # input resolution (pixels)
N_STAGE1_CLASSES = 2                         # Normal vs Abnormal
N_STAGE2_CLASSES = 6                         # six disease classes
STAGE1_SENS_MIN  = 0.95                      # minimum Stage 1 sensitivity threshold
FID_THRESHOLD    = 50.0                      # max FID for synthetic data admission
PATIENCE         = 10                        # early stopping patience (epochs)
NUM_EPOCHS       = 50                        # maximum training epochs
BATCH_SIZE       = 32
BACKBONE_LR      = 1e-5                      # differential LR: backbone
HEAD_LR          = 1e-4                      # differential LR: classification head
WEIGHT_DECAY     = 1e-2
GRAD_CLIP        = 1.0                       # gradient clipping max_norm

# ImageNet normalisation constants (required for timm pretrained weights)
IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD  = (0.229, 0.224, 0.225)

DISEASE_CLASSES = [
    'Diabetic Retinopathy (early)',
    'Glaucoma (early)',
    'Retinitis Pigmentosa / Rod Dystrophy',
    'Age-Related Macular Degeneration',
    'Cone Dystrophy',
    'Complete CSNB',
]

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'


# ══════════════════════════════════════════════════════════════════════════════
# 1. ERG-specific data augmentation
# ══════════════════════════════════════════════════════════════════════════════

class ERGSpectrogramAugment:
    """Apply ERG-validated augmentations to a 224×224 spectrogram tensor.

    Four augmentation types are applied stochastically during training (§13.3):
      1. Time masking    – zeros a random contiguous band of time columns
      2. Frequency masking – zeros a random contiguous band of frequency rows
      3. Gaussian noise  – additive noise to simulate recording noise floor
      4. Brightness jitter – multiplicative intensity scaling

    ⚠️  Geometric augmentations (horizontal flip, vertical flip, rotation) are
    explicitly PROHIBITED for ERG spectrograms. Flipping the time axis reverses
    stimulus onset; flipping the frequency axis inverts the OP/b-wave band
    relationship. Both destroy the physiological meaning of the image.

    Parameters
    ----------
    time_mask_max : int
        Maximum width of the time mask in pixels (default 20 = ~4.5 % of 224).
    freq_mask_max : int
        Maximum height of the frequency mask in pixels (default 20).
    noise_std : float
        Standard deviation of additive Gaussian noise (default 0.05).
    brightness_range : tuple
        (min, max) multiplicative brightness jitter (default 0.9–1.1).
    p : float
        Probability of applying each augmentation independently (default 0.5).
    """

    def __init__(self,
                 time_mask_max:    int   = 20,
                 freq_mask_max:    int   = 20,
                 noise_std:        float = 0.05,
                 brightness_range: tuple = (0.9, 1.1),
                 p:                float = 0.5):
        self.time_mask_max    = time_mask_max
        self.freq_mask_max    = freq_mask_max
        self.noise_std        = noise_std
        self.brightness_range = brightness_range
        self.p                = p

    def __call__(self, x: torch.Tensor) -> torch.Tensor:
        """Augment a single spectrogram tensor.

        Parameters
        ----------
        x : torch.Tensor, shape (C, H, W) or (H, W)

        Returns
        -------
        torch.Tensor, same shape as input.
        """
        x = x.clone()
        rng = np.random.default_rng()

        # Time masking: zero a random time-axis band
        if rng.random() < self.p:
            w    = rng.integers(1, self.time_mask_max + 1)
            t0   = rng.integers(0, max(1, x.shape[-1] - w))
            x[..., t0: t0 + w] = 0.0

        # Frequency masking: zero a random frequency-axis band
        if rng.random() < self.p:
            h    = rng.integers(1, self.freq_mask_max + 1)
            f0   = rng.integers(0, max(1, x.shape[-2] - h))
            x[..., f0: f0 + h, :] = 0.0

        # Gaussian noise
        if rng.random() < self.p:
            x = x + torch.randn_like(x) * self.noise_std

        # Brightness jitter (multiplicative)
        if rng.random() < self.p:
            lo, hi = self.brightness_range
            scale  = lo + rng.random() * (hi - lo)
            x      = x * scale

        return x.clamp(0.0, 1.0)


# ══════════════════════════════════════════════════════════════════════════════
# 2. Model construction
# ══════════════════════════════════════════════════════════════════════════════

def build_vit_stage1(pretrained: bool = True) -> nn.Module:
    """Build the Stage 1 binary ViT Small (Normal vs Abnormal).

    Architecture: vit_small_r26_s32_224
      - 22 M parameters, 8 attention heads, 8 encoder blocks, embedding dim 384
      - Pre-trained on ImageNet-21k (14 M images, 21,843 classes)
      - Classification head replaced with 2-output linear layer

    Parameters
    ----------
    pretrained : bool
        Load ImageNet-21k weights (True for fine-tuning; False for ablation).

    Returns
    -------
    nn.Module ready to move to device with .to(DEVICE).
    """
    model = timm.create_model(
        VIT_MODEL_NAME,
        pretrained  = pretrained,
        num_classes = N_STAGE1_CLASSES,
    )
    return model


def build_vit_stage2(pretrained: bool = True) -> nn.Module:
    """Build the Stage 2 six-class disease ViT Small.

    Same architecture as Stage 1 with a 6-output classification head.
    Receives only recordings classified as Abnormal by Stage 1.
    """
    model = timm.create_model(
        VIT_MODEL_NAME,
        pretrained  = pretrained,
        num_classes = N_STAGE2_CLASSES,
    )
    return model


def build_comparison_model(arch:        str  = 'densenet121',
                            num_classes: int  = N_STAGE2_CLASSES,
                            pretrained:  bool = True) -> nn.Module:
    """Build a comparison CNN architecture (DenseNet121 / ResNet50 / VGG16).

    Architecture AUC baselines (Albasu et al., 2024):
      densenet121 → 0.851
      resnet50    → 0.823
      vgg16       → 0.811

    Parameters
    ----------
    arch : str
        One of 'densenet121', 'resnet50', 'vgg16', 'vgg19'.
    num_classes : int
    pretrained : bool

    Returns
    -------
    nn.Module
    """
    supported = ('densenet121', 'resnet50', 'vgg16', 'vgg19')
    if arch not in supported:
        raise ValueError(f'arch must be one of {supported}; got {arch!r}')
    model = timm.create_model(arch, pretrained=pretrained,
                               num_classes=num_classes)
    return model


# ══════════════════════════════════════════════════════════════════════════════
# 3. Training loop
# ══════════════════════════════════════════════════════════════════════════════

def train_vit(model:        nn.Module,
              train_loader: DataLoader,
              val_loader:   DataLoader,
              class_weights: torch.Tensor = None,
              num_epochs:   int   = NUM_EPOCHS,
              patience:     int   = PATIENCE,
              save_path:    str   = 'models/vit_best.pt',
              config:       dict  = None) -> dict:
    """Fine-tune ViT Small with differential learning rates and early stopping.

    Training configuration (§13.3):
      Optimiser     : AdamW (weight_decay=1e-2)
      LR schedule   : CosineAnnealingLR (T_max=num_epochs, eta_min=1e-7)
      Differential LR: backbone 1e-5  (10× lower than head — §13.3.2)
                        head    1e-4
      Loss          : CrossEntropyLoss with optional class_weights
      Gradient clip : max_norm=1.0 (prevents large updates in early epochs)
      Early stopping: patience=10 on validation loss

    Parameters
    ----------
    model : nn.Module (output of build_vit_stage1 or build_vit_stage2)
    train_loader, val_loader : DataLoader yielding (images, labels) batches
    class_weights : torch.Tensor, shape (n_classes,) or None
    num_epochs : int
    patience : int
    save_path : str  path for best model checkpoint
    config : dict  config-API dict; training metadata written here if provided

    Returns
    -------
    dict with keys: train_losses, val_losses, best_epoch, best_val_loss
    """
    os.makedirs(os.path.dirname(save_path) if os.path.dirname(save_path)
                else '.', exist_ok=True)

    model = model.to(DEVICE)

    # Differential learning rates
    backbone_params = [p for n, p in model.named_parameters()
                       if 'head' not in n]
    head_params     = [p for n, p in model.named_parameters()
                       if 'head'     in n]
    optimizer = AdamW([
        {'params': backbone_params, 'lr': BACKBONE_LR},
        {'params': head_params,     'lr': HEAD_LR},
    ], weight_decay=WEIGHT_DECAY)

    scheduler = CosineAnnealingLR(optimizer, T_max=num_epochs, eta_min=1e-7)
    criterion = nn.CrossEntropyLoss(
        weight=class_weights.to(DEVICE) if class_weights is not None else None)

    best_val_loss  = float('inf')
    patience_count = 0
    best_epoch     = 0
    train_losses, val_losses = [], []

    for epoch in range(num_epochs):
        # ── Training ───────────────────────────────────────────────────────
        model.train()
        train_loss = 0.0
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(DEVICE), y_batch.to(DEVICE)
            optimizer.zero_grad()
            logits = model(X_batch)
            loss   = criterion(logits, y_batch)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(),
                                           max_norm=GRAD_CLIP)
            optimizer.step()
            train_loss += loss.item()

        # ── Validation ─────────────────────────────────────────────────────
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for X_val, y_val in val_loader:
                logits    = model(X_val.to(DEVICE))
                val_loss += criterion(logits, y_val.to(DEVICE)).item()

        scheduler.step()
        train_losses.append(train_loss / len(train_loader))
        val_losses.append(val_loss   / len(val_loader))

        print(f'Epoch {epoch:3d}  '
              f'train={train_losses[-1]:.4f}  '
              f'val={val_losses[-1]:.4f}  '
              f'patience={patience_count}/{patience}')

        # ── Early stopping ─────────────────────────────────────────────────
        if val_loss < best_val_loss:
            best_val_loss  = val_loss
            best_epoch     = epoch
            patience_count = 0
            torch.save(model.state_dict(), save_path)
        else:
            patience_count += 1
            if patience_count >= patience:
                print(f'Early stopping at epoch {epoch}.')
                break

    # Record training metadata in config-API dict
    if config is not None:
        key = os.path.basename(save_path).replace('.pt', '')
        config[key] = {
            'model_path'  : save_path,
            'best_epoch'  : best_epoch,
            'best_val_loss': round(best_val_loss, 6),
            'num_epochs'  : epoch + 1,
        }

    return {
        'train_losses' : train_losses,
        'val_losses'   : val_losses,
        'best_epoch'   : best_epoch,
        'best_val_loss': best_val_loss,
    }


# ══════════════════════════════════════════════════════════════════════════════
# 4. Two-stage cascade classifier
# ══════════════════════════════════════════════════════════════════════════════

class CascadeClassifier:
    """Two-stage cascade classifier for ERG spectrogram disease classification.

    Stage 1: Binary ViT Small (Normal vs Abnormal).
             Decision threshold set to achieve Stage 1 sensitivity ≥ 0.95.
             If Stage 1 probability(Abnormal) ≥ threshold: forward to Stage 2.
             If Stage 1 probability(Normal)   > threshold complement: Green TL.

    Stage 2: Six-class ViT Small (disease classification).
             Receives only recordings flagged as Abnormal by Stage 1.
             Output: probability vector over 6 disease classes.

    Joint confidence = p(Abnormal) × p(disease class | Abnormal).
    Top-3 disease classes by probability are reported in the Layer 2 summary.

    Parameters
    ----------
    stage1_path : str  path to Stage 1 .pt weights file
    stage2_path : str  path to Stage 2 .pt weights file
    stage1_threshold : float  abnormal decision threshold (default 0.5;
                               tune from ROC curve for sensitivity ≥ 0.95)
    """

    def __init__(self,
                 stage1_path:      str,
                 stage2_path:      str,
                 stage1_threshold: float = 0.5):
        self.stage1 = build_vit_stage1(pretrained=False)
        self.stage1.load_state_dict(
            torch.load(stage1_path, map_location=DEVICE))
        self.stage1 = self.stage1.to(DEVICE).eval()

        self.stage2 = build_vit_stage2(pretrained=False)
        self.stage2.load_state_dict(
            torch.load(stage2_path, map_location=DEVICE))
        self.stage2 = self.stage2.to(DEVICE).eval()

        self.threshold = stage1_threshold

    @torch.no_grad()
    def predict(self, images: torch.Tensor) -> list:
        """Run the cascade on a batch of 224×224 spectrogram tensors.

        Parameters
        ----------
        images : torch.Tensor, shape (B, C, H, W)

        Returns
        -------
        list of dicts, one per recording, with keys:
          stage1_label      – 'Normal' or 'Abnormal'
          stage1_prob_abnormal – float
          stage2_probs      – np.ndarray (6,) or None if stage1=Normal
          top3_classes      – list of (class_name, joint_confidence) or None
          joint_confidence  – float (p_abnormal × p_top_class) or None
          traffic_light_input – float confidence for Traffic Light assignment
        """
        images = images.to(DEVICE)
        s1_logits = self.stage1(images)
        s1_probs  = torch.softmax(s1_logits, dim=1).cpu().numpy()
        # Convention: class 0 = Normal, class 1 = Abnormal
        p_abnormal = s1_probs[:, 1]

        results = []
        for i, pa in enumerate(p_abnormal):
            if pa < self.threshold:
                results.append({
                    'stage1_label'         : 'Normal',
                    'stage1_prob_abnormal' : float(pa),
                    'stage2_probs'         : None,
                    'top3_classes'         : None,
                    'joint_confidence'     : float(1 - pa),
                    'traffic_light_input'  : float(1 - pa),
                })
            else:
                img_i    = images[i].unsqueeze(0)
                s2_logits = self.stage2(img_i)
                s2_probs  = torch.softmax(s2_logits, dim=1).cpu().numpy()[0]
                joint     = pa * s2_probs
                top3_idx  = np.argsort(joint)[::-1][:3]
                top3      = [(DISEASE_CLASSES[j], float(joint[j]))
                             for j in top3_idx]
                results.append({
                    'stage1_label'         : 'Abnormal',
                    'stage1_prob_abnormal' : float(pa),
                    'stage2_probs'         : s2_probs,
                    'top3_classes'         : top3,
                    'joint_confidence'     : float(joint[top3_idx[0]]),
                    'traffic_light_input'  : float(pa),
                })
        return results

    def tune_threshold(self,
                       images:    torch.Tensor,
                       y_binary:  np.ndarray,
                       min_sens:  float = STAGE1_SENS_MIN) -> float:
        """Set Stage 1 threshold to achieve minimum sensitivity on a held-out set.

        Scans thresholds from 0.01 to 0.99 in steps of 0.01. Selects the
        highest threshold (most specific) that achieves sensitivity ≥ min_sens
        for the Abnormal class. Returns the selected threshold and updates
        self.threshold.

        Parameters
        ----------
        images : torch.Tensor, shape (N, C, H, W) – validation set images
        y_binary : np.ndarray, shape (N,) – binary labels (0=Normal, 1=Abnormal)
        min_sens : float – minimum required sensitivity (default 0.95)

        Returns
        -------
        float – selected threshold
        """
        with torch.no_grad():
            s1_logits = self.stage1(images.to(DEVICE))
            p_abn     = torch.softmax(s1_logits, dim=1)[:, 1].cpu().numpy()

        best_thr  = 0.5
        for thr in np.arange(0.99, 0.00, -0.01):
            preds     = (p_abn >= thr).astype(int)
            tp        = ((preds == 1) & (y_binary == 1)).sum()
            fn        = ((preds == 0) & (y_binary == 1)).sum()
            sens      = tp / (tp + fn) if (tp + fn) > 0 else 0.0
            if sens >= min_sens:
                best_thr = float(thr)
                break

        print(f'Stage 1 threshold tuned: {best_thr:.2f} '
              f'(sensitivity ≥ {min_sens:.2f})')
        self.threshold = best_thr
        return best_thr


# ══════════════════════════════════════════════════════════════════════════════
# 5. Synthetic data quality validation
# ══════════════════════════════════════════════════════════════════════════════

def compute_fid(real_image_dir: str,
                fake_image_dir: str,
                device:         str = DEVICE) -> float:
    """Compute Fréchet Inception Distance between real and synthetic spectrograms.

    FID < 50 is the admission threshold for synthetic data to the training set
    (§13.6.2). FID ≥ 50 requires retraining the GAN before any synthetic
    examples are used.

    Requires:  pip install pytorch-fid

    Parameters
    ----------
    real_image_dir : str  directory of real spectrogram PNG/JPEG images
    fake_image_dir : str  directory of synthetic spectrogram PNG/JPEG images
    device : str  'cuda' or 'cpu'

    Returns
    -------
    float  FID score
    """
    try:
        from pytorch_fid import fid_score
    except ImportError:
        raise ImportError('pytorch-fid is required: pip install pytorch-fid')

    fid    = fid_score.calculate_fid_given_paths(
        [real_image_dir, fake_image_dir],
        batch_size = 32,
        device     = device,
        dims       = 2048,
    )
    status = 'PASS' if fid < FID_THRESHOLD else f'FAIL (threshold {FID_THRESHOLD}) -- retrain GAN'
    print(f'FID = {fid:.2f}  [{status}]')
    return fid


# ══════════════════════════════════════════════════════════════════════════════
# Smoke test  (CPU-safe; GPU not required)
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    print(f'Device: {DEVICE}')

    # ── 1. Data augmentation verification ────────────────────────────────
    print('\n=== Augmentation smoke test ===')
    augment = ERGSpectrogramAugment(p=1.0)  # p=1.0 applies all augmentations
    dummy   = torch.rand(1, IMG_SIZE, IMG_SIZE)  # single-channel spectrogram
    aug_out = augment(dummy)
    print(f'Input  range: [{dummy.min():.3f}, {dummy.max():.3f}]')
    print(f'Output range: [{aug_out.min():.3f}, {aug_out.max():.3f}]  '
          f'(must stay in [0, 1])')
    assert aug_out.min() >= 0.0 and aug_out.max() <= 1.0, \
        'Augmentation produced out-of-range values!'
    print('Augmentation output: OK')

    fig_aug, axes = plt.subplots(1, 2, figsize=(10, 4))
    axes[0].imshow(dummy.squeeze().numpy(), cmap='inferno', origin='lower')
    axes[0].set_title('Original spectrogram', fontsize=11)
    axes[1].imshow(aug_out.squeeze().numpy(), cmap='inferno', origin='lower')
    axes[1].set_title('After augmentation (all four types, p=1.0)', fontsize=11)
    for ax in axes:
        ax.set_xlabel('Time (pixels)'); ax.set_ylabel('Frequency (pixels)')
    plt.tight_layout()
    plt.savefig('ch13_fig1_augmentation.png', dpi=150, bbox_inches='tight')
    print('Saved: ch13_fig1_augmentation.png')

    # ── 2. Model construction and forward pass ────────────────────────────
    print('\n=== Model construction smoke test (no pretrained weights) ===')
    for label, model in [
        ('Stage 1 ViT (2-class)', build_vit_stage1(pretrained=False)),
        ('Stage 2 ViT (6-class)', build_vit_stage2(pretrained=False)),
        ('DenseNet121',           build_comparison_model('densenet121', pretrained=False)),
        ('ResNet50',              build_comparison_model('resnet50',    pretrained=False)),
        ('VGG16',                 build_comparison_model('vgg16',       pretrained=False)),
    ]:
        model  = model.to(DEVICE)
        # 3-channel 224×224 batch of 4
        dummy_batch = torch.rand(4, 3, IMG_SIZE, IMG_SIZE).to(DEVICE)
        with torch.no_grad():
            out = model(dummy_batch)
        n_params = sum(p.numel() for p in model.parameters()) / 1e6
        print(f'  {label:<30s}  output: {tuple(out.shape)}  '
              f'params: {n_params:.1f} M')
        assert out.shape == (4, out.shape[1]), 'Unexpected output shape'

    # ── 3. Mini training loop (1 epoch, synthetic data) ───────────────────
    print('\n=== Mini training loop (1 epoch, CPU, synthetic data) ===')
    N_TRAIN, N_VAL = 32, 16
    X_tr  = torch.rand(N_TRAIN, 3, IMG_SIZE, IMG_SIZE)
    y_tr  = torch.randint(0, N_STAGE2_CLASSES, (N_TRAIN,))
    X_va  = torch.rand(N_VAL,   3, IMG_SIZE, IMG_SIZE)
    y_va  = torch.randint(0, N_STAGE2_CLASSES, (N_VAL,))

    tr_loader = DataLoader(TensorDataset(X_tr, y_tr), batch_size=8, shuffle=True)
    va_loader = DataLoader(TensorDataset(X_va, y_va), batch_size=8)

    mini_model = build_vit_stage2(pretrained=False)
    history    = train_vit(
        mini_model, tr_loader, va_loader,
        num_epochs=2, patience=5,
        save_path='models/ch13_smoke_vit.pt',
    )
    print(f'  train_loss[0] = {history["train_losses"][0]:.4f}')
    print(f'  val_loss[0]   = {history["val_losses"][0]:.4f}')
    print(f'  best_epoch    = {history["best_epoch"]}')

    # ── 4. Training curve plot ────────────────────────────────────────────
    fig_tc, ax_tc = plt.subplots(figsize=(8, 4))
    ax_tc.plot(history['train_losses'], label='Train loss', color='#2E75B6')
    ax_tc.plot(history['val_losses'],   label='Val loss',   color='#C62828')
    ax_tc.axvline(history['best_epoch'], color='green', ls='--', lw=1.0,
                  label=f'Best epoch ({history["best_epoch"]})')
    ax_tc.set_xlabel('Epoch', fontsize=11)
    ax_tc.set_ylabel('CrossEntropy loss', fontsize=11)
    ax_tc.set_title('ViT Small – Training Curve (smoke test, 2 epochs)',
                    fontsize=12, fontweight='bold')
    ax_tc.legend(fontsize=10)
    ax_tc.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig('ch13_fig2_training_curve.png', dpi=150, bbox_inches='tight')
    print('Saved: ch13_fig2_training_curve.png')

    # ── 5. Architecture AUC comparison bar chart ──────────────────────────
    arch_aucs = {
        'ViT Small\n(primary)' : 0.888,
        'DenseNet121'          : 0.851,
        'ResNet50'             : 0.823,
        'VGG16'                : 0.811,
        'RF (classical\nbaseline)': 0.722,
    }
    fig_ac, ax_ac = plt.subplots(figsize=(9, 4))
    colours = ['#2E7D32', '#2E75B6', '#1565C0', '#5C6BC0', '#C62828']
    bars    = ax_ac.bar(arch_aucs.keys(), arch_aucs.values(),
                        color=colours)
    ax_ac.axhline(0.722, color='red', ls='--', lw=1.0,
                  label='RF baseline (Albasu et al., 2024)')
    ax_ac.set_ylim(0.65, 0.95)
    ax_ac.set_ylabel('Macro AUC-ROC', fontsize=11)
    ax_ac.set_title('Architecture Comparison – ERG Spectrogram Classification\n'
                    '(Albasu et al., 2024 – project CIs in Chapter 16)',
                    fontsize=11, fontweight='bold')
    ax_ac.legend(fontsize=9)
    ax_ac.grid(True, axis='y', alpha=0.25)
    for bar, v in zip(bars, arch_aucs.values()):
        ax_ac.text(bar.get_x() + bar.get_width() / 2, v + 0.003,
                   f'{v:.3f}', ha='center', va='bottom', fontsize=8)
    plt.tight_layout()
    plt.savefig('ch13_fig3_arch_comparison.png', dpi=150, bbox_inches='tight')
    print('Saved: ch13_fig3_arch_comparison.png')

    plt.show()
    print('\nSmoke test complete. GPU training: replace pretrained=False with '
          'pretrained=True and run on a Colab GPU runtime.')