# -*- coding: utf-8 -*-
"""Chapter_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T78dzJ2uQJr8x5I9FFI5RdJzIs-_zBqS
"""

# -*- coding: utf-8 -*-
"""
chapter_09_erg_feature_extraction.py
======================================
Hands-On Electroretinography in the Age of AI
Chapter 9 – Feature Extraction and Selection

Implements three feature families and a four-method feature selection pipeline:

TIME-DOMAIN FEATURES
  extract_a_wave                – a-wave amplitude and implicit time (ISCEV)
  extract_b_wave                – b-wave amplitude (trough-to-peak, ISCEV)
  compute_ba_ratio              – b/a amplitude ratio
  extract_phnr                  – PhNR amplitude (LA 3.0 only)
  extract_oscillatory_potentials– OP2, OP3, OP4 amplitudes and OP2 implicit time
  extract_time_domain_features  – Orchestrator: all time-domain features for one recording

NONLINEAR AND TIME-FREQUENCY FEATURES (Section 9.3)
  extract_nonlinear_features           – Hurst Exponent, Approximate Entropy (Nair & Joseph, 2014a)
  extract_dwt_band_energies            – 6 CWT band-energy descriptors (Gauvin, Lina & Lachapelle, 2014)
  extract_bwave_derivative_features    – b-wave ascending/descending inflection time+gradient (Wood, Margrain & Binns, 2014)
  extract_awave_descending_inflection  – a-wave descending inflection time (Wood, Margrain & Binns, 2014)

FREQUENCY-DOMAIN FEATURES (Section 9.4)
  extract_frequency_domain_features    – peak frequency, spectral entropy (all protocols), harmonic ratio (LA 30 Hz only)

COMPLETE SINGLE-RECORDING PIPELINE
  extract_all_features           – All 25-27 features (of 28 defined) for one recording (Section 9.6)

COMPLETE PATIENT PIPELINE
  build_patient_feature_matrix   – extract_all_features() across all protocols x eyes for one patient

FEATURE SELECTION
  rfe_selection                 – Recursive Feature Elimination (RFECV)
  correlation_filter            – Pearson correlation redundancy filter
  mrmr_selection                – Minimum Redundancy Maximum Relevance
  rf_importance_selection       – Random Forest mean decrease in impurity
  feature_selection_pipeline    – Four-method majority-vote selection

Fail-safe design: all extractors return NaN rather than a guessed value when
a waveform component cannot be reliably identified. NaN values are handled
by the missing-value strategy in Chapter 10.

Repository : https://github.com/AI-Fairness-com/ERG-Analysis-API
Author     : Hamid
Licence    : See repo root LICENSE
"""

# ── Dependencies ───────────────────────────────────────────────────────────────
# Run once in your Colab session:
#   !pip install scipy scikit-learn pandas mrmr-selection -q
# mrmr-selection is optional; mrmr_selection() degrades gracefully without it.

import numpy as np
import pandas as pd
from typing import Dict, Any
from collections import Counter
from numpy.lib.stride_tricks import sliding_window_view
from scipy.signal import welch, find_peaks, stft as _stft
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFECV
from sklearn.model_selection import StratifiedKFold
import pywt

# ── Locked constants ───────────────────────────────────────────────────────────
FS_HZ         = 2000.0   # pipeline sampling rate (Chapter 3)
PROTOCOLS     = ('DA 0.01', 'DA 3.0', 'DA 10.0', 'LA 3.0', 'LA 30 Hz')
EYES          = ('RE', 'LE')

# ISCEV 2022 flash-duration constants -- kept separate deliberately:
# ISCEV_FLASH_MAX_DURATION_MS is the absolute ceiling ISCEV allows for any
# stimulus flash. FLASH_MIDPOINT_CORRECTION_THRESHOLD_MS is the (much lower)
# duration above which ISCEV requires implicit time to be measured from the
# flash midpoint rather than flash onset. These answer different questions
# and must not share one constant.
ISCEV_FLASH_MAX_DURATION_MS = 5.0
FLASH_MIDPOINT_CORRECTION_THRESHOLD_MS = 1.0

# (No spectrogram-region or PSD-per-band constants: those features were
# dropped from this pipeline's canonical design -- not part of Chapter 9's
# cited 28-feature set. See docs/CHANGELOG.md, 2026-09-07 entry.)


def extract_a_wave(signal_uv:    np.ndarray,
                   time_ms:      np.ndarray,
                   protocol:     str,
                   hardware_lowpass_hz: float = 300.0,
                   flash_duration_ms: float = 0.0,
                   search_start: float = 5.0,
                   search_end:   float = 40.0) -> dict:
    """Extract a-wave amplitude and implicit time from a broadband ERG sweep.

    Parameters
    ----------
    signal_uv : np.ndarray
        1-D broadband-filtered ERG in µV (t = 0 at stimulus onset).
    time_ms : np.ndarray
        Corresponding time axis in ms.
    protocol : str
        ISCEV protocol string ('DA 0.01', 'DA 3.0', 'DA 10.0',
        'LA 3.0', 'LA 30 Hz').
    hardware_lowpass_hz : float
        Hardware low-pass cutoff for this recording (Chapter 5 metadata).
        Used only to set a_wave_mar_technical when no a-wave is detected.
    flash_duration_ms : float
        Stimulus flash duration in ms. Per ISCEV 2022, flashes longer than
        FLASH_MIDPOINT_CORRECTION_THRESHOLD_MS (1 ms) require implicit time
        to be measured from the flash midpoint rather than flash onset.
    search_start, search_end : float
        Post-stimulus search window in ms.

    Returns
    -------
    dict with keys: a_amp_uv (float or NaN), a_implicit_ms (float or NaN),
                    a_wave_mar_technical (bool, only meaningful when NaN),
                    flash_midpoint_correction_applied (bool),
                    flash_midpoint_correction_ms (float).

    Notes
    -----
    DA 0.01 and LA 30 Hz do not generate a measurable a-wave; NaN is
    returned immediately for these protocols. LA 3.0 does have a
    scorable a-wave (ISCEV 2022: measured baseline-to-trough alongside
    DA 3.0 and DA 10.0) and is no longer excluded here.
    Amplitude is reported as absolute value (ISCEV 2022: baseline-to-trough).
    When no a-wave is detected, hardware_lowpass_hz is compared against a
    protocol-specific threshold (30 Hz dark-adapted, 35 Hz LA 3.0 -- this
    project's own convention, margined above the measured human a-b wave
    frequency ceiling of Chen, Zheng and Lei, 2013) to distinguish a
    MAR-technical absence from a MNAR-physiological one.
    """
    correction_ms = (flash_duration_ms / 2.0
                     if flash_duration_ms >= FLASH_MIDPOINT_CORRECTION_THRESHOLD_MS
                     else 0.0)
    correction_applied = correction_ms > 0.0

    if protocol.strip().upper() in ('DA 0.01', 'LA 30 HZ'):
        return {'a_amp_uv': np.nan, 'a_implicit_ms': np.nan}

    lowpass_threshold = 35.0 if protocol.strip().upper() == 'LA 3.0' else 30.0

    mask = (time_ms >= search_start) & (time_ms <= search_end)
    if not mask.any():
        return {'a_amp_uv': np.nan, 'a_implicit_ms': np.nan,
                'a_wave_mar_technical': hardware_lowpass_hz < lowpass_threshold}

    window_amp  = signal_uv[mask]
    window_time = time_ms[mask]
    a_local_idx = int(np.argmin(window_amp))
    a_amp_raw   = float(window_amp[a_local_idx])
    a_time      = float(window_time[a_local_idx]) - correction_ms

    # a-wave must be a negative deflection
    if a_amp_raw >= 0:
        return {'a_amp_uv': np.nan, 'a_implicit_ms': np.nan,
                'a_wave_mar_technical': hardware_lowpass_hz < lowpass_threshold}

    baseline_mask = time_ms < 0
    baseline_mean = float(signal_uv[baseline_mask].mean()) if baseline_mask.any() else 0.0
    a_amp_uv      = abs(a_amp_raw - baseline_mean)

    return {'a_amp_uv': round(a_amp_uv, 2), 'a_implicit_ms': round(a_time, 2),
            'flash_midpoint_correction_applied': correction_applied,
            'flash_midpoint_correction_ms': correction_ms}


def extract_b_wave(signal_uv:  np.ndarray,
                   time_ms:    np.ndarray,
                   protocol:   str,
                   a_time_ms:  float = np.nan,
                   flash_duration_ms: float = 0.0,
                   search_end: float = 150.0) -> dict:
    """Extract b-wave amplitude (trough-to-peak, ISCEV 2022) and implicit time.

    Parameters
    ----------
    signal_uv : np.ndarray
        Broadband-filtered ERG in µV.
    time_ms : np.ndarray
        Time axis in ms.
    protocol : str
        ISCEV protocol string.
    a_time_ms : float
        a-wave implicit time (ms), already flash-midpoint corrected if
        applicable. Pass np.nan for DA 0.01 (no a-wave); the
        baseline-to-peak convention is then used.
    flash_duration_ms : float
        Stimulus flash duration in ms. Per ISCEV 2022, flashes longer than
        FLASH_MIDPOINT_CORRECTION_THRESHOLD_MS (1 ms) require implicit time
        to be measured from the flash midpoint rather than flash onset.
    search_end : float
        End of b-wave search window in ms post-stimulus.

    Returns
    -------
    dict with keys: b_amp_uv (float or NaN), b_implicit_ms (float or NaN),
                    flash_midpoint_correction_applied (bool),
                    flash_midpoint_correction_ms (float).
    """
    correction_ms = (flash_duration_ms / 2.0
                     if flash_duration_ms >= FLASH_MIDPOINT_CORRECTION_THRESHOLD_MS
                     else 0.0)
    correction_applied = correction_ms > 0.0

    b_search_start = 20.0 if np.isnan(a_time_ms) else a_time_ms

    mask = (time_ms >= b_search_start) & (time_ms <= search_end)
    if not mask.any():
        return {'b_amp_uv': np.nan, 'b_implicit_ms': np.nan}

    window_amp  = signal_uv[mask]
    window_time = time_ms[mask]
    b_local_idx = int(np.argmax(window_amp))
    b_amp_raw   = float(window_amp[b_local_idx])
    b_time      = float(window_time[b_local_idx]) - correction_ms

    if b_amp_raw <= 0:
        return {'b_amp_uv': np.nan, 'b_implicit_ms': np.nan}

    if np.isnan(a_time_ms):
        # DA 0.01: baseline-to-peak
        baseline_mask   = time_ms < 0
        reference_level = float(signal_uv[baseline_mask].mean()) if baseline_mask.any() else 0.0
    else:
        # All other protocols: a-wave trough-to-peak (ISCEV 2022)
        a_idx           = int(np.argmin(np.abs(time_ms - a_time_ms)))
        reference_level = float(signal_uv[a_idx])

    b_amp_uv = b_amp_raw - reference_level
    if b_amp_uv <= 0:
        return {'b_amp_uv': np.nan, 'b_implicit_ms': np.nan}

    return {'b_amp_uv': round(b_amp_uv, 2), 'b_implicit_ms': round(b_time, 2),
            'flash_midpoint_correction_applied': correction_applied,
            'flash_midpoint_correction_ms': correction_ms}


def compute_ba_ratio(b_amp_uv: float, a_amp_uv: float) -> float:
    """Compute the b/a amplitude ratio.

    Returns NaN if either component is missing or if a_amp_uv is zero.
    A ratio < 1.0 is a negative ERG (diagnostic hallmark of complete CSNB).
    """
    if np.isnan(b_amp_uv) or np.isnan(a_amp_uv) or a_amp_uv == 0:
        return np.nan
    return round(b_amp_uv / a_amp_uv, 3)


def extract_phnr(signal_uv:    np.ndarray,
                 time_ms:      np.ndarray,
                 b_time_ms:    float,
                 noise_rms_uv: float,
                 hardware_highpass_hz: float = 0.3,
                 search_start: float = 60.0,
                 search_end:   float = 200.0) -> dict:
    """Extract PhNR amplitude from a LA 3.0 broadband-filtered sweep.

    Parameters
    ----------
    signal_uv : np.ndarray
        LA 3.0 broadband-filtered ERG in µV.
    time_ms : np.ndarray
        Time axis in ms.
    b_time_ms : float
        b-wave implicit time (ms). PhNR search starts after this.
    noise_rms_uv : float
        Pre-stimulus noise RMS from Chapter 2 quality pipeline.
    hardware_highpass_hz : float
        Hardware high-pass cutoff for this recording (Chapter 5 metadata).
        Used only to set phnr_mar_technical when no PhNR is detected.
    search_start, search_end : float
        PhNR search window bounds in ms post-stimulus.

    Returns
    -------
    dict with keys: phnr_amp_uv (float or NaN),
                    phnr_mar_technical (bool, only meaningful when NaN).

    Notes
    -----
    PhNR must exceed 2x noise RMS to be considered reliable. This
    multiplier is this project's own convention (see Chapter 11 §11.1.2),
    not an ISCEV-specified value; no peer-reviewed automated PhNR
    detectability threshold was found during this book's review.
    When no PhNR is detected, hardware_highpass_hz is compared against
    the ISCEV-specified 0.3 Hz target (Frishman et al., 2018) to
    distinguish a MAR-technical absence from a MNAR-physiological one.
    A 5-point moving average is applied before trough detection to reduce
    false detections from noise.
    """
    effective_start = max(search_start, b_time_ms + 5.0)
    mask = (time_ms >= effective_start) & (time_ms <= search_end)
    if not mask.any():
        return {'phnr_amp_uv': np.nan,
                'phnr_mar_technical': hardware_highpass_hz > 0.3}

    win_amp = signal_uv[mask]
    if len(win_amp) >= 5:
        smoothed = np.mean(sliding_window_view(win_amp, 5), axis=1)
    else:
        smoothed = win_amp

    seg_min, seg_max = float(np.min(smoothed)), float(np.max(smoothed))
    phnr_signed = seg_min if abs(seg_min) >= abs(seg_max) else seg_max
    phnr_magnitude = abs(phnr_signed)
    if phnr_magnitude < 2.0 * noise_rms_uv:
        return {'phnr_amp_uv': np.nan, 'phnr_polarity_atypical': False,
                'phnr_mar_technical': hardware_highpass_hz > 0.3}

    return {'phnr_amp_uv': round(phnr_signed, 2),
            'phnr_polarity_atypical': bool(phnr_signed > 0)}


def extract_oscillatory_potentials(op_signal_uv: np.ndarray,
                                    time_ms:      np.ndarray,
                                    hardware_lowpass_hz: float = 300.0,
                                    min_prom_uv:  float = 5.0,
                                    min_dist_ms:  float = 8.0,
                                    fs:           float = FS_HZ) -> dict:
    """Extract OP2, OP3, OP4 amplitudes and OP2 implicit time.

    Uses the 75-300 Hz bandpass-filtered signal (Chapter 5 output).
    OP1 is excluded because its trough overlaps the b-wave ascending limb; ISCEV 2022 does not define an OP1-OP4 numbering scheme.
    Returns NaN for any OP that cannot be reliably identified.

    Parameters
    ----------
    op_signal_uv : np.ndarray
        OP-isolated (75-300 Hz) filtered ERG in uV.
    time_ms : np.ndarray
        Time axis in ms.
    hardware_lowpass_hz : float
        Hardware low-pass cutoff for this recording (Chapter 5 metadata).
        Used only to set op_mar_technical when no OPs are detected.
    min_prom_uv : float
        Minimum peak prominence in uV.
    min_dist_ms : float
        Minimum inter-peak distance in ms.
    fs : float
        Sampling rate in Hz.

    Returns
    -------
    dict with keys: op2_amp_uv, op3_amp_uv, op4_amp_uv,
                    op_sum_uv, op2_implicit_ms,
                    op_mar_technical (bool, only meaningful when all NaN).
    """
    op_mar_technical = hardware_lowpass_hz < 300.0
    _nan_result = {k: np.nan for k in
                   ['op2_amp_uv', 'op3_amp_uv', 'op4_amp_uv',
                    'op_sum_uv', 'op2_implicit_ms']}
    _nan_result['op_mar_technical'] = op_mar_technical

    post_mask = (time_ms >= 0) & (time_ms <= 100)
    if not post_mask.any():
        return _nan_result

    post_amp  = op_signal_uv[post_mask]
    post_time = time_ms[post_mask]
    min_dist_samples = int(min_dist_ms * fs / 1000)

    peaks, _ = find_peaks(post_amp,
                          prominence=min_prom_uv,
                          distance=max(1, min_dist_samples))

    if len(peaks) < 2:
        return _nan_result

    # OP1 excluded: first valid peak must be ≥ 25 ms post-stimulus
    valid_peaks = [p for p in peaks if post_time[p] >= 25.0]
    if len(valid_peaks) < 2:
        return _nan_result

    results  = dict(_nan_result)
    op_amps  = []
    for i, label in enumerate(['op2', 'op3', 'op4']):
        if i >= len(valid_peaks):
            break
        peak_idx   = valid_peaks[i]
        peak_amp   = float(post_amp[peak_idx])
        trough_start = valid_peaks[i - 1] if i > 0 else 0
        trough_amp   = float(post_amp[trough_start:peak_idx + 1].min())
        op_amp_tp    = peak_amp - trough_amp
        results[f'{label}_amp_uv'] = round(op_amp_tp, 2)
        if label == 'op2':
            results['op2_implicit_ms'] = round(float(post_time[peak_idx]), 2)
        op_amps.append(op_amp_tp)

    if len(op_amps) >= 2:
        results['op_sum_uv'] = round(sum(op_amps), 2)

    return results


def extract_time_domain_features(broadband_uv:   np.ndarray,
                                  op_filtered_uv: np.ndarray,
                                  time_ms:        np.ndarray,
                                  protocol:       str,
                                  noise_rms_uv:   float,
                                  hardware_lowpass_hz:  float = 300.0,
                                  hardware_highpass_hz: float = 0.3,
                                  flash_duration_ms:     float = 0.0,
                                  fs:             float = FS_HZ) -> dict:
    """Extract all ISCEV time-domain features for one ERG recording.

    Orchestrates the individual extractors in the correct order:
    a-wave -> b-wave (using a-wave as reference) -> b/a ratio ->
    PhNR (LA 3.0 only) -> OPs (DA 3.0 and DA 10.0 only).

    Parameters
    ----------
    broadband_uv : np.ndarray
        Broadband-filtered ERG in uV (Chapter 5 §5.2.1 output).
    op_filtered_uv : np.ndarray
        OP-isolated 75-300 Hz signal in uV (Chapter 5 §5.3 output).
    time_ms : np.ndarray
        Time axis aligned to stimulus onset at t = 0 ms.
    protocol : str
        ISCEV protocol string.
    noise_rms_uv : float
        Pre-stimulus noise RMS from Chapter 2 quality pipeline.
    hardware_lowpass_hz : float
        Hardware low-pass cutoff for this recording (Chapter 5 metadata,
        default 300.0 matches an unconstrained device). Passed to the
        a-wave and OP extractors for MAR-technical vs MNAR-physiological
        classification when no signal is detected.
    hardware_highpass_hz : float
        Hardware high-pass cutoff for this recording (Chapter 5 metadata,
        default 0.3 matches the ISCEV target). Passed to the PhNR
        extractor for the same purpose.
    flash_duration_ms : float
        Stimulus flash duration in ms (device metadata, default 0.0 matches
        a near-instantaneous xenon flashtube, per ISCEV 2022). Passed to
        the a-wave and b-wave extractors for the ISCEV flash-midpoint
        implicit-time correction.
    fs : float
        Sampling rate in Hz.

    Returns
    -------
    dict of {feature_name: float_or_nan} for all time-domain features.
    """
    features = {}

    a = extract_a_wave(broadband_uv, time_ms, protocol,
                       hardware_lowpass_hz=hardware_lowpass_hz,
                       flash_duration_ms=flash_duration_ms)
    features.update(a)

    b = extract_b_wave(broadband_uv, time_ms, protocol,
                       a_time_ms=a['a_implicit_ms'],
                       flash_duration_ms=flash_duration_ms)
    features.update(b)

    features['ba_ratio'] = compute_ba_ratio(b['b_amp_uv'], a['a_amp_uv'])

    if protocol.strip().upper() == 'LA 3.0':
        b_t = b['b_implicit_ms'] if not np.isnan(b['b_implicit_ms']) else 50.0
        features.update(extract_phnr(broadband_uv, time_ms, b_t, noise_rms_uv,
                                     hardware_highpass_hz=hardware_highpass_hz))
    else:
        features['phnr_amp_uv'] = np.nan

    if protocol.strip().upper() in ('DA 3.0', 'DA 10.0'):
        features.update(
            extract_oscillatory_potentials(op_filtered_uv, time_ms,
                                           hardware_lowpass_hz=hardware_lowpass_hz,
                                           fs=fs))
    else:
        for k in ['op2_amp_uv', 'op3_amp_uv', 'op4_amp_uv',
                  'op_sum_uv', 'op2_implicit_ms']:
            features[k] = np.nan

    return features


# ══════════════════════════════════════════════════════════════════════════════
# SPECTROGRAM REGION FEATURES
# ══════════════════════════════════════════════════════════════════════════════


def extract_nonlinear_features(signal: np.ndarray) -> Dict[str, Any]:
    """
    Hurst Exponent and Approximate Entropy of the broadband signal.
    Both measures are significantly lower (p<0.05) in CSNB, RP, and
    cone-rod dystrophy vs. healthy controls (Nair and Joseph, 2014a).
    """
    x = np.asarray(signal, dtype=float)
    n = len(x)
    # Hurst exponent via detrended-difference scaling
    if n < 20:
        hurst = np.nan
    else:
        lags = range(2, n // 2)
        tau = np.array([np.std(x[lag:] - x[:-lag]) for lag in lags])
        valid = tau > 0
        if valid.sum() < 2:
            hurst = np.nan
        else:
            log_lags = np.log(np.array(list(lags))[valid])
            log_tau = np.log(tau[valid])
            slope, _ = np.polyfit(log_lags, log_tau, 1)
            hurst = float(slope * 2.0)
    # Approximate entropy (Pincus, 1991; m=2, r=0.15*SD per Nair and Joseph, 2014a)
    def _phi(m, r):
        z = np.array([x[i:i + m] for i in range(n - m + 1)])
        d = np.abs(z[:, None, :] - z[None, :, :]).max(axis=2)
        c = (d <= r).sum(axis=1) / (n - m + 1)
        return np.sum(np.log(c)) / (n - m + 1)
    if n < 10:
        apen = np.nan
    else:
        r = 0.15 * np.std(x)
        apen = float(_phi(2, r) - _phi(3, r)) if r > 0 else np.nan
    return {
        'hurst_exponent': round(hurst, 4) if not np.isnan(hurst) else np.nan,
        'approximate_entropy': round(apen, 4) if not np.isnan(apen) else np.nan,
    }



def extract_dwt_band_energies(signal: np.ndarray, fs_hz: float,
                               flash_onset_sample: int = 0,
                               wavelet: str = 'morl') -> Dict[str, Any]:
    """
    CWT band-energy descriptors at the six statistically-validated
    frequency/time-window pairs: 20/40 Hz over the a-wave window, 20/40 Hz
    over the b-wave window, and 80/160 Hz over the OP window
    (Gauvin, Lina and Lachapelle, 2014).
    """
    x = np.asarray(signal, dtype=float)
    n = len(x)
    t_ms = (np.arange(n) - flash_onset_sample) * 1000.0 / fs_hz
    dt = 1.0 / fs_hz
    central_freq = pywt.central_frequency(wavelet)
    descriptors = {
        'dwt_20a_uv2': (20.0, (5.0, 30.0)),
        'dwt_40a_uv2': (40.0, (5.0, 30.0)),
        'dwt_20b_uv2': (20.0, (20.0, 70.0)),
        'dwt_40b_uv2': (40.0, (20.0, 70.0)),
        'dwt_80ops_uv2': (80.0, (10.0, 45.0)),
        'dwt_160ops_uv2': (160.0, (10.0, 45.0)),
    }
    out = {}
    for key, (target_freq_hz, window_ms) in descriptors.items():
        scale = central_freq * fs_hz / target_freq_hz
        coeffs, _ = pywt.cwt(x, [scale], wavelet, sampling_period=dt)
        mag = np.abs(coeffs[0])
        mask = (t_ms >= window_ms[0]) & (t_ms <= window_ms[1])
        out[key] = round(float(np.sum(mag[mask] ** 2)), 2) if mask.any() else np.nan
    return out



def extract_bwave_derivative_features(signal: np.ndarray, fs_hz: float,
                                       b_wave_implicit_time_ms: float,
                                       flash_onset_sample: int = 0,
                                       search_end_ms: float = 150.0) -> Dict[str, Any]:
    """
    b-wave ascending- and descending-limb inflection points (2nd-derivative
    zero crossings), implicit time and gradient. Both limbs reached
    statistical significance in the source study (descending: p<0.001 time,
    p=0.033 gradient; ascending: p<0.001 time, p=0.005 gradient)
    (Wood, Margrain and Binns, 2014).
    """
    empty = {'b_ascending_inflection_ms': np.nan, 'b_ascending_gradient_uv_ms': np.nan,
             'b_descending_inflection_ms': np.nan, 'b_descending_gradient_uv_ms': np.nan}
    if np.isnan(b_wave_implicit_time_ms):
        return empty
    t_ms = (np.arange(len(signal)) - flash_onset_sample) * 1000.0 / fs_hz
    asc_mask = (t_ms >= 0.0) & (t_ms <= b_wave_implicit_time_ms - 1.0)
    asc_result = {'b_ascending_inflection_ms': np.nan, 'b_ascending_gradient_uv_ms': np.nan}
    if asc_mask.sum() >= 5:
        seg_t = t_ms[asc_mask]
        seg_x = np.asarray(signal)[asc_mask]
        d1 = np.gradient(seg_x, seg_t)
        d2 = np.gradient(d1, seg_t)
        sign_changes = np.where(np.diff(np.sign(d2)))[0]
        candidates = [i for i in sign_changes if d1[i] > 0]
        if candidates:
            idx = candidates[-1]
            asc_result = {
                'b_ascending_inflection_ms': round(float(seg_t[idx]), 2),
                'b_ascending_gradient_uv_ms': round(float(d1[idx]), 2),
            }
    desc_mask = (t_ms >= b_wave_implicit_time_ms + 3.0) & (t_ms <= search_end_ms)
    desc_result = {'b_descending_inflection_ms': np.nan, 'b_descending_gradient_uv_ms': np.nan}
    if desc_mask.sum() >= 5:
        seg_t = t_ms[desc_mask]
        seg_x = np.asarray(signal)[desc_mask]
        d1 = np.gradient(seg_x, seg_t)
        d2 = np.gradient(d1, seg_t)
        sign_changes = np.where(np.diff(np.sign(d2)))[0]
        candidates = [i for i in sign_changes if d1[i] < 0]
        if candidates:
            idx = candidates[0]
            desc_result = {
                'b_descending_inflection_ms': round(float(seg_t[idx]), 2),
                'b_descending_gradient_uv_ms': round(float(d1[idx]), 2),
            }
    return {**asc_result, **desc_result}



def extract_awave_descending_inflection(signal: np.ndarray, fs_hz: float,
                                         a_wave_implicit_time_ms: float,
                                         b_wave_implicit_time_ms: float,
                                         flash_onset_sample: int = 0) -> Dict[str, Any]:
    """
    a-wave descending-limb inflection point, implicit time only. Gradient at
    this point was NOT significant in the source study (p = 0.097) and is
    deliberately not extracted; implicit time was significant (p < 0.001,
    AUC 0.68) (Wood, Margrain and Binns, 2014).
    """
    if np.isnan(a_wave_implicit_time_ms) or np.isnan(b_wave_implicit_time_ms):
        return {'a_descending_inflection_ms': np.nan}
    t_ms = (np.arange(len(signal)) - flash_onset_sample) * 1000.0 / fs_hz
    mask = (t_ms >= a_wave_implicit_time_ms + 1.0) & (t_ms <= b_wave_implicit_time_ms - 1.0)
    if mask.sum() < 5:
        return {'a_descending_inflection_ms': np.nan}
    seg_t = t_ms[mask]
    seg_x = np.asarray(signal)[mask]
    d1 = np.gradient(seg_x, seg_t)
    d2 = np.gradient(d1, seg_t)
    sign_changes = np.where(np.diff(np.sign(d2)))[0]
    if len(sign_changes) == 0:
        return {'a_descending_inflection_ms': np.nan}
    idx = sign_changes[0]
    return {'a_descending_inflection_ms': round(float(seg_t[idx]), 2)}


def extract_frequency_domain_features(signal: np.ndarray, fs_hz: float,
                                       protocol: str = 'DA 3.0',
                                       fmin: float = 0.0, fmax: float = 300.0,
                                       fundamental_hz: float = 30.0,
                                       n_harmonics: int = 3,
                                       bw_hz: float = 2.0) -> Dict[str, Any]:
    """
    Peak PSD frequency and spectral entropy on the broadband signal for
    every protocol. Harmonic ratio (LA 30 Hz only).
    """
    freqs, psd = welch(signal, fs=fs_hz, nperseg=min(256, len(signal)))
    mask = (freqs >= fmin) & (freqs <= fmax)
    freqs_m, psd_m = freqs[mask], psd[mask]
    if len(psd_m) == 0 or np.sum(psd_m) == 0:
        out = {'peak_freq_hz': np.nan, 'spectral_entropy': np.nan}
    else:
        peak_freq = float(freqs_m[np.argmax(psd_m)])
        p_norm = psd_m / np.sum(psd_m)
        p_norm = p_norm[p_norm > 0]
        entropy = float(-np.sum(p_norm * np.log(p_norm)) / np.log(len(p_norm))) if len(p_norm) > 1 else np.nan
        out = {'peak_freq_hz': round(peak_freq, 2), 'spectral_entropy': round(entropy, 4)}
    if protocol.upper().replace(' ', '') in ('LA30HZ', 'LA30'):
        total_power = np.sum(psd)
        if total_power > 0:
            harmonic_power = 0.0
            for k in range(1, n_harmonics + 1):
                f0 = fundamental_hz * k
                hmask = (freqs >= f0 - bw_hz) & (freqs <= f0 + bw_hz)
                harmonic_power += np.sum(psd[hmask])
            out['harmonic_ratio'] = round(float(harmonic_power / total_power), 4)
        else:
            out['harmonic_ratio'] = np.nan
    return out



def extract_all_features(signal: np.ndarray, fs_hz: float,
                         protocol: str = 'DA 3.0',
                         flash_onset_sample: int = 0,
                         flash_duration_ms: float = 0.0,
                         op_signal: np.ndarray = None,
                         noise_rms_uv: float = 1.0,
                         hardware_lowpass_hz: float = 300.0,
                         hardware_highpass_hz: float = 0.3) -> Dict[str, Any]:
    """Assemble every feature family in this chapter for one recording.

    flash_duration_ms defaults to 0.0, matching ISCEV 2022's assumption
    for a near-instantaneous xenon flashtube; pass the device's actual
    flash duration for LED-based systems to apply the ISCEV
    flash-midpoint implicit-time correction where it is needed.

    hardware_lowpass_hz and hardware_highpass_hz are Chapter 5 device
    metadata, used only to distinguish a MAR-technical absence from a
    MNAR-physiological one when the a-wave, PhNR, or OPs are not detected.
    """
    time_ms = (np.arange(len(signal)) - flash_onset_sample) * 1000.0 / fs_hz

    features = {'protocol': protocol}

    # §9.1: a-wave, b-wave, b/a ratio
    a = extract_a_wave(signal, time_ms, protocol,
                       hardware_lowpass_hz=hardware_lowpass_hz,
                       flash_duration_ms=flash_duration_ms)
    features.update(a)
    b = extract_b_wave(signal, time_ms, protocol,
                       a_time_ms=a['a_implicit_ms'],
                       flash_duration_ms=flash_duration_ms)
    features.update(b)
    features['ba_ratio'] = compute_ba_ratio(b['b_amp_uv'], a['a_amp_uv'])

    # §9.1: oscillatory potentials, computed only when a dedicated
    # OP-isolated (75-300 Hz) signal is supplied; there is no fallback
    # to the broadband signal. Without op_signal, OP extraction is
    # skipped entirely and its keys are simply absent from the output.
    if protocol.strip().upper() in ('DA 3.0', 'DA 10.0') and op_signal is not None:
        features.update(extract_oscillatory_potentials(
            op_signal, time_ms, hardware_lowpass_hz=hardware_lowpass_hz))
    else:
        for k in ['op2_amp_uv', 'op3_amp_uv', 'op4_amp_uv',
                  'op_sum_uv', 'op2_implicit_ms']:
            features[k] = np.nan
    # §9.2: PhNR family, LA 3.0 only        
    if protocol.strip().upper() == 'LA 3.0':
        b_it = features.get('b_implicit_ms', np.nan)
        if not np.isnan(b_it):
            features.update(extract_phnr(signal, time_ms, b_it, noise_rms_uv,
                                         hardware_highpass_hz=hardware_highpass_hz))
            b_amp = features.get('b_amp_uv', np.nan)
            phnr_amp = features.get('phnr_amp_uv', np.nan)
            if not np.isnan(b_amp) and b_amp != 0 and not np.isnan(phnr_amp):
                features['phnr_bwave_ratio'] = round(float(phnr_amp / b_amp), 4)
            else:
                features['phnr_bwave_ratio'] = np.nan
        else:
            features['phnr_amp_uv'] = np.nan
            features['phnr_polarity_atypical'] = False
            features['phnr_bwave_ratio'] = np.nan

    # §9.3: nonlinear, DWT bands, b-wave and a-wave derivative features (all protocols)
    features.update(extract_nonlinear_features(signal))
    features.update(extract_dwt_band_energies(signal, fs_hz, flash_onset_sample))
    a_implicit = features.get('a_implicit_ms', np.nan)
    b_implicit = features.get('b_implicit_ms', np.nan)
    features.update(extract_bwave_derivative_features(
        signal, fs_hz, b_implicit, flash_onset_sample))
    features.update(extract_awave_descending_inflection(
        signal, fs_hz, a_implicit, b_implicit, flash_onset_sample))

    # §9.4: frequency-domain
    features.update(extract_frequency_domain_features(signal, fs_hz, protocol))

    return features


# ══════════════════════════════════════════════════════════════════════════════
# COMPLETE PATIENT PIPELINE
# ══════════════════════════════════════════════════════════════════════════════

def build_patient_feature_matrix(patient_recordings: dict,
                                  noise_rms_by_eye:   dict) -> dict:
    """Call extract_all_features() once per protocol x eye for one patient.

    Not printed in the book -- Section 9.6 describes this loop in prose
    ("Calling this once per recording, across all 5 protocols and both
    eyes for one patient...") without printing the loop itself. This is
    the repo's own implementation of that described pattern.

    Parameters
    ----------
    patient_recordings : dict
        Nested dict: {protocol: {eye: recording_dict}}.
        recording_dict must contain: signal_uv, fs_hz, flash_onset_sample.
        Optional per-recording keys: op_signal_uv, flash_duration_ms,
        hardware_lowpass_hz, hardware_highpass_hz.
    noise_rms_by_eye : dict
        {eye: {protocol: noise_rms_uv}} noise RMS from Chapter 2 pipeline.

    Returns
    -------
    dict {f'{protocol}_{eye}_{feature}': value}
        Flat feature vector. 5 protocols x 2 eyes x 25-27 features/recording
        = 256 raw values per patient (Section 9.6).
    """
    features = {}
    for protocol in PROTOCOLS:
        for eye in EYES:
            prefix = f"{protocol.replace(' ', '_').replace('.', 'p')}_{eye}"
            try:
                rec = patient_recordings[protocol][eye]
            except KeyError:
                continue
            nrms = noise_rms_by_eye.get(eye, {}).get(protocol, 5.0)
            recording_feats = extract_all_features(
                signal=rec['signal_uv'],
                fs_hz=rec['fs_hz'],
                protocol=protocol,
                flash_onset_sample=rec.get('flash_onset_sample', 0),
                flash_duration_ms=rec.get('flash_duration_ms', 0.0),
                op_signal=rec.get('op_signal_uv'),
                noise_rms_uv=nrms,
                hardware_lowpass_hz=rec.get('hardware_lowpass_hz', 300.0),
                hardware_highpass_hz=rec.get('hardware_highpass_hz', 0.3),
            )
            _meta_keys = {'protocol', 'flash_midpoint_correction_applied',
                          'flash_midpoint_correction_ms', 'op_mar_technical',
                          'a_wave_mar_technical', 'phnr_mar_technical',
                          'phnr_polarity_atypical'}
            features.update({f'{prefix}_{k}': v for k, v in recording_feats.items()
                             if k not in _meta_keys})
    return features


def rfe_selection(X_train:       np.ndarray,
                  y_train:       np.ndarray,
                  feature_names: list) -> list:
    """Recursive Feature Elimination with cross-validation (RFECV).

    Uses a Random Forest as the inner estimator. The cross-validated version
    automatically determines the optimal number of features by maximising
    macro AUC-ROC.

    Parameters
    ----------
    X_train : np.ndarray, shape (n_samples, n_features)
    y_train : np.ndarray, shape (n_samples,)
    feature_names : list of str

    Returns
    -------
    list of selected feature name strings.
    """
    estimator = RandomForestClassifier(
        n_estimators=100, max_depth=6, random_state=42, n_jobs=-1)
    cv       = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    selector = RFECV(estimator=estimator, step=5, cv=cv,
                     scoring='roc_auc_ovr', min_features_to_select=10,
                     n_jobs=-1)
    selector.fit(X_train, y_train)
    selected = [f for f, s in zip(feature_names, selector.support_) if s]
    print(f'RFE selected {len(selected)} features '
          f'(optimal n = {selector.n_features_})')
    return selected


def correlation_filter(X_train:       np.ndarray,
                        feature_names: list,
                        threshold:     float = 0.90) -> list:
    """Remove highly correlated features (Pearson r > threshold).

    For each correlated pair, retains the less redundant feature
    (the one with lower mean correlation to all other features).

    Parameters
    ----------
    X_train : np.ndarray, shape (n_samples, n_features)
    feature_names : list of str
    threshold : float
        Pearson |r| above which a pair is considered redundant.

    Returns
    -------
    list of retained feature name strings.
    """
    df    = pd.DataFrame(X_train, columns=feature_names)
    corr  = df.corr(method='pearson').abs()
    upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))

    to_drop = set()
    for col in upper.columns:
        correlated = upper.index[upper[col] > threshold].tolist()
        if correlated:
            all_candidates = [col] + correlated
            mean_corrs     = {f: corr[f].drop(f).mean() for f in all_candidates}
            most_redundant = max(mean_corrs, key=mean_corrs.get)
            to_drop.add(most_redundant)

    retained = [f for f in feature_names if f not in to_drop]
    print(f'Correlation filter: dropped {len(to_drop)}, '
          f'retained {len(retained)}')
    return retained


def mrmr_selection(X_train:       np.ndarray,
                   y_train:       np.ndarray,
                   feature_names: list,
                   n_features:    int = 40) -> list:
    """Minimum Redundancy Maximum Relevance feature selection.

    Requires the mrmr-selection package:  pip install mrmr-selection
    Falls back to all features with a warning if not installed.

    Parameters
    ----------
    X_train : np.ndarray, shape (n_samples, n_features)
    y_train : np.ndarray, shape (n_samples,)
    feature_names : list of str
    n_features : int
        Maximum number of features to select.

    Returns
    -------
    list of selected feature name strings.
    """
    try:
        import mrmr
        df       = pd.DataFrame(X_train, columns=feature_names)
        selected = mrmr.mrmr_classif(
            X=df, y=pd.Series(y_train),
            K=min(n_features, len(feature_names)))
        print(f'mRMR selected {len(selected)} features')
        return selected
    except ImportError:
        print('mrmr-selection not installed.  Run: pip install mrmr-selection')
        print('Falling back to all features.')
        return feature_names


def rf_importance_selection(X_train:       np.ndarray,
                             y_train:       np.ndarray,
                             feature_names: list,
                             top_k:         int = 40) -> list:
    """Select top-k features by Random Forest mean decrease in impurity.

    Parameters
    ----------
    X_train : np.ndarray, shape (n_samples, n_features)
    y_train : np.ndarray, shape (n_samples,)
    feature_names : list of str
    top_k : int
        Number of top features to return.

    Returns
    -------
    list of selected feature name strings (descending importance order).
    """
    rf = RandomForestClassifier(n_estimators=200, max_depth=8,
                                 random_state=42, n_jobs=-1)
    rf.fit(X_train, y_train)
    ranked   = sorted(zip(feature_names, rf.feature_importances_),
                      key=lambda x: x[1], reverse=True)
    selected = [name for name, _ in ranked[:top_k]]
    print(f'RF importance: top {len(selected)} features selected')
    for name, imp in ranked[:10]:
        print(f'  {name:<45s}  {imp:.4f}')
    return selected


def feature_selection_pipeline(X_train:        np.ndarray,
                                 y_train:        np.ndarray,
                                 feature_names:  list,
                                 vote_threshold: int = 2) -> list:
    """Run all four selection methods; retain features selected by ≥ vote_threshold.

    Parameters
    ----------
    X_train : np.ndarray, shape (n_samples, n_features)
    y_train : np.ndarray, shape (n_samples,)
    feature_names : list of str
    vote_threshold : int
        Minimum number of methods (out of 4) that must select a feature.

    Returns
    -------
    list of selected feature name strings, sorted by descending vote count.
    """
    print('Running feature selection pipeline...')
    print(f'Input: {X_train.shape[1]} features, {X_train.shape[0]} samples')

    rfe_feats  = set(rfe_selection(X_train, y_train, feature_names))
    corr_feats = set(correlation_filter(X_train, feature_names))
    mrmr_feats = set(mrmr_selection(X_train, y_train, feature_names))
    rf_feats   = set(rf_importance_selection(X_train, y_train, feature_names))

    votes = Counter()
    for feat_set in [rfe_feats, corr_feats, mrmr_feats, rf_feats]:
        for f in feat_set:
            votes[f] += 1

    selected = sorted([f for f, v in votes.items() if v >= vote_threshold],
                      key=lambda f: -votes[f])

    print(f'\nSelected {len(selected)} features '
          f'(threshold = {vote_threshold}/4 votes)')
    for v in range(4, 0, -1):
        at_v = [f for f in selected if votes[f] == v]
        if at_v:
            print(f'  {v} votes: {len(at_v)} features')
    return selected



# ══════════════════════════════════════════════════════════════════════════════
# Smoke test
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    from scipy.signal import butter, sosfiltfilt

    fs    = int(FS_HZ)
    pre   = 100       # ms pre-stimulus
    epoch = 500       # ms total
    N     = int(fs * epoch / 1000)
    t_ms  = np.linspace(-pre, epoch - pre, N, endpoint=False)
    flash_onset_sample = int(pre * fs / 1000)

    def make_sweep(a=-120, b=280, op=1.0, noise=5, seed=0) -> np.ndarray:
        rng = np.random.default_rng(seed)
        sig = np.zeros(N)
        post = t_ms >= 0
        sig[post] += a * np.exp(-((t_ms[post] - 20) ** 2) / (2 * 8  ** 2))
        sig[post] += b * np.exp(-((t_ms[post] - 60) ** 2) / (2 * 18 ** 2))
        for ot, oa in [(28, 18), (35, 22), (45, 16), (58, 10)]:
            sig[post] += (op * oa
                          * np.sin(2 * np.pi * 120 * t_ms[post] / 1000)
                          * np.exp(-((t_ms[post] - ot) ** 2) / (2 * 5 ** 2)))
        return sig + rng.normal(0, noise, N)

    def make_op_filtered(sig: np.ndarray) -> np.ndarray:
        sos = butter(4, [75, 300], btype='bandpass', fs=fs, output='sos')
        return sosfiltfilt(sos, sig)

    normal = make_sweep(seed=0)

    print('=== extract_all_features() for one DA 3.0 recording ===')
    feats = extract_all_features(normal, fs, protocol='DA 3.0',
                                  flash_onset_sample=flash_onset_sample,
                                  flash_duration_ms=1.0,
                                  op_signal=make_op_filtered(normal),
                                  noise_rms_uv=5.0)
    for k, v in feats.items():
        print(f'  {k:<32s} = {v}')
    meta_keys = {'protocol', 'flash_midpoint_correction_applied',
                 'flash_midpoint_correction_ms', 'op_mar_technical',
                 'a_wave_mar_technical', 'phnr_mar_technical',
                 'phnr_polarity_atypical'}
    n_feats = len([k for k in feats if k not in meta_keys])
    print(f'\n  {n_feats} diagnostic features on this DA 3.0 recording (expect 25)')
    assert n_feats == 25, f"expected 25 diagnostic features on DA 3.0, got {n_feats}"

    print('\\n=== Full patient feature matrix (build_patient_feature_matrix) ===')
    rec_template = {'signal_uv': normal, 'fs_hz': float(fs),
                     'flash_onset_sample': flash_onset_sample,
                     'op_signal_uv': make_op_filtered(normal)}
    patient_recs   = {p: {'RE': rec_template, 'LE': rec_template} for p in PROTOCOLS}
    noise_rms_dict = {eye: {p: 5.0 for p in PROTOCOLS} for eye in EYES}
    all_feats  = build_patient_feature_matrix(patient_recs, noise_rms_dict)
    feat_names = list(all_feats.keys())
    feat_vals  = np.array(list(all_feats.values()), dtype=float)
    print(f'  Total raw values : {len(feat_names)}  (expect 256)')
    assert len(feat_names) == 256, f"expected 256 raw values, got {len(feat_names)}"
    print(f'  NaN count        : {int(np.isnan(feat_vals).sum())}  (expected for protocol-gated features)')

    print('\\n=== Feature selection pipeline (synthetic 3-class dataset) ===')
    n_each = 15
    labels_, X_rows = [], []
    for cls_idx, (a, b, op_s) in enumerate([
            (-120, 280, 1.0), (-80, 230, 0.4), (-10, 22, 0.05)]):
        for seed in range(n_each):
            s   = make_sweep(a=a, b=b, op=op_s, seed=seed + cls_idx * n_each)
            rec_ = {'signal_uv': s, 'fs_hz': float(fs),
                     'flash_onset_sample': flash_onset_sample,
                     'op_signal_uv': make_op_filtered(s)}
            pr  = {p: {'RE': rec_, 'LE': rec_} for p in PROTOCOLS}
            fv  = build_patient_feature_matrix(pr, noise_rms_dict)
            X_rows.append(list(fv.values()))
            labels_.append(cls_idx)

    X_all  = np.nan_to_num(np.array(X_rows, dtype=float))
    y_all  = np.array(labels_)
    fnames = feat_names

    selected = feature_selection_pipeline(X_all, y_all, fnames, vote_threshold=2)
    print(f'\\nFinal selected feature count: {len(selected)}')

    print('\\n=== ALL SMOKE TESTS PASSED ===')
