# -*- coding: utf-8 -*-
"""Chapter_14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r-qQ0crAuzJf4p3rYmDuIxWhcvNFdm5L
"""

# -*- coding: utf-8 -*-
"""
chapter_14_shap_explainability.py
===================================
Hands-On Electroretinography in the Age of AI
Chapter 14 – SHAP Explainability Framework

Implements the three-level SHAP explainability pipeline for the clinical report:

  LEVEL 1 – TreeSHAP for Random Forest (§14.2)
    compute_feature_shap        – Signed waterfall chart per patient record

  LEVEL 2 – GradientSHAP for Vision Transformer (§14.3)
    compute_spectrogram_shap    – 224×224 pixel saliency overlay
    summarise_saliency_regions  – Mean saliency per ERG time-frequency region

  LEVEL 3 – Plain-language clinical translation (§14.4)
    plain_language_shap         – SHAP → clinician-readable narrative sentences

  CALIBRATION (§14.5)
    calibrate_vit_output        – Per-class Platt scaling with Brier Score gate

  INTEGRATION
    generate_shap_report_block  – Combines all three levels into one report dict

SHAP magnitude thresholds for Layer 2 narrative (§14.4.1):
  Dominant     |SHAP| ≥ 0.20   – named explicitly, rank word attached
  Significant  0.10 ≤ |SHAP| < 0.20  – named explicitly
  Supporting   0.05 ≤ |SHAP| < 0.10  – grouped into one sentence
  Negligible   |SHAP| < 0.05   – not mentioned in narrative

SHAP is computed for all non-Green Traffic Light results and stored in the
Layer 4 audit record. SHAP attributions for Green results are stored in
the audit log but NOT displayed to clinical users (risk of misinterpretation).

Repository : https://github.com/AI-Fairness-com/ERG-Analysis-API
Author     : Hamid
Licence    : See repo root LICENSE
"""

# ── Dependencies ───────────────────────────────────────────────────────────────
# Run once in your Colab session:
#   !pip install shap scipy scikit-learn torch timm matplotlib -q

import os
import warnings
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

import shap
import torch

from typing import Dict, List, Tuple
from scipy.special  import expit as sigmoid
from scipy.optimize import minimize
from sklearn.calibration import calibration_curve
from sklearn.metrics      import brier_score_loss
from sklearn.preprocessing import label_binarize

# ── Locked project constants ───────────────────────────────────────────────────
BRIER_THRESHOLD = 0.25    # calibration warning gate (§14.5.3)
IMG_SIZE        = 224     # spectrogram image size (pixels)
FS_HZ           = 2000    # pipeline sampling rate
OUTPUT_DIR      = 'outputs/shap'

DISEASE_CLASSES = [
    'Diabetic Retinopathy (early)',
    'Glaucoma (early)',
    'Retinitis Pigmentosa / Rod Dystrophy',
    'Age-Related Macular Degeneration',
    'Cone Dystrophy',
    'Complete CSNB',
]
ALL_CLASSES = ['Normal'] + DISEASE_CLASSES

RANK_WORDS = ['the dominant', 'the second', 'the third', 'the fourth', 'the fifth']


# ══════════════════════════════════════════════════════════════════════════════
# SHAP-to-clinical sentence mapping table (§14.4.2)
# ══════════════════════════════════════════════════════════════════════════════

SHAP_SENTENCE_MAP: Dict[Tuple[str, str], Tuple[str, str]] = {
    ('op2_implicit_time_ms', 'high'): (
        'The delay in OP2 implicit time was {rank} contributor to the {cls} '
        'classification (contribution: {pct}%). Delayed oscillatory potentials '
        'are an established early marker of inner retinal dysfunction, particularly '
        'in early diabetic maculopathy.',
        'Diabetic Retinopathy',
    ),
    ('op2_implicit_time_ms', 'low'): (
        'The OP2 implicit time was within or below the normal reference range '
        '(contribution: {pct}%), providing evidence against inner retinal '
        'conduction delay.',
        'Normal / non-DR',
    ),
    ('b_mean_intensity', 'low'): (
        'The reduction in spectrogram mean intensity was {rank} contributor to '
        'the {cls} classification (contribution: {pct}%). Reduced overall spectral '
        'energy reflects a global attenuation of bipolar cell and inner retinal '
        'activity.',
        'Diabetic Retinopathy / RP / Rod Dystrophy',
    ),
    ('phnr_amplitude_uv', 'low'): (
        'The reduction in photopic negative response (PhNR) amplitude was {rank} '
        'contributor to the {cls} classification (contribution: {pct}%). The PhNR '
        'reflects retinal ganglion cell function; its reduction is the primary ERG '
        'marker of early glaucomatous damage.',
        'Glaucoma',
    ),
    ('b_wave_implicit_time_ms', 'high'): (
        'The delayed b-wave implicit time was {rank} contributor to the {cls} '
        'classification (contribution: {pct}%). B-wave delay indicates slowed '
        'bipolar cell signal transmission, consistent with inner nuclear layer '
        'dysfunction.',
        'Diabetic Retinopathy / AMD',
    ),
    ('op_power_ratio', 'low'): (
        'The reduction in oscillatory potential power ratio was {rank} contributor '
        'to the {cls} classification (contribution: {pct}%). The OP power ratio '
        'reflects the proportion of total spectral energy in the 75–300 Hz '
        'amacrine cell band.',
        'Diabetic Retinopathy',
    ),
    ('ba_ratio', 'low'): (
        'The reduced b/a amplitude ratio was {rank} contributor to the {cls} '
        'classification (contribution: {pct}%). A b/a ratio below 1.0 on the '
        'dark-adapted 3.0 cd·s·m⁻² response indicates that b-wave amplitude is '
        'disproportionately reduced relative to the a-wave, consistent with '
        'bipolar cell or rod photoreceptor dysfunction.',
        'RP / Rod Dystrophy / CSNB',
    ),
    ('a_wave_amplitude_uv', 'low'): (
        'The reduction in a-wave amplitude was {rank} contributor to the {cls} '
        'classification (contribution: {pct}%). A-wave reduction reflects '
        'photoreceptor outer segment dysfunction.',
        'RP / Rod Dystrophy / Cone Dystrophy',
    ),
}


# ══════════════════════════════════════════════════════════════════════════════
# Level 1 – TreeSHAP for Random Forest
# ══════════════════════════════════════════════════════════════════════════════

def compute_feature_shap(pipeline,
                          X_test:        np.ndarray,
                          y_test,
                          sample_idx:    int,
                          class_names:   List[str],
                          feature_names: List[str],
                          output_dir:    str = OUTPUT_DIR) -> dict:
    """Compute TreeSHAP values for a single patient record.

    Uses shap.TreeExplainer for exact (not approximate) Shapley values
    computed in polynomial time for the Random Forest.

    The waterfall chart shows all 28 features ranked by |SHAP|, with signed
    bars coloured by feature value direction (above/below training mean).
    The sum of all bars exactly bridges the gap between the model's average
    output (base value) and its output for this specific recording.

    Parameters
    ----------
    pipeline : fitted sklearn Pipeline (Chapter 12 Random Forest)
    X_test : np.ndarray, shape (n_test, n_features) – raw (pre-transform) matrix
    y_test : array-like or None – true labels (optional, for display only)
    sample_idx : int – index into X_test for the patient to explain
    class_names : list of str – 7-class label list
    feature_names : list of str – 28-feature name list
    output_dir : str – directory for saved PNG artefacts

    Returns
    -------
    dict with keys: shap_values, base_value, predicted_class,
                    predicted_proba, feature_names, top_features (top 5 by |SHAP|)
    """
    os.makedirs(output_dir, exist_ok=True)

    preproc = pipeline[:-1]   # all steps except final classifier
    clf     = pipeline[-1]    # RandomForestClassifier
    X_trans = preproc.transform(X_test)

    explainer = shap.TreeExplainer(clf)
    shap_vals = explainer.shap_values(X_trans)
    # shap_vals shape: (n_classes, n_samples, n_features)
    base_vals = explainer.expected_value   # shape: (n_classes,)

    pred_class_idx = int(clf.predict(X_trans[[sample_idx]])[0])
    pred_class     = class_names[pred_class_idx]
    pred_proba     = float(clf.predict_proba(X_trans[[sample_idx]])[0, pred_class_idx])

    sv   = shap_vals[pred_class_idx][sample_idx]   # (n_features,)
    base = base_vals[pred_class_idx]

    # Waterfall chart
    shap_exp = shap.Explanation(
        values        = sv,
        base_values   = base,
        data          = X_trans[sample_idx],
        feature_names = feature_names,
    )
    plt.figure(figsize=(10, 8))
    shap.plots.waterfall(shap_exp, max_display=15, show=False)
    plt.title(f'SHAP Waterfall — {pred_class} (p={pred_proba:.2f})',
              fontsize=12, fontweight='bold')
    plt.tight_layout()
    save_path = os.path.join(output_dir, f'waterfall_sample{sample_idx}.png')
    plt.savefig(save_path, dpi=220, bbox_inches='tight')
    plt.close()

    return {
        'shap_values'    : sv,
        'base_value'     : base,
        'predicted_class': pred_class,
        'predicted_proba': round(pred_proba, 4),
        'feature_names'  : feature_names,
        'top_features'   : sorted(
            zip(feature_names, sv), key=lambda x: abs(x[1]), reverse=True)[:5],
    }


# ══════════════════════════════════════════════════════════════════════════════
# Level 2 – GradientSHAP for Vision Transformer
# ══════════════════════════════════════════════════════════════════════════════

def compute_spectrogram_shap(model,
                               spectrogram: torch.Tensor,
                               background:  torch.Tensor,
                               class_idx:   int,
                               class_name:  str,
                               output_dir:  str = OUTPUT_DIR) -> np.ndarray:
    """Compute pixel-level GradientSHAP saliency for a single spectrogram.

    GradientExplainer is the primary spectrogram-level explainability method
    (selected over attention rollout for superior spatial specificity on
    ERG spectrograms per §14.3.3). Produces a 224×224 saliency map overlaid
    on the original spectrogram.

    Validation criterion: highest-saliency regions must correspond to the
    clinically expected ERG components for the predicted disease class
    (OP burst at 75–300 Hz / 15–70 ms for DR; PhNR band for Glaucoma; etc.).

    Parameters
    ----------
    model : trained ViT Small nn.Module (Chapter 13), in eval mode
    spectrogram : torch.Tensor, shape (1, 3, 224, 224)
    background : torch.Tensor, shape (n_bg, 3, 224, 224)
        Reference background for SHAP baseline (typically 20 training images).
    class_idx : int – predicted class index (0–5 for Stage 2)
    class_name : str – predicted class label for figure title
    output_dir : str

    Returns
    -------
    np.ndarray, shape (224, 224) – normalised saliency map in [0, 1]
    """
    os.makedirs(output_dir, exist_ok=True)
    model.eval()

    explainer   = shap.GradientExplainer(model, background)
    shap_values = explainer.shap_values(spectrogram)
    # shap_values: list of (1, 3, 224, 224) per class
    sv_class = shap_values[class_idx][0]          # (3, 224, 224)
    saliency = np.mean(np.abs(sv_class), axis=0)  # (224, 224)
    saliency = (saliency - saliency.min()) / (saliency.max() - saliency.min() + 1e-8)

    # Original spectrogram for overlay
    spec_np = spectrogram[0].permute(1, 2, 0).cpu().numpy()  # (224, 224, 3)
    spec_np = (spec_np - spec_np.min()) / (spec_np.max() - spec_np.min() + 1e-8)

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    axes[0].imshow(spec_np)
    axes[0].set_title('Original Spectrogram')
    axes[0].axis('off')

    axes[1].imshow(saliency, cmap='hot')
    axes[1].set_title(f'SHAP Saliency — {class_name}')
    axes[1].axis('off')

    heat    = cm.hot(saliency)[..., :3]
    overlay = np.clip((1 - 0.45) * spec_np + 0.45 * heat, 0, 1)
    axes[2].imshow(overlay)
    axes[2].set_title('Spectrogram + SHAP Overlay')
    axes[2].axis('off')

    plt.suptitle(f'Spectrogram-Level SHAP  │  {class_name}',
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    fname = f'spectrogram_shap_{class_name.replace(" ", "_")}.png'
    plt.savefig(os.path.join(output_dir, fname), dpi=220, bbox_inches='tight')
    plt.close()

    return saliency


def summarise_saliency_regions(saliency:          np.ndarray,
                                fs:               int   = FS_HZ,
                                nperseg:          int   = 64,
                                total_duration_ms: float = 250.0) -> dict:
    """Map a 224×224 saliency map to named ERG time-frequency regions.

    Divides the saliency map into five clinically defined regions and computes
    mean saliency per region, normalised to [0, 1]. Included in the Layer 3
    Specialist Report alongside the full saliency overlay.

    Parameters
    ----------
    saliency : np.ndarray, shape (H, W) – normalised saliency from compute_spectrogram_shap
    fs : int – sampling rate in Hz (sets frequency axis scale)
    nperseg : int – STFT window length (not used directly; retained for API consistency)
    total_duration_ms : float – total post-stimulus duration in ms (sets time axis scale)

    Returns
    -------
    dict {region_name: normalised_mean_saliency} all values in [0, 1]

    Regions:
      b_wave_band    0–30 Hz,   40–150 ms  (b-wave dominant band)
      phnr_band      0–15 Hz,   80–160 ms  (PhNR / slow photopic response)
      op_burst_band  75–300 Hz, 15–70 ms   (oscillatory potentials)
      high_freq_band 300–500 Hz, 0–100 ms  (high-frequency noise reference)
      prestim_noise  all freq,   0–20 ms   (pre-stimulus baseline)
    """
    H, W      = saliency.shape
    freq_max  = fs / 2           # 1000 Hz
    time_max  = total_duration_ms

    def px_rows(f_low, f_high):
        return int(f_low / freq_max * H), int(f_high / freq_max * H)

    def px_cols(t_low_ms, t_high_ms):
        return int(t_low_ms / time_max * W), int(t_high_ms / time_max * W)

    regions = {
        'b_wave_band'   : (px_rows(0,   30),  px_cols(40,  150)),
        'phnr_band'     : (px_rows(0,   15),  px_cols(80,  160)),
        'op_burst_band' : (px_rows(75,  300), px_cols(15,   70)),
        'high_freq_band': (px_rows(300, 500), px_cols(0,   100)),
        'prestim_noise' : (px_rows(0,   500), px_cols(0,    20)),
    }

    results = {}
    for name, ((r0, r1), (c0, c1)) in regions.items():
        patch = saliency[r0:r1, c0:c1]
        results[name] = float(patch.mean()) if patch.size > 0 else 0.0

    max_sal  = max(results.values()) or 1.0
    return {k: round(v / max_sal, 3) for k, v in results.items()}


# ══════════════════════════════════════════════════════════════════════════════
# Level 3 – Plain-language SHAP narrative
# ══════════════════════════════════════════════════════════════════════════════

def plain_language_shap(shap_values:     np.ndarray,
                         feature_values:  np.ndarray,
                         feature_names:   List[str],
                         feature_means:   np.ndarray,
                         predicted_class: str,
                         min_pct:         float = 5.0) -> str:
    """Convert SHAP values to a clinician-readable narrative paragraph.

    Processes features in descending order of |SHAP| contribution. Features
    above min_pct (5%) are named individually using the SHAP_SENTENCE_MAP
    template. Features between 2% and 5% are grouped into a single sentence.
    Features below 2% are not mentioned.

    No SHAP numerical values or probability units appear in the output —
    only plain-language clinical descriptions are shown in the Layer 2 report.

    Parameters
    ----------
    shap_values : np.ndarray, shape (n_features,)
    feature_values : np.ndarray, shape (n_features,) – post-transform values
    feature_names : list of str
    feature_means : np.ndarray, shape (n_features,) – training-set mean per feature
    predicted_class : str
    min_pct : float – minimum % contribution to name a feature individually

    Returns
    -------
    str – plain-English narrative for the Layer 2 Clinical Summary
    """
    total = np.sum(np.abs(shap_values))
    contributions = [
        (feat, sv, fv, abs(sv) / (total + 1e-8) * 100)
        for feat, sv, fv in zip(feature_names, shap_values, feature_values)
    ]
    contributions.sort(key=lambda x: -x[3])

    sentences  = []
    rank_idx   = 0
    minor_feats = []

    for feat, sv, fv, pct in contributions:
        if pct < min_pct:
            if pct >= 2.0:
                minor_feats.append(feat)
            continue
        direction = 'high' if fv > feature_means[feature_names.index(feat)] else 'low'
        key = (feat, direction)
        if key in SHAP_SENTENCE_MAP:
            tmpl, _ = SHAP_SENTENCE_MAP[key]
            rank_word = RANK_WORDS[rank_idx] if rank_idx < len(RANK_WORDS) else 'a'
            sentences.append(tmpl.format(
                rank=rank_word, cls=predicted_class, pct=f'{pct:.0f}'))
            rank_idx += 1

    if minor_feats:
        joined = ', '.join(minor_feats[:3])
        sentences.append(f'Additional supporting contributors included: {joined}.')

    if not sentences:
        return (
            'The classification is supported by a combination of minor feature '
            'contributions, none of which individually exceeds 5% of the total '
            'attribution. Please refer to the SHAP waterfall chart in the '
            'Specialist Report for details.')

    return ' '.join(sentences)


# ══════════════════════════════════════════════════════════════════════════════
# Calibration – Platt scaling for ViT output
# ══════════════════════════════════════════════════════════════════════════════

def calibrate_vit_output(logits_val:      np.ndarray,
                          y_val:           np.ndarray,
                          logits_test:     np.ndarray,
                          y_test:          np.ndarray,
                          class_names:     list,
                          brier_threshold: float = BRIER_THRESHOLD) -> dict:
    """Apply per-class Platt scaling to ViT logits (§14.5).

    Fits a sigmoid A·x + B on the validation logits for each class
    independently (one-versus-rest). Re-normalises calibrated probabilities
    to sum to 1. Validates calibration quality with per-class Brier Score.

    A macro Brier Score above brier_threshold triggers CALIBRATION_WARNING
    in the Layer 4 audit record and must be resolved before deployment.

    Parameters
    ----------
    logits_val : np.ndarray, shape (n_val, n_classes) – raw ViT logits, val set
    y_val : np.ndarray, shape (n_val,) – true integer labels, val set
    logits_test : np.ndarray, shape (n_test, n_classes) – raw ViT logits, test set
    y_test : np.ndarray, shape (n_test,) – true integer labels, test set
    class_names : list of str
    brier_threshold : float (default 0.25)

    Returns
    -------
    dict with keys: calibrated_proba, platt_params, brier_per_class,
                    macro_brier, layer4_audit_flag
    """
    n_classes   = logits_val.shape[1]
    platt_params = {}
    calib_proba  = np.zeros_like(logits_test, dtype=float)

    for c in range(n_classes):
        y_bin_val = (y_val == c).astype(float)

        def neg_log_likelihood(params):
            A, B = params
            p    = sigmoid(A * logits_val[:, c] + B)
            p    = np.clip(p, 1e-7, 1 - 1e-7)
            return -np.mean(y_bin_val * np.log(p) + (1 - y_bin_val) * np.log(1 - p))

        res = minimize(neg_log_likelihood, x0=[1.0, 0.0], method='Nelder-Mead')
        A, B = res.x
        platt_params[class_names[c]] = {'A': round(A, 5), 'B': round(B, 5)}
        calib_proba[:, c] = sigmoid(A * logits_test[:, c] + B)

    # Re-normalise to sum to 1
    calib_proba = calib_proba / calib_proba.sum(axis=1, keepdims=True)

    # Brier Score validation
    y_test_bin      = label_binarize(y_test, classes=list(range(n_classes)))
    brier_per_class = [
        brier_score_loss(y_test_bin[:, c], calib_proba[:, c])
        for c in range(n_classes)
    ]
    macro_brier = float(np.mean(brier_per_class))
    audit_flag  = 'PASS'

    if macro_brier > brier_threshold:
        audit_flag = 'CALIBRATION_WARNING'
        warnings.warn(
            f'Macro Brier Score {macro_brier:.4f} exceeds threshold '
            f'{brier_threshold}. Layer 4 audit flag set to '
            f'CALIBRATION_WARNING. Recalibrate before production deployment.',
            UserWarning,
        )

    print(f'Platt scaling complete.  '
          f'Macro Brier Score: {macro_brier:.4f}  [{audit_flag}]')

    return {
        'calibrated_proba' : calib_proba,
        'platt_params'     : platt_params,
        'brier_per_class'  : dict(zip(class_names, brier_per_class)),
        'macro_brier'      : round(macro_brier, 4),
        'layer4_audit_flag': audit_flag,
    }


# ══════════════════════════════════════════════════════════════════════════════
# Integration – full SHAP report block
# ══════════════════════════════════════════════════════════════════════════════

def generate_shap_report_block(rf_pipeline,
                                vit_model,
                                feature_matrix: np.ndarray,
                                spectrogram:    torch.Tensor,
                                background:     torch.Tensor,
                                class_names:    list,
                                feature_names:  list,
                                feature_means:  np.ndarray,
                                output_dir:     str = OUTPUT_DIR) -> dict:
    """Generate all three SHAP levels for one patient record.

    Produces and saves three artefacts:
      Layer 2: plain-language narrative string
      Layer 3: waterfall PNG + spectrogram saliency overlay PNG + region dict
      Layer 4: raw SHAP values dict + top-5 features list

    Parameters
    ----------
    rf_pipeline : fitted sklearn Pipeline (Chapter 12 Random Forest)
    vit_model : trained ViT Small nn.Module (Chapter 13, calibrated)
    feature_matrix : np.ndarray, shape (1, n_features) – one patient record
    spectrogram : torch.Tensor, shape (1, 3, 224, 224)
    background : torch.Tensor, shape (n_bg, 3, 224, 224)
    class_names, feature_names : lists of str
    feature_means : np.ndarray, shape (n_features,) – training-set means
    output_dir : str

    Returns
    -------
    dict ready for embedding in the four-layer clinical report
    """
    os.makedirs(output_dir, exist_ok=True)

    # ── Level 1: TreeSHAP (Random Forest) ────────────────────────────────
    l1 = compute_feature_shap(
        rf_pipeline, feature_matrix, None, 0,
        class_names, feature_names, output_dir,
    )

    # ── Level 2: GradientSHAP (ViT Small) ────────────────────────────────
    pred_class_idx = class_names.index(l1['predicted_class'])
    saliency       = compute_spectrogram_shap(
        vit_model, spectrogram, background,
        pred_class_idx, l1['predicted_class'], output_dir,
    )
    region_summary = summarise_saliency_regions(saliency)

    # ── Level 3: Plain-language narrative ─────────────────────────────────
    preproc  = rf_pipeline[:-1]
    X_trans  = preproc.transform(feature_matrix)
    sv       = shap.TreeExplainer(rf_pipeline[-1]).shap_values(X_trans)[pred_class_idx][0]
    narrative = plain_language_shap(
        sv, X_trans[0], feature_names, feature_means, l1['predicted_class'])

    clean_cls = l1['predicted_class'].replace(' ', '_')
    return {
        'layer2_narrative'     : narrative,
        'layer3_waterfall_path': os.path.join(output_dir, 'waterfall_sample0.png'),
        'layer3_saliency_path' : os.path.join(output_dir,
                                              f'spectrogram_shap_{clean_cls}.png'),
        'layer3_region_summary': region_summary,
        'layer4_shap_values'   : dict(zip(feature_names, sv.tolist())),
        'layer4_top5_features' : l1['top_features'],
        'predicted_class'      : l1['predicted_class'],
        'predicted_proba'      : l1['predicted_proba'],
    }


# ══════════════════════════════════════════════════════════════════════════════
# Smoke test
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.impute import SimpleImputer

    rng = np.random.default_rng(42)
    N_FEAT = 28

    feat_names = (
        ['op2_implicit_time_ms', 'b_mean_intensity', 'phnr_amplitude_uv',
         'b_wave_implicit_time_ms', 'op_power_ratio', 'ba_ratio',
         'a_wave_amplitude_uv', 'op_sum_uv']
        + [f'feat_{i:02d}' for i in range(N_FEAT - 8)]
    )

    # ── 1. Synthetic dataset for TreeSHAP ─────────────────────────────────
    N_REC   = 300
    N_CLASS = 7
    class_p = [0.28, 0.18, 0.15, 0.12, 0.10, 0.09, 0.08]
    y_all   = rng.choice(N_CLASS, size=N_REC, p=class_p)
    X_all   = rng.normal(0, 1, (N_REC, N_FEAT)).astype(np.float32)
    for c in range(N_CLASS):
        X_all[y_all == c, 0] += c * 1.5   # op2_implicit_time_ms signal
        X_all[y_all == c, 1] -= c * 0.8   # b_mean_intensity signal
        X_all[y_all == c, 2] += (6 - c) * 0.6  # phnr_amplitude_uv

    idx   = rng.permutation(N_REC)
    n_tr  = int(0.70 * N_REC)
    X_tr, y_tr = X_all[idx[:n_tr]],  y_all[idx[:n_tr]]
    X_te, y_te = X_all[idx[n_tr:]], y_all[idx[n_tr:]]

    rf_pipe = Pipeline([
        ('imputer',    SimpleImputer(strategy='mean')),
        ('scaler',     StandardScaler()),
        ('classifier', RandomForestClassifier(n_estimators=100,
                                               class_weight='balanced',
                                               random_state=42, n_jobs=-1)),
    ])
    rf_pipe.fit(X_tr, y_tr)

    # ── 2. Level 1: TreeSHAP waterfall ────────────────────────────────────
    print('=== Level 1: TreeSHAP ===')
    l1_result = compute_feature_shap(
        rf_pipe, X_te, y_te, sample_idx=0,
        class_names=ALL_CLASSES, feature_names=feat_names,
    )
    print(f'  Predicted class : {l1_result["predicted_class"]}')
    print(f'  Predicted proba : {l1_result["predicted_proba"]}')
    print(f'  Top 5 features  : {[f for f,_ in l1_result["top_features"]]}')

    # ── 3. Level 3: Plain-language narrative ──────────────────────────────
    print('\n=== Level 3: Plain-language narrative ===')
    feat_means = X_tr.mean(axis=0)
    preproc    = rf_pipe[:-1]
    X_trans    = preproc.transform(X_te)
    sv_sample  = shap.TreeExplainer(rf_pipe[-1]).shap_values(X_trans)
    pred_idx   = int(rf_pipe['classifier'].predict(X_trans[[0]])[0])
    sv         = sv_sample[pred_idx][0]

    narrative = plain_language_shap(
        sv, X_trans[0], feat_names, feat_means,
        predicted_class=ALL_CLASSES[pred_idx],
    )
    print(f'\nNarrative:\n{narrative}')

    # ── 4. Calibration smoke test ─────────────────────────────────────────
    print('\n=== Platt scaling calibration ===')
    N_CLS   = N_CLASS
    # Synthetic logits (uniform noise → Brier will be near 0.25)
    logits_v = rng.normal(0, 1, (60, N_CLS)).astype(float)
    y_v      = rng.integers(0, N_CLS, 60)
    logits_t = rng.normal(0, 1, (40, N_CLS)).astype(float)
    y_t      = rng.integers(0, N_CLS, 40)

    cal_result = calibrate_vit_output(
        logits_v, y_v, logits_t, y_t, ALL_CLASSES)
    print(f'  Layer 4 flag : {cal_result["layer4_audit_flag"]}')
    print(f'  Macro Brier  : {cal_result["macro_brier"]}')

    # ── 5. Saliency region summary on a synthetic saliency map ────────────
    print('\n=== Saliency region summary ===')
    # imshow default: row 0 at top → high freq = small row index (near top).
    # _rows() inverts so that higher frequency bands appear higher in the image.
    H, W = IMG_SIZE, IMG_SIZE
    _freq_max = float(FS_HZ) / 2   # 1000 Hz
    _time_max = 250.0               # ms

    def _rows(f_lo, f_hi):
        r_lo = H - int(f_hi / _freq_max * H)
        r_hi = H - int(f_lo / _freq_max * H)
        return max(0, r_lo), min(H, r_hi)

    def _cols(t_lo, t_hi):
        return int(t_lo / _time_max * W), int(t_hi / _time_max * W)

    synthetic_saliency = rng.random((H, W)).astype(np.float32)
    # Inject OP burst signal: 75-300 Hz / 15-70 ms  (upper-left region)
    op_r0, op_r1 = _rows(75, 300)
    op_c0, op_c1 = _cols(15, 70)
    synthetic_saliency[op_r0:op_r1, op_c0:op_c1] += 2.0
    synthetic_saliency = np.clip(synthetic_saliency, 0, 1)

    regions = summarise_saliency_regions(synthetic_saliency)
    print('  Region saliency (normalised):')
    for k, v in sorted(regions.items(), key=lambda x: -x[1]):
        print(f'    {k:<20s} {v:.3f}')

    # ── 6. Visualise saliency regions overlay ─────────────────────────────
    import matplotlib.patches as mpatches

    region_defs = {
        'b_wave_band'   : (_rows(0,   30),  _cols(40,  150), '#2E75B6'),
        'op_burst_band' : (_rows(75, 300),  _cols(15,   70), '#C62828'),
        'phnr_band'     : (_rows(0,   15),  _cols(80,  160), '#2E7D32'),
        'prestim_noise' : (_rows(0,  500),  _cols(0,    20), '#F9A825'),
    }

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    im0 = axes[0].imshow(synthetic_saliency, cmap='hot')
    axes[0].set_title('Synthetic Saliency Map\n(bright square = injected OP burst)',
                      fontsize=10)
    axes[0].set_xlabel('Time (pixels)'); axes[0].set_ylabel('Frequency (pixels, high=top)')
    plt.colorbar(im0, ax=axes[0])

    axes[1].imshow(synthetic_saliency, cmap='hot')
    for rname, ((r0, r1), (c0, c1), col) in region_defs.items():
        rect = mpatches.Rectangle(
            (c0, r0), c1 - c0, r1 - r0,
            linewidth=2, edgecolor=col, facecolor='none', label=rname)
        axes[1].add_patch(rect)
    axes[1].legend(fontsize=8, loc='lower right')
    axes[1].set_title('ERG Region Boundaries on Saliency Map', fontsize=10)
    axes[1].set_xlabel('Time (pixels)'); axes[1].set_ylabel('Frequency (pixels, high=top)')

    fig.suptitle('Chapter 14 - SHAP Saliency Region Analysis\n'
                 '(high freq = top; time increases left to right)',
                 fontsize=11, fontweight='bold')
    plt.tight_layout()
    plt.savefig('ch14_fig1_saliency_regions.png', dpi=150, bbox_inches='tight')
    print('\nSaved: ch14_fig1_saliency_regions.png')
    plt.show()