# -*- coding: utf-8 -*-
"""erg_report_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1byqYZrTmxqoT02IAnz61UES7dmqCjpjc
"""

"""
erg_report_generator.py — v2.4.0 Professional Clinical Report Generator
ERG Analysis API — AI Fairness CIO (Charity Commission No. 1218464)

Generates a fixed-layout, print-quality PDF clinical report using ReportLab,
replacing the v2.3.2 browser print-to-PDF (which captured the upload form UI).

This module is self-contained and can be called from erg_server.py with the
same `full_report` dict already produced by ERGReportGenerator, plus the
waveform arrays already produced by ERGFilter.
"""

import os
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor, white, black
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer, Table, TableStyle,
    KeepTogether, HRFlowable, Image as RLImage
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.pdfgen import canvas as pdfcanvas
from reportlab.graphics.shapes import Drawing, Line, String, Polygon, Rect
from reportlab.graphics import renderPDF

# ── Brand palette (extracted from AI Fairness CIO logo) ───────────────────────
GREEN       = HexColor("#0F3B2D")   # forest green — primary brand
GOLD        = HexColor("#C18A0B")   # gold accent
GREEN_TINT  = HexColor("#EAF1EE")   # pale green background tint
INK         = HexColor("#1A1A1A")   # body text
SLATE       = HexColor("#5A6068")   # secondary text / labels
RULE        = HexColor("#D8DCDD")   # hairline rule
RED_SIG     = HexColor("#B3261E")   # RED traffic light
AMBER_SIG   = HexColor("#9A6700")   # AMBER traffic light
GREEN_SIG   = HexColor("#1E7B34")   # GREEN traffic light
GREY_SIG    = HexColor("#6B7280")   # UNAVAILABLE / grey
PANEL_BG    = HexColor("#F7F8F8")
WAVE_TEAL   = HexColor("#0E7C86")
WAVE_AMBER  = HexColor("#C18A0B")
WAVE_RED    = HexColor("#B3261E")
WAVE_GRID   = HexColor("#E3E6E7")
PURPLE_SIG  = HexColor("#7B3FA0")   # PhNR marker — distinct from a/b colors

ORG_NAME    = "AI Fairness CIO"
ORG_REG     = "Charity Commission for England and Wales · Reg. No. 1218464"
ORG_ADDR    = "London, United Kingdom"
ORG_EMAIL   = "info@ai-fairness.com"
ORG_WEB     = "www.ai-fairness.com"
ORG_TEL     = "+44 (0)7356 287090"
PRODUCT     = "ERG Analysis API"
PRODUCT_VER = "v2.4.0"

LOGO_PATH = "/content/logo_icon.png"

PAGE_W, PAGE_H = A4
MARGIN = 18 * mm

SIGNAL_COLORS = {
    "RED": RED_SIG, "AMBER": AMBER_SIG, "GREEN": GREEN_SIG, "UNAVAILABLE": GREY_SIG,
}
SIGNAL_LABELS = {
    "RED": "Significant Abnormality", "AMBER": "Borderline Abnormality",
    "GREEN": "Within Normal Limits", "UNAVAILABLE": "Reference Range Unavailable",
}

styles = getSampleStyleSheet()

def _style(name, **kw):
    base = dict(fontName="Helvetica", fontSize=9, leading=12, textColor=INK)
    base.update(kw)
    return ParagraphStyle(name, **base)

S_LABEL      = _style("label", fontSize=7.2, textColor=SLATE, leading=9, fontName="Helvetica-Bold")
S_LABEL_ON_DARK = _style("labeldark", fontSize=7.2, textColor=white, leading=9, fontName="Helvetica-Bold")
S_VALUE      = _style("value", fontSize=9.5, leading=12)
S_VALUE_BOLD = _style("valueB", fontSize=9.5, leading=12, fontName="Helvetica-Bold")
S_SECTION    = _style("section", fontSize=10.5, leading=13, fontName="Helvetica-Bold", textColor=GREEN)
S_BODY       = _style("body", fontSize=9, leading=13)
S_BODY_SM    = _style("bodysm", fontSize=8, leading=11, textColor=SLATE)
S_DISCLAIMER = _style("disclaimer", fontSize=7.4, leading=9.8, textColor=SLATE)
S_FINDING_HD = _style("findhd", fontSize=15, leading=18, fontName="Helvetica-Bold")
S_FINDING_BD = _style("findbd", fontSize=9.3, leading=13)


def _fmt(val, unit="", decimals=1, dash="\u2014"):
    if val is None:
        return dash
    try:
        if isinstance(val, float) and (val != val):  # NaN check
            return dash
        return f"{val:.{decimals}f}{unit}"
    except (TypeError, ValueError):
        return str(val)


def _fmt_z(z):
    if z is None:
        return "N/A"
    try:
        if z != z:
            return "N/A"
        sign = "+" if z >= 0 else ""
        return f"Z = {sign}{z:.2f}"
    except (TypeError, ValueError):
        return "N/A"


# ── Header / footer canvas ─────────────────────────────────────────────────

class ReportCanvas(pdfcanvas.Canvas):
    """Custom canvas drawing the letterhead header and footer on every page."""

    def __init__(self, *args, report_meta=None, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_states = []
        self.report_meta = report_meta or {}

    def showPage(self):
        self._draw_header()
        self._draw_footer()
        super().showPage()

    def save(self):
        if self._saved_states or self.getPageNumber() >= 1:
            pass
        super().save()

    def _draw_header(self):
        c = self
        top = PAGE_H - MARGIN

        # Logo icon mark (left)
        try:
            c.drawImage(LOGO_PATH,
                        MARGIN, top - 13 * mm, width=13 * mm, height=13 * mm,
                        preserveAspectRatio=True, mask='auto')
        except Exception:
            pass

        # Org name + product, right next to logo
        c.setFillColor(GREEN)
        c.setFont("Helvetica-Bold", 13)
        c.drawString(MARGIN + 16 * mm, top - 5.5 * mm, ORG_NAME)
        c.setFont("Helvetica", 7.4)
        c.setFillColor(SLATE)
        c.drawString(MARGIN + 16 * mm, top - 9.6 * mm, ORG_REG)

        # Product badge (right-aligned)
        c.setFont("Helvetica-Bold", 11)
        c.setFillColor(INK)
        c.drawRightString(PAGE_W - MARGIN, top - 5.5 * mm, PRODUCT)
        c.setFont("Helvetica", 8)
        c.setFillColor(GOLD)
        c.drawRightString(PAGE_W - MARGIN, top - 9.6 * mm, f"Clinical Decision Support Report  ·  {PRODUCT_VER}")

        # Rule under header
        c.setStrokeColor(GREEN)
        c.setLineWidth(1.1)
        c.line(MARGIN, top - 14.5 * mm, PAGE_W - MARGIN, top - 14.5 * mm)

    def _draw_footer(self):
        c = self
        bottom = MARGIN
        meta = self.report_meta
        c.setStrokeColor(RULE)
        c.setLineWidth(0.6)
        c.line(MARGIN, bottom + 9 * mm, PAGE_W - MARGIN, bottom + 9 * mm)

        c.setFont("Helvetica", 6.6)
        c.setFillColor(SLATE)
        left_txt = (f"{ORG_ADDR}  ·  {ORG_EMAIL}  ·  {ORG_WEB}  ·  {ORG_TEL}")
        c.drawString(MARGIN, bottom + 4.5 * mm, left_txt)

        report_id = meta.get("report_id", "—")
        page_num = c.getPageNumber()
        right_txt = f"Report ID: {report_id}   ·   Page {page_num}"
        c.drawRightString(PAGE_W - MARGIN, bottom + 4.5 * mm, right_txt)

        c.setFont("Helvetica-Oblique", 6.6)
        c.drawCentredString(PAGE_W / 2, bottom, "Clinical Decision Support Only — Not a Medical Diagnosis")


# ── Waveform drawing (vector, not a screenshot) ────────────────────────────

def _sample_at(time_ms, amplitude_uv, t):
    """Return the actual recorded signal value at (or nearest to) time t.
    This guarantees any marker placed at this value sits exactly ON the
    visible trace, regardless of what derived/clinical number is being
    labelled next to it. Never feed a derived distance (e.g. peak-to-trough
    amplitude) into a y-coordinate — sample the real trace instead."""
    if not time_ms:
        return None
    lo, hi = 0, len(time_ms) - 1
    if t <= time_ms[0]:
        return amplitude_uv[0]
    if t >= time_ms[-1]:
        return amplitude_uv[-1]
    while lo < hi:
        mid = (lo + hi) // 2
        if time_ms[mid] < t:
            lo = mid + 1
        else:
            hi = mid
    return amplitude_uv[lo]


def build_waveform_drawing(time_ms, amplitude_uv, op_signal=None, fs_hz=2000.0,
                            pre_stimulus_ms=50.0, a_wave=None, b_wave=None,
                            ba_amplitude_uv=None, phnr_wave=None,
                            width_mm=174, height_mm=52):
    """
    Render the filtered ERG waveform as a true vector graphic (ReportLab Drawing),
    not a rasterised browser screenshot.

    Time axis is FLASH-RELATIVE (t=0 at flash onset, pre-stimulus baseline
    shown as negative ms) — matches ISCEV/clinical device convention
    (RETeval, Espion, etc.) and keeps every ms figure on the chart
    (axis ticks, implicit-time labels) on the same reference frame.

    a_wave / b_wave / phnr_wave: dict with 'time_ms' (ABSOLUTE, i.e.
    pre_stimulus_ms + implicit_time) — any 'amp_uv' key is IGNORED for
    plotting; the actual y-position is always sampled from the real trace
    via _sample_at(), so the dot can never float off the signal.
    phnr_wave is optional — omitted entirely (no fabricated position) unless
    the caller supplies a real measured time.

    ba_amplitude_uv: the derived clinical b-wave amplitude (a-trough to
    b-peak distance, e.g. features['b_wave_amplitude_uv']). Used ONLY for the
    bracket label text — never as a plotting coordinate. Pass None to omit
    the bracket entirely.
    """
    W = width_mm * mm
    H = height_mm * mm
    pad_l, pad_r, pad_t, pad_b = 11 * mm, 6 * mm, 8 * mm, 11 * mm
    plot_w = W - pad_l - pad_r
    plot_h = H - pad_t - pad_b

    d = Drawing(W, H)
    d.add(Rect(0, 0, W, H, fillColor=white, strokeColor=None))

    if not time_ms or not amplitude_uv:
        d.add(String(W / 2, H / 2, "Waveform unavailable", fontSize=8,
                      fillColor=SLATE, textAnchor="middle"))
        return d

    t_min, t_max = min(time_ms), max(time_ms)
    flash_t = t_min + pre_stimulus_ms  # absolute time of flash onset
    a_min, a_max = min(amplitude_uv), max(amplitude_uv)
    a_span = (a_max - a_min) or 1.0
    # Extra headroom top/bottom so dot labels (which sit above peaks / below
    # troughs) never clip against the plot edge regardless of signal shape.
    a_min -= a_span * 0.22
    a_max += a_span * 0.75
    a_span = a_max - a_min

    def xpix(t):
        return pad_l + (t - t_min) / (t_max - t_min) * plot_w

    def ypix(a):
        return pad_b + (a - a_min) / a_span * plot_h

    def rel_ms(t_abs):
        """Convert absolute recording time to flash-relative ms (ISCEV convention)."""
        return t_abs - flash_t

    # Gridlines (horizontal, light) — y-axis (uV) unchanged
    n_grid = 5
    for i in range(n_grid + 1):
        gy = pad_b + i * plot_h / n_grid
        d.add(Line(pad_l, gy, pad_l + plot_w, gy, strokeColor=WAVE_GRID, strokeWidth=0.4))
        val = a_min + i * a_span / n_grid
        d.add(String(pad_l - 2, gy - 2.5, f"{val:.0f}", fontSize=5.6,
                      fillColor=SLATE, textAnchor="end"))

    # Vertical measurement gridlines every 50ms, FLASH-RELATIVE, unlabeled —
    # a visual ruler so any feature's approximate timing can be read off
    # without needing every implicit time explicitly annotated.
    first_tick = (rel_ms(t_min) // 50) * 50
    tick = first_tick
    while tick <= rel_ms(t_max):
        tx_abs = flash_t + tick
        if t_min <= tx_abs <= t_max:
            gx = xpix(tx_abs)
            d.add(Line(gx, pad_b, gx, pad_b + plot_h, strokeColor=WAVE_GRID, strokeWidth=0.35))
        tick += 50

    # Pre-stimulus shaded band
    pre_x0 = xpix(t_min)
    pre_x1 = xpix(flash_t)
    d.add(Rect(pre_x0, pad_b, max(0, pre_x1 - pre_x0), plot_h,
                fillColor=HexColor("#F0F2F2"), strokeColor=None))

    # Flash onset line — this IS t=0 on the displayed axis
    fx = xpix(flash_t)
    d.add(Line(fx, pad_b, fx, pad_b + plot_h, strokeColor=WAVE_RED,
                strokeWidth=0.7, strokeDashArray=[2, 1.5]))
    d.add(String(fx + 1.5, pad_b + plot_h - 6, "Flash (0ms)", fontSize=5.8, fillColor=WAVE_RED))

    # OP band overlay (dashed amber) if provided
    if op_signal and len(op_signal) == len(time_ms):
        pts = []
        step = max(1, len(time_ms) // 700)
        for i in range(0, len(time_ms), step):
            pts.extend([xpix(time_ms[i]), ypix(op_signal[i])])
        if len(pts) >= 4:
            from reportlab.graphics.shapes import PolyLine
            d.add(PolyLine(pts, strokeColor=WAVE_AMBER, strokeWidth=0.6, strokeDashArray=[3, 2]))

# Main filtered signal (teal), decimated for vector size
    pts = []
    step = max(1, len(time_ms) // 700)
    for i in range(0, len(time_ms), step):
        pts.extend([xpix(time_ms[i]), ypix(amplitude_uv[i])])
    if len(pts) >= 4:
        from reportlab.graphics.shapes import PolyLine
        d.add(PolyLine(pts, strokeColor=WAVE_TEAL, strokeWidth=1.1))

    def _label_y(dot_y, prefer_above, text_h=7):
        """Flip label above/below the dot as needed so it never clips the
        top or bottom of the plot area, regardless of where the dot sits."""
        if prefer_above:
            y = dot_y + 10
            if y + text_h > pad_b + plot_h - 2:
                y = dot_y - text_h - 2
        else:
            y = dot_y - text_h
            if y < pad_b + 2:
                y = dot_y + 4
        return y

    def _labeled(x, y, text, color, anchor="start"):
        """Draw a text label with a white backing plate so it stays legible
        regardless of what's behind it (trace line, bracket, gridlines)."""
        text_w = len(text) * 3.3 + 2
        rect_x = x if anchor == "start" else x - text_w / 2
        d.add(Rect(rect_x - 1, y - 1.3, text_w + 2, 7, fillColor=white, strokeColor=None))
        d.add(String(x, y, text, fontSize=6.2, fillColor=color, textAnchor=anchor))

    # a-wave / b-wave markers — y-position is ALWAYS the real sampled trace    # value at that timestamp, never a derived/clinical distance (see
    # _sample_at docstring and Phase 0.2 of the waveform SOP).
    #
    # Labels are deliberately worded "a-trough" / "b-peak" rather than bare
    # "a"/"b" — these are RAW heights above baseline, NOT the same quantity
    # as the table's "A-/B-Wave Amplitude" rows (which for the b-wave is a
    # peak-to-trough DISTANCE, not a height). Conflating the two caused
    # real user confusion in a previous round.
    a_raw_y = a_x = None
    b_raw_y = b_x = None
    if a_wave and a_wave.get("time_ms") is not None:
        a_imp_ms = rel_ms(a_wave["time_ms"])
        a_raw = _sample_at(time_ms, amplitude_uv, a_wave["time_ms"])
        a_x, a_raw_y = xpix(a_wave["time_ms"]), ypix(a_raw)
        d.add(_circle_marker(a_x, a_raw_y, RED_SIG))
        ly = _label_y(a_raw_y, prefer_above=False)
        _labeled(a_x + 3, ly, f"a-trough {a_raw:.0f}uV", RED_SIG)
        d.add(Line(a_x, pad_b, a_x, pad_b - 3, strokeColor=RED_SIG, strokeWidth=0.8))
        d.add(String(a_x, pad_b - 11, f"{a_imp_ms:.1f}ms", fontSize=5.4,
                      fillColor=RED_SIG, textAnchor="middle"))
    if b_wave and b_wave.get("time_ms") is not None:
        b_imp_ms = rel_ms(b_wave["time_ms"])
        b_raw = _sample_at(time_ms, amplitude_uv, b_wave["time_ms"])
        b_x, b_raw_y = xpix(b_wave["time_ms"]), ypix(b_raw)
        d.add(_circle_marker(b_x, b_raw_y, GREEN_SIG))
        ly = _label_y(b_raw_y, prefer_above=True)
        _labeled(b_x + 3, ly, f"b-peak {b_raw:.0f}uV", GREEN_SIG)
        d.add(Line(b_x, pad_b, b_x, pad_b - 3, strokeColor=GREEN_SIG, strokeWidth=0.8))
        d.add(String(b_x, pad_b - 11, f"{b_imp_ms:.1f}ms", fontSize=5.4,
                      fillColor=GREEN_SIG, textAnchor="middle"))
    if phnr_wave and phnr_wave.get("time_ms") is not None:
        p_imp_ms = rel_ms(phnr_wave["time_ms"])
        p_raw = _sample_at(time_ms, amplitude_uv, phnr_wave["time_ms"])
        p_x, p_raw_y = xpix(phnr_wave["time_ms"]), ypix(p_raw)
        d.add(_circle_marker(p_x, p_raw_y, PURPLE_SIG))
        # PhNR label always placed BELOW its dot, regardless of sign --
        # "above" collides with the B-Wave Amp bracket when PhNR sits close
        # in time to the b-peak (a known case: atypical positive PhNR).
        ly = p_raw_y - 9
        if ly < pad_b + 2:
            ly = p_raw_y + 4
        _labeled(p_x + 3, ly, f"PhNR {p_raw:.0f}uV", PURPLE_SIG)
        d.add(Line(p_x, pad_b, p_x, pad_b - 3, strokeColor=PURPLE_SIG, strokeWidth=0.8))
        d.add(String(p_x, pad_b - 11, f"{p_imp_ms:.1f}ms", fontSize=5.4,
                      fillColor=PURPLE_SIG, textAnchor="middle"))

    # ISCEV-style bracket: the derived clinical B-Wave Amplitude is a
    # DISTANCE (a-trough to b-peak), so it is drawn as a vertical bracket
    # spanning the two real sampled y-positions, never as a single dot
    # height. Label uses the EXACT same wording as the Layer 2 table row
    # ("B-Wave Amp") so it reads as the same quantity, not a third number.
    if ba_amplitude_uv is not None and a_raw_y is not None and b_raw_y is not None:
        bracket_x = max(a_x, b_x)
        y_lo, y_hi = min(a_raw_y, b_raw_y), max(a_raw_y, b_raw_y)
        d.add(Line(bracket_x, y_lo, bracket_x, y_hi, strokeColor=SLATE, strokeWidth=0.6))
        d.add(Line(bracket_x - 1.5, y_lo, bracket_x + 1.5, y_lo, strokeColor=SLATE, strokeWidth=0.6))
        d.add(Line(bracket_x - 1.5, y_hi, bracket_x + 1.5, y_hi, strokeColor=SLATE, strokeWidth=0.6))
        label_y = (y_lo + y_hi) / 2 - 2.5
        label_text = f"B-Wave Amp {ba_amplitude_uv:.1f}uV"
        label_w = len(label_text) * 3.2 + 3
        d.add(Rect(bracket_x + 1.5, label_y - 1.2, label_w, 6.5,
                    fillColor=white, strokeColor=None))
        d.add(String(bracket_x + 2.5, label_y, label_text, fontSize=6.2,
                      fillColor=SLATE, fontName="Helvetica-Bold"))

    # Axis labels
    d.add(String(pad_l + plot_w / 2, 3, "Time (ms, relative to flash)", fontSize=6.4,
                  fillColor=SLATE, textAnchor="middle"))
    d.add(String(2, pad_b + plot_h / 2, "uV", fontSize=6.4,
                  fillColor=SLATE, textAnchor="start"))
    # X tick labels at the two recording boundaries, flash-relative
    d.add(String(xpix(t_min), 3 + 6.5, f"{rel_ms(t_min):.0f}", fontSize=5.6, fillColor=SLATE))
    d.add(String(xpix(t_max), 3 + 6.5, f"{rel_ms(t_max):.0f}", fontSize=5.6,
                  fillColor=SLATE, textAnchor="end"))

    # Border box
    d.add(Rect(pad_l, pad_b, plot_w, plot_h, fillColor=None, strokeColor=RULE, strokeWidth=0.6))

    return d


def _circle_marker(x, y, color, r=2.0):
    from reportlab.graphics.shapes import Circle
    return Circle(x, y, r, fillColor=white, strokeColor=color, strokeWidth=1.1)


# ── Traffic light badge (vector) ───────────────────────────────────────────

def traffic_light_badge(signal, size=9 * mm):
    color = SIGNAL_COLORS.get(signal, GREY_SIG)
    d = Drawing(size, size)
    from reportlab.graphics.shapes import Circle
    d.add(Circle(size / 2, size / 2, size / 2 - 0.5, fillColor=color, strokeColor=None))
    return d


# ── Section builders ───────────────────────────────────────────────────────

def build_patient_block(meta):
    rows = [
        [Paragraph("PATIENT ID", S_LABEL), Paragraph("AGE STRATUM", S_LABEL),
         Paragraph("PROTOCOL", S_LABEL), Paragraph("ELECTRODE", S_LABEL)],
        [Paragraph(meta.get("patient_id", "UNKNOWN"), S_VALUE_BOLD),
         Paragraph(meta.get("age_stratum", "—"), S_VALUE_BOLD),
         Paragraph(meta.get("protocol", "—"), S_VALUE_BOLD),
         Paragraph(meta.get("electrode", "—"), S_VALUE_BOLD)],
        [Paragraph("RECORDING DATE", S_LABEL), Paragraph("REPORT GENERATED", S_LABEL),
         Paragraph("SAMPLING RATE", S_LABEL), Paragraph("PROCESSING TIME", S_LABEL)],
        [Paragraph(meta.get("recording_date", "—"), S_VALUE),
         Paragraph(meta.get("report_generated", "—"), S_VALUE),
         Paragraph(meta.get("fs_hz", "—"), S_VALUE),
         Paragraph(meta.get("processing_ms", "—"), S_VALUE)],
    ]
    t = Table(rows, colWidths=[42 * mm] * 4)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), PANEL_BG),
        ("BOX", (0, 0), (-1, -1), 0.6, RULE),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, RULE),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return t


def build_traffic_light_panel(traffic_light):
    signal = traffic_light.get("signal", "UNAVAILABLE")
    message = traffic_light.get("message", "")
    confidence = traffic_light.get("confidence")
    if isinstance(confidence, (int, float)) and confidence <= 1.0:
        confidence = confidence * 100
    color = SIGNAL_COLORS.get(signal, GREY_SIG)

    badge = traffic_light_badge(signal, size=9 * mm)
    heading = Paragraph(f'<font color="{color.hexval()}">{signal}</font>', S_FINDING_HD)
    sublabel = Paragraph(SIGNAL_LABELS.get(signal, ""), _style("sub", fontSize=8.5,
                          textColor=SLATE, fontName="Helvetica-Bold"))
    msg = Paragraph(message or "—", S_FINDING_BD)

    conf_txt = f"{confidence:.0f}%" if isinstance(confidence, (int, float)) else "N/A"
    conf_block = Table([
        [Paragraph(conf_txt, _style("confnum", fontSize=16, fontName="Helvetica-Bold",
                                     textColor=INK, alignment=TA_CENTER, leading=18))],
        [Paragraph("CONFIDENCE", _style("conflbl", fontSize=6.2, textColor=SLATE,
                                         alignment=TA_CENTER, fontName="Helvetica-Bold", leading=8))],
    ], colWidths=[28 * mm])
    conf_block.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, 0), 0), ("BOTTOMPADDING", (0, 0), (-1, 0), 1),
        ("TOPPADDING", (0, 1), (-1, 1), 0), ("BOTTOMPADDING", (0, 1), (-1, 1), 0),
    ]))

    left_col = Table([[badge, Spacer(1, 1)], ], colWidths=[10 * mm])
    left_col.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")]))

    text_col = [heading, sublabel, Spacer(1, 3), msg]

    inner = Table([[left_col, text_col, conf_block]],
                   colWidths=[12 * mm, 122 * mm, 28 * mm])
    inner.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (0, 0), 0),
    ]))

    wrapper = Table([[inner]], colWidths=[174 * mm])
    bg = HexColor("#FBEAE9") if signal == "RED" else (
        HexColor("#FCF3E3") if signal == "AMBER" else (
        HexColor("#E9F5EC") if signal == "GREEN" else HexColor("#F1F2F3")))
    wrapper.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), bg),
        ("BOX", (0, 0), (-1, -1), 0, None),
        ("LINEBELOW", (0, 0), (-1, -1), 2.2, color),
        ("TOPPADDING", (0, 0), (-1, -1), 7), ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 10), ("RIGHTPADDING", (0, 0), (-1, -1), 10),
    ]))
    return wrapper


def build_metrics_table(features, z_scores, zscore_available=True):
    """Layer 2 — clinical parameter metrics grid (4 columns x N rows)."""
    phnr_atypical = bool(features.get("phnr_polarity_atypical", False)) if features else False

    def z_cell(key):
        z = z_scores.get(key) if z_scores else None
        if not zscore_available:
            return Paragraph("No norms", _style("nonorm", fontSize=8, textColor=GREY_SIG,
                                                  fontName="Helvetica-Oblique"))
        if z is None:
            return Paragraph("N/A", _style("na", fontSize=8, textColor=SLATE))
        color = (RED_SIG if abs(z) > 3.0 else AMBER_SIG if abs(z) > 2.0 else GREEN_SIG)
        return Paragraph(_fmt_z(z), _style("zval", fontSize=8.6, fontName="Helvetica-Bold",
                                            textColor=color))

    rows = [[
        Paragraph("PARAMETER", S_LABEL_ON_DARK), Paragraph("VALUE", S_LABEL_ON_DARK),
        Paragraph("Z-SCORE", S_LABEL_ON_DARK), Paragraph("STATUS", S_LABEL_ON_DARK)
    ]]

    param_defs = [
        ("a_wave_amplitude_uv", "A-Wave Amplitude", "uV", "a_wave_amplitude"),
        ("b_wave_amplitude_uv", "B-Wave Amplitude", "uV", "b_wave_amplitude"),
        ("b_wave_implicit_time_ms", "B-Wave Implicit Time", "ms", "b_wave_implicit_time"),
        ("ba_ratio", "B/A Ratio", "", "ba_ratio"),
        ("phnr_amp_uv", "PhNR Amplitude", "uV", None),
    ]

    for fkey, label, unit, zkey in param_defs:
        val = features.get(fkey) if features else None
        if val is None:
            continue
        decimals = 2 if fkey == "ba_ratio" else 1
        val_txt = _fmt(val, unit, decimals=decimals)
        val_color = INK
        if fkey == "phnr_amp_uv" and val is not None:
            # phnr_amp_uv is signed at source (v2.4.1): negative = typical
            # below-baseline deflection, positive = atypical above-baseline.
            sign = "+" if val > 0 else ("\u2212" if val < 0 else "")
            val_txt = f"{sign}{abs(val):.1f}{unit}"
            if phnr_atypical:
                val_color = RED_SIG
        z_para = z_cell(zkey) if zkey else Paragraph(
            "Ref. pending", _style("pend", fontSize=7.6, textColor=SLATE,
                                    fontName="Helvetica-Oblique"))
        status_txt, status_color = "—", SLATE
        if zkey and z_scores and z_scores.get(zkey) is not None and zscore_available:
            zz = z_scores[zkey]
            if abs(zz) > 3.0:
                status_txt, status_color = "RED", RED_SIG
            elif abs(zz) > 2.0:
                status_txt, status_color = "AMBER", AMBER_SIG
            else:
                status_txt, status_color = "GREEN", GREEN_SIG
        elif fkey == "phnr_amp_uv" and phnr_atypical:
            status_txt, status_color = "CHECK QUALITY", RED_SIG
        elif fkey == "phnr_amp_uv":
            status_txt, status_color = "Pending", SLATE
        elif not zscore_available:
            status_txt, status_color = "UNAVAILABLE", GREY_SIG

        rows.append([
            Paragraph(label, S_VALUE),
            Paragraph(val_txt, ParagraphStyle("valB_dyn", parent=S_VALUE_BOLD, textColor=val_color)),
            z_para,
            Paragraph(status_txt, _style("st", fontSize=8.2, fontName="Helvetica-Bold",
                                          textColor=status_color)),
        ])

    t = Table(rows, colWidths=[58 * mm, 38 * mm, 38 * mm, 40 * mm])
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), GREEN),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 7.2),
        ("TOPPADDING", (0, 0), (-1, 0), 4), ("BOTTOMPADDING", (0, 0), (-1, 0), 4),
        ("TOPPADDING", (0, 1), (-1, -1), 4), ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("LINEBELOW", (0, 0), (-1, -2), 0.4, RULE),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]
    for i in range(1, len(rows)):
        if i % 2 == 0:
            style.append(("BACKGROUND", (0, i), (-1, i), HexColor("#FBFBFB")))
    t.setStyle(TableStyle(style))
    return t


def build_quality_panel(quality):
    grade = quality.get("grade", "—")
    desc = quality.get("description", "")
    snr_db = quality.get("snr_db")
    snr_status = quality.get("snr_status", "")
    grade_color = {"A": GREEN_SIG, "B": GREEN_SIG, "C": AMBER_SIG, "D": RED_SIG, "F": RED_SIG}.get(grade, SLATE)

    rows = [[
        Paragraph("SIGNAL QUALITY GRADE", S_LABEL),
        Paragraph("SNR", S_LABEL),
        Paragraph("ISCEV 2022 COMPLIANCE", S_LABEL),
    ], [
        Paragraph(f'<font color="{grade_color.hexval()}"><b>{grade}</b></font>  {desc}', S_VALUE),
        Paragraph(f"{_fmt(snr_db, ' dB')}  ({snr_status})" if snr_db is not None else "—", S_VALUE),
        Paragraph(quality.get("iscev_text", "Compliant"), S_VALUE),
    ]]
    t = Table(rows, colWidths=[80 * mm, 47 * mm, 47 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), PANEL_BG),
        ("BOX", (0, 0), (-1, -1), 0.6, RULE),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, RULE),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return t


DISCLAIMER_TEXT = (
    "This result is generated by an automated signal analysis algorithm and is intended to support, "
    "not replace, clinical judgment. It does not constitute a medical diagnosis. All results should be "
    "interpreted in the context of the patient's full clinical history, examination findings, and "
    "relevant investigations by a qualified healthcare professional. A Green ERG signal does not "
    "exclude significant ocular or systemic pathology. If you have any concern about this patient's "
    "visual function, please refer to an appropriate specialist."
)


def build_disclaimer_block():
    t = Table([[Paragraph(f"<b>Clinical Decision Support Disclaimer.</b> {DISCLAIMER_TEXT}", S_DISCLAIMER)]],
               colWidths=[174 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), HexColor("#FFFDF5")),
        ("BOX", (0, 0), (-1, -1), 0.6, GOLD),
        ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 8), ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return t


PHNR_ATYPICAL_TEXT = (
    "<b>DATA QUALITY WARNING \u2014 Atypical PhNR Polarity.</b> The Photopic Negative Response is "
    "defined as a negative-going deflection below baseline in all published normative and "
    "pathological data. A positive (above-baseline) reading is <b>not a recognised alternate "
    "clinical state</b>. Likely causes: electrode polarity inversion, baseline drift or "
    "low-frequency noise, or another waveform feature (b-wave tail, i-wave, or oscillatory "
    "potential ringing) dominating the search window in place of a true, smaller PhNR trough. "
    "Verify electrode connection and signal quality before any clinical interpretation of this "
    "value."
)


def build_phnr_warning_block():
    t = Table([[Paragraph(PHNR_ATYPICAL_TEXT, ParagraphStyle(
        "phnrwarn", parent=S_DISCLAIMER, textColor=RED_SIG))]],
               colWidths=[174 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), HexColor("#FBEAE9")),
        ("BOX", (0, 0), (-1, -1), 0.8, RED_SIG),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 8), ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return t


def section_heading(text):
    return [
        Spacer(1, 2),
        Paragraph(text.upper(), S_SECTION),
        HRFlowable(width="100%", thickness=0.7, color=GREEN, spaceBefore=1.5, spaceAfter=4),
    ]


# ── Main entry point ───────────────────────────────────────────────────────

def generate_clinical_report_pdf(output_path, full_report, waveform_data, meta=None):
    """
    Parameters
    ----------
    output_path : str — file path to write the PDF to
    full_report : dict — the existing ERGReportGenerator output
                  (layer_1_traffic_light, layer_2_clinical_summary, etc.)
    waveform_data : dict — {time_ms, amplitude_uv, op_signal, fs_hz, pre_stimulus_ms,
                             a_wave: {time_ms}, b_wave: {time_ms}}
                             (any 'amp_uv' key is ignored — y-position is always
                             sampled from the real trace, see _sample_at())
    meta : dict — optional override for patient_id, age_stratum, protocol, electrode,
                  recording_date, report_generated, report_id
    """
    meta = meta or {}
    layer1 = full_report.get("layer_1_traffic_light", full_report.get("traffic_light", {}))
    layer4 = full_report.get("layer_4_technical_audit", {})

    # The live API response (erg_server.py /api/v1/analyse) is flat:
    #   { traffic_light, features, z_scores, audit_results: {quality, snr, iscev_compliance}, ... }
    # full_report may be passed either as that flat dict, or as the nested
    # ERGReportGenerator output (layer_1_..., layer_2_..., etc). Support both.
    features = full_report.get("features", {})
    z_scores = full_report.get("z_scores",
                   full_report.get("layer_2_clinical_summary", {}).get("z_scores", {}))
    audit_results = full_report.get("audit_results", {})
    zscore_available = layer4.get("zscore_available", True)

    quality_raw = audit_results.get("quality", full_report.get("quality", {}))
    snr_raw     = audit_results.get("snr", {})
    iscev_raw   = audit_results.get("iscev_compliance", {})

    quality = {
        "grade": quality_raw.get("grade", "—"),
        "description": quality_raw.get("description", ""),
        "snr_db": snr_raw.get("db"),
        "snr_status": snr_raw.get("status", ""),
        "iscev_text": (
            "Compliant" if iscev_raw.get("overall_compliant") else
            "Non-compliant" if iscev_raw.get("overall_compliant") is False else "—"
        ),
    }

    fhir_obs = full_report.get("fhir_observation", {})
    report_id = layer4.get("report_id") or fhir_obs.get("id") or meta.get("report_id") or \
        f"ERG-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

    fhir_patient_id = "UNKNOWN"
    if fhir_obs.get("subject", {}).get("reference"):
        fhir_patient_id = fhir_obs["subject"]["reference"].replace("Patient/", "")

    meta_full = {
        "patient_id": meta.get("patient_id") or fhir_patient_id,
        "age_stratum": meta.get("age_stratum", layer4.get("age_stratum", "—")),
        "protocol": meta.get("protocol", layer4.get("protocol", "—")),
        "electrode": meta.get("electrode", layer4.get("electrode_type", "—")),
        "recording_date": meta.get("recording_date", "—"),
        "report_generated": datetime.now().strftime("%d %B %Y, %H:%M"),
        "fs_hz": f"{waveform_data.get('fs_hz', 2000):.0f} Hz",
        "processing_ms": _fmt(
            full_report.get("processing_ms", layer4.get("processing_time_ms")),
            " ms", decimals=0),
        "report_id": report_id,
    }

    doc = BaseDocTemplate(
        output_path, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN + 14 * mm, bottomMargin=MARGIN + 8 * mm,
        title=f"ERG Clinical Report — {meta_full['patient_id']}",
        author=ORG_NAME,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="main")

    def _make_canvas(*args, **kw):
        return ReportCanvas(*args, report_meta=meta_full, **kw)

    doc.addPageTemplates([PageTemplate(id="report", frames=[frame])])

    story = []

    # Title row
    story.append(Paragraph("Full-Field Electroretinogram — Clinical Decision Support Report",
                            _style("doctitle", fontSize=13, leading=17,
                                   fontName="Helvetica-Bold", textColor=INK)))
    story.append(Spacer(1, 5))
    story.append(Paragraph(
        "ISCEV 2022-compliant signal processing &nbsp;\u00b7&nbsp; "
        "Normative reference: Baker et al. (2025), N=407, DOI:10.1007/s10633-025-10009-2",
        _style("subtitle", fontSize=7.6, leading=10, textColor=SLATE)))
    story.append(Spacer(1, 3))

    story.append(build_patient_block(meta_full))
    story.append(Spacer(1, 3))

    story.extend(section_heading("Layer 1 — Traffic Light Result"))
    story.append(build_traffic_light_panel(layer1))

    story.extend(section_heading("Layer 2 — Clinical Parameter Summary"))
    story.append(build_metrics_table(features, z_scores, zscore_available))
    if features.get("phnr_polarity_atypical"):
        story.append(Spacer(1, 3))
        story.append(build_phnr_warning_block())

    story.extend(section_heading("Filtered ERG Waveform"))
    wf_drawing = build_waveform_drawing(
        waveform_data.get("time_ms", []),
        waveform_data.get("amplitude_uv", []),
        op_signal=waveform_data.get("op_signal"),
        fs_hz=waveform_data.get("fs_hz", 2000.0),
        pre_stimulus_ms=waveform_data.get("pre_stimulus_ms", 50.0),
        a_wave=waveform_data.get("a_wave"),
        b_wave=waveform_data.get("b_wave"),
        phnr_wave=waveform_data.get("phnr_wave"),
        ba_amplitude_uv=features.get("b_wave_amplitude_uv"),
        height_mm=42,
    )
    story.append(wf_drawing)
    legend = Table([[
        Paragraph('<font color="#0E7C86">\u2014\u2014</font> Filtered signal', S_BODY_SM),
        Paragraph('<font color="#C18A0B">\u2014 \u2014</font> OP band', S_BODY_SM),
        Paragraph('<font color="#B3261E">\u2014 \u2014</font> Flash onset', S_BODY_SM),
        Paragraph('Shaded region: pre-stimulus baseline', S_BODY_SM),
    ]], colWidths=[34 * mm, 34 * mm, 34 * mm, 72 * mm])
    legend.setStyle(TableStyle([("TOPPADDING", (0, 0), (-1, -1), 1),
                                 ("BOTTOMPADDING", (0, 0), (-1, -1), 0)]))
    story.append(legend)

    story.extend(section_heading("Layer 3 — Signal Quality & ISCEV Compliance"))
    story.append(build_quality_panel(quality))
    story.append(Spacer(1, 4))
    story.append(build_disclaimer_block())

    doc.build(story, canvasmaker=_make_canvas)
    return output_path


# ── Standalone demo / test harness ─────────────────────────────────────────

if __name__ == "__main__":
    import numpy as np

    def _demo_synth_trace(fs, pre_ms, a_t, a_amp, b_t, b_wave_amplitude_uv,
                           n=700, noise=2.5, decay_tau=45.0, seed=0):
        """Build a synthetic ERG trace whose REAL sampled values are physically
        consistent with the declared clinical parameters:
          sig(a_t) == a_amp                              (a-wave trough)
          sig(b_t) == a_amp + b_wave_amplitude_uv         (b-wave peak)
        because B-Wave Amplitude is defined as the a-trough-to-b-peak DISTANCE,
        not a height above baseline (SOP Phase 0.1/0.2). Demo-only — real
        pipeline data is self-consistent by construction since amplitudes are
        computed directly from the recorded trace."""
        rng = np.random.default_rng(seed)
        peak_uv = a_amp + b_wave_amplitude_uv
        t = (np.arange(n) / fs * 1000).tolist()
        sig = np.zeros(n)
        for i in range(n):
            tt = t[i] - pre_ms
            if tt < 0:
                sig[i] = rng.normal(0, noise)
            elif tt <= a_t:
                frac = tt / a_t if a_t else 1.0
                sig[i] = a_amp * (1 - np.cos(np.pi * frac)) / 2 + rng.normal(0, noise)
            elif tt <= b_t:
                frac = (tt - a_t) / (b_t - a_t) if b_t > a_t else 1.0
                sig[i] = a_amp + (peak_uv - a_amp) * (1 - np.cos(np.pi * frac)) / 2 + rng.normal(0, noise)
            else:
                sig[i] = peak_uv * np.exp(-(tt - b_t) / decay_tau) + rng.normal(0, noise)
        return t, sig.tolist()

    # Reconstruct the DR demo case from the v2.3.2 screenshot for a realistic demo
    fs = 2000.0
    n = 700
    pre_ms = 50.0
    t, sig_list = _demo_synth_trace(fs, pre_ms, a_t=15.5, a_amp=-134.7,
                                     b_t=56.5, b_wave_amplitude_uv=163.4)
    sig = np.array(sig_list)
    op = (8 * np.exp(-((np.array(t) - pre_ms - 20) ** 2) / (2 * 30 ** 2))).tolist()

    demo_full_report = {
        # This mirrors the EXACT shape returned by erg_server.py /api/v1/analyse
        "traffic_light": {
            "signal": "RED",
            "message": ("Significant abnormality: ba ratio reduction — consistent with inner "
                        "retinal dysfunction or disproportionate a-wave loss (Z=3.4). Urgent "
                        "review required."),
            "confidence": 0.90,   # live API sends a 0–1 fraction, see ERG_API_v2_4.html *100
        },
        "features": {
            "a_wave_amplitude_uv": -134.7, "b_wave_amplitude_uv": 163.4,
            "b_wave_implicit_time_ms": 56.5, "ba_ratio": 1.21,
            "phnr_amp_uv": None,
        },
        "z_scores": {
            "a_wave_amplitude": -1.33, "b_wave_amplitude": -2.22,
            "b_wave_implicit_time": 1.60, "ba_ratio": -3.39,
        },
        "audit_results": {
            "quality": {"grade": "B", "description": "Good — minor issues present, OP features likely usable"},
            "snr": {"db": 9.1, "status": "PASS", "electrode_type": "gold_foil"},
            "iscev_compliance": {
                "overall_compliant": True,
                "sampling_rate_ok": True, "sampling_rate_value": 2000,
                "prestimulus_ok": True, "prestimulus_value": 50,
                "post_stimulus_ok": True, "post_stimulus_value": 300,
            },
        },
        "fhir_observation": {
            "id": "ERG-20260620-DEMO01",
            "subject": {"reference": "Patient/DEMO-DR-001"},
        },
        "processing_ms": 36,
        "layer_4_technical_audit": {
            "zscore_available": True,
        },
    }

    demo_waveform = {
        "time_ms": t, "amplitude_uv": sig.tolist(), "op_signal": op,
        "fs_hz": fs, "pre_stimulus_ms": pre_ms,
        "a_wave": {"time_ms": pre_ms + 15.5},
        "b_wave": {"time_ms": pre_ms + 56.5},
    }

    demo_meta = {
        "patient_id": "DEMO-DR-001",
        "recording_date": "20 June 2026",
        "protocol": "DA 3",
        "electrode": "Gold Foil",
        "age_stratum": "\u226435y",
    }

    out = generate_clinical_report_pdf(
        "/content/ERG_Clinical_Report_DEMO.pdf",
        demo_full_report, demo_waveform, demo_meta
    )
    print("Generated:", out)